// Hand-authored TEF theme unit (spec §3.2.1) — "La consommation" (Consumption). Part of the full
// TEF theme coverage in the Learn path. Exports the same { unit, items } shape as generated units
// (spec §3.2.6). All exercises are tap-only (spec §3.2.2).

export const unit = {
  id: 'consommation',
  title: 'La consommation',
  description: 'Discuss shopping, buying habits, and sustainable consumption.',
  lessons: [
    {
      id: 'consommation-vocabulaire',
      title: 'Vocabulaire de la consommation',
      learningItemIds: ['achat', 'produit', 'prix', 'vente'],
      exercises: [
        {
          id: 'cns-1',
          learningItemId: 'achat',
          type: 'multiple_choice',
          stage: 'recognition',
          prompt: 'What does "un achat" mean?',
          content: { options: ['a purchase', 'a wish', 'a habit', 'a bill'] },
          answer: 'a purchase',
          explanation: '"Un achat" is a "purchase."',
        },
        {
          id: 'cns-2',
          learningItemId: 'produit',
          type: 'multiple_choice',
          stage: 'recognition',
          prompt: 'What does "un produit" mean?',
          content: { options: ['a product', 'a price', 'a promise', 'a problem'] },
          answer: 'a product',
          explanation: '"Un produit" is a "product."',
        },
        {
          id: 'cns-3',
          learningItemId: 'prix',
          type: 'translation',
          stage: 'recall',
          prompt: 'Translate: price',
          content: { direction: 'en_to_fr', options: ['prix', 'pris', 'pré', 'prie'] },
          answer: 'prix',
          explanation: '"Price" translates to "le prix."',
        },
        {
          id: 'cns-4',
          learningItemId: 'vente',
          type: 'translation',
          stage: 'recall',
          prompt: 'Translate: sale',
          content: { direction: 'en_to_fr', options: ['vente', 'vent', 'vêtement', 'vie'] },
          answer: 'vente',
          explanation: '"Sale" translates to "la vente."',
        },
        {
          id: 'cns-5',
          learningItemId: 'achat',
          type: 'fill_blank',
          stage: 'context',
          prompt: 'Complete the sentence',
          content: {
            sentence: 'Je réfléchis avant de faire un ______ en ligne.',
            options: ['achat', 'accueil', 'appui', 'accord'],
          },
          answer: 'achat',
          explanation: '"Faire un achat" — to make a purchase.',
        },
        {
          id: 'cns-6',
          learningItemId: 'produit',
          type: 'fill_blank',
          stage: 'context',
          prompt: 'Complete the sentence',
          content: {
            sentence: 'Ce ______ local est de bonne qualité.',
            options: ['produit', 'projet', 'processus', 'produit laitier derivé'],
          },
          answer: 'produit',
          explanation: '"Un produit local" — a local product.',
        },
      
        {
          id: 'cns-19',
          learningItemId: 'achat',
          type: 'fill_blank',
          stage: 'context',
          prompt: 'Quel mot complète la phrase suivante ? "J’ai fait un ___ pour acheter un nouveau téléphone."',
          content: {"sentence":"J’ai fait un ___ pour acheter un nouveau téléphone.","options":["achat","produit","prix","vente"]},
          answer: 'achat',
          explanation: 'The blank should be "achat", meaning a purchase.',
        },
        {
          id: 'cns-20',
          learningItemId: 'produit',
          type: 'multiple_choice',
          stage: 'recall',
          prompt: 'Le mot français "produit" se traduit en anglais par…',
          content: {"options":["product","price","sale","purchase"]},
          answer: 'product',
          explanation: '"Produit" means "product" in English.',
        },
        {
          id: 'cns-21',
          learningItemId: 'prix',
          type: 'translation',
          stage: 'recall',
          prompt: 'Translate into French: "The price of the book is high."',
          content: {"options":["Le prix du livre est élevé.","Le produit du livre est élevé.","La vente du livre est élevée.","Le achat du livre est élevé."]},
          answer: 'Le prix du livre est élevé.',
          explanation: 'The correct translation is "Le prix du livre est élevé."',
        },
        {
          id: 'cns-22',
          learningItemId: 'vente',
          type: 'pronunciation',
          stage: 'production',
          prompt: 'Prononcez la phrase suivante en français : "La vente a commencé à midi."',
          content: {"sentence":"La vente a commencé à midi."},
          answer: 'La vente a commencé à midi.',
          explanation: 'Practice the pronunciation of "La vente a commencé à midi."',
        },
        {
          id: 'cns-23',
          learningItemId: 'achat',
          type: 'multiple_choice',
          stage: 'transformation',
          prompt: 'Choisissez la forme correcte du nom féminin correspondant à "achat".',
          content: {"options":["achat","achatée","achats","achate"]},
          answer: 'achats',
          explanation: 'The plural of "achat" is "achats".',
        },
        {
          id: 'cns-24',
          learningItemId: 'produit',
          type: 'fill_blank',
          stage: 'completion',
          prompt: 'Complétez la phrase : "Ce ___ est fabriqué à partir de matériaux recyclés."',
          content: {"sentence":"Ce ___ est fabriqué à partir de matériaux recyclés.","options":["produit","prix","achat","vente"]},
          answer: 'produit',
          explanation: 'The correct word is "produit" meaning product.',
        },
        {
          id: 'cns-25',
          learningItemId: 'prix',
          type: 'multiple_choice',
          stage: 'recognition',
          prompt: 'Quel est le sens de "prix" en anglais ?',
          content: {"options":["price","product","sale","purchase"]},
          answer: 'price',
          explanation: '"Prix" translates to "price".',
        },
        {
          id: 'cns-26',
          learningItemId: 'achat',
          type: 'pronunciation',
          stage: 'production',
          prompt: 'Prononcez la phrase suivante en français : "Je fais un achat important aujourd’hui."',
          content: {"sentence":"Je fais un achat important aujourd’hui."},
          answer: 'Je fais un achat important aujourd’hui.',
          explanation: 'Practice the pronunciation of "Je fais un achat important aujourd’hui."',
        },
      ],
    },
    {
      id: 'consommation-idees',
      title: 'Construire des idées',
      learningItemIds: ['quantiteurs', 'faire-du-shopping', 'payer-cher'],
      exercises: [
        {
          id: 'cns-7',
          learningItemId: 'quantiteurs',
          type: 'multiple_choice',
          stage: 'recognition',
          prompt: 'Which sentence is correct?',
          content: { options: ['Je bois trop de sucre.', 'Je bois trop du sucre.'] },
          answer: 'Je bois trop de sucre.',
          explanation: 'After "trop / assez / pas assez," the partitive becomes "de."',
        },
        {
          id: 'cns-8',
          learningItemId: 'quantiteurs',
          type: 'fill_blank',
          stage: 'transformation',
          prompt: 'Complete the sentence',
          content: {
            sentence: 'On achète pas ______ temps pour comparer les prix.',
            options: ['assez de', 'assez du', 'assez de la', 'assez des'],
          },
          answer: 'assez de',
          explanation: 'Quantity word + "de": "pas assez de temps."',
        },
        {
          id: 'cns-9',
          learningItemId: 'faire-du-shopping',
          type: 'multiple_choice',
          stage: 'recognition',
          prompt: 'What does "Faire du shopping" mean?',
          content: { options: ['To go shopping', 'To go to the cinema', 'To go on vacation', 'To go to the bank'] },
          answer: 'To go shopping',
          explanation: '"Faire du shopping" means "to go shopping."',
        },
        {
          id: 'cns-10',
          learningItemId: 'faire-du-shopping',
          type: 'fill_blank',
          stage: 'context',
          prompt: 'Complete the sentence',
          content: {
            sentence: 'Le week-end, on ______ du shopping en ville.',
            options: ['fait', 'fais', 'ferait', 'faire'],
          },
          answer: 'fait',
          explanation: '"On fait du shopping" — present of "faire."',
        },
        {
          id: 'cns-11',
          learningItemId: 'payer-cher',
          type: 'translation',
          stage: 'recall',
          prompt: 'Translate: to pay a lot / dearly',
          content: { direction: 'en_to_fr', options: ['payer cher', 'penser cher', 'peu cher', 'payer mieux'] },
          answer: 'payer cher',
          explanation: '"To pay a lot" is "payer cher."',
        },
        {
          id: 'cns-12',
          learningItemId: 'payer-cher',
          type: 'fill_blank',
          stage: 'context',
          prompt: 'Complete the sentence',
          content: {
            sentence: 'On paie trop ______ pour un simple café.',
            options: ['cher', 'chère', 'chers', 'cheté'],
          },
          answer: 'cher',
          explanation: 'Adverb use after the verb: "payer cher."',
        },
      
        {
          id: 'cns-27',
          learningItemId: 'quantiteurs',
          type: 'fill_blank',
          stage: 'context',
          prompt: 'Complete the sentence with the correct quantifier.',
          content: {"sentence":"Il n'y a pas ______ d'argent pour acheter cette maison.","options":["assez de","assez du","assez de la","assez des"]},
          answer: 'assez de',
          explanation: 'After "pas assez", use "de".',
        },
        {
          id: 'cns-28',
          learningItemId: 'quantiteurs',
          type: 'fill_blank',
          stage: 'transformation',
          prompt: 'Transform: "Il n\'a pas assez de temps."',
          content: {"sentence":"Il ______ de temps pour finir le projet.","options":["pas assez de","pas assez du","pas assez de la","pas assez des"]},
          answer: 'pas assez de',
          explanation: 'After "pas assez", use "de".',
        },
        {
          id: 'cns-29',
          learningItemId: 'payer-cher',
          type: 'pronunciation',
          stage: 'production',
          prompt: 'Repeat after me:',
          content: {"sentence":"On paie trop cher pour des vêtements de marque."},
          answer: 'On paie trop cher pour des vêtements de marque.',
          explanation: 'Practice the expression "payer cher" with plural.',
        },
        {
          id: 'cns-30',
          learningItemId: 'quantiteurs',
          type: 'fill_blank',
          stage: 'context',
          prompt: 'Choose the correct form of the quantifier for feminine plural.',
          content: {"sentence":"Il n'y a pas ______ d'eau pour les enfants.","options":["assez de","assez du","assez de la","assez des"]},
          answer: 'assez de',
          explanation: 'After "pas assez", use "de" regardless of gender/plural.',
        },
      ],
    },
    {
      id: 'consommation-argumenter',
      title: 'Argumenter sur la consommation',
      learningItemIds: ['en-avoir-pour-son-argent', 'impulsion'],
      exercises: [
        {
          id: 'cns-13',
          learningItemId: 'en-avoir-pour-son-argent',
          type: 'multiple_choice',
          stage: 'recognition',
          prompt: 'What does "En avoir pour son argent" mean?',
          content: { options: ['To get your money\u2019s worth', 'To spend all your money', 'To have no money', 'To lend money'] },
          answer: 'To get your money\u2019s worth',
          explanation: '"En avoir pour son argent" = to get good value for money.',
        },
        {
          id: 'cns-14',
          learningItemId: 'en-avoir-pour-son-argent',
          type: 'fill_blank',
          stage: 'context',
          prompt: 'Complete the sentence',
          content: {
            sentence: 'Avec une bonne offre, on en a pour son ______.',
            options: ['argent', 'argenture', 'argentite', 'argentin'],
          },
          answer: 'argent',
          explanation: 'The fixed expression is "en avoir pour son argent."',
        },
        {
          id: 'cns-15',
          learningItemId: 'impulsion',
          type: 'multiple_choice',
          stage: 'recognition',
          prompt: 'What does "un achat impulsif" mean?',
          content: { options: ['A spur-of-the-moment purchase', 'A planned purchase', 'A fraudulent purchase', 'A collective purchase'] },
          answer: 'A spur-of-the-moment purchase',
          explanation: '"Un achat impulsif" = an impulse buy.',
        },
        {
          id: 'cns-16',
          learningItemId: 'impulsion',
          type: 'fill_blank',
          stage: 'context',
          prompt: 'Complete the sentence',
          content: {
            sentence: 'Les achats ______ sont parfois regrettés.',
            options: ['impulsifs', 'impulsion', 'impulsive', 'impulsionnels'],
          },
          answer: 'impulsifs',
          explanation: '"Les achats impulsifs" — plural agreement.',
        },
        {
          id: 'cns-17',
          learningItemId: 'en-avoir-pour-son-argent',
          type: 'pronunciation',
          stage: 'production',
          prompt: 'Say the sentence aloud.',
          content: { sentence: 'En attendant les soldes, on en a pour son argent.' },
          answer: 'En attendant les soldes, on en a pour son argent.',
          explanation: 'Gérondif "en attendant" + the fixed expression.',
        },
        {
          id: 'cns-18',
          learningItemId: 'impulsion',
          type: 'pronunciation',
          stage: 'production',
          prompt: 'Say the sentence aloud.',
          content: { sentence: 'Il faut éviter les achats impulsifs.' },
          answer: 'Il faut éviter les achats impulsifs.',
          explanation: '"Il faut éviter" + noun phrase — useful for the oral debate.',
        },
      
        {
          id: 'cns-31',
          learningItemId: 'en-avoir-pour-son-argent',
          type: 'translation',
          stage: 'recognition',
          prompt: 'Translate into French: "I want to make sure I get my money’s worth."',
          content: {"options":["Je veux m’assurer d’avoir du bon rapport qualité/prix.","Je veux être sûr d’avoir mon argent.","Je veux que mon argent soit bien dépensé.","Je veux que mon argent soit gagné.”"]},
          answer: 'Je veux m’assurer d’avoir du bon rapport qualité/prix.',
          explanation: 'The expression means to get good value for money.',
        },
        {
          id: 'cns-32',
          learningItemId: 'en-avoir-pour-son-argent',
          type: 'pronunciation',
          stage: 'transformation',
          prompt: 'Prononcez la phrase suivante :',
          content: {"sentence":"Avec cette offre, on en a vraiment pour son argent."},
          answer: 'Avec cette offre, on en a vraiment pour son argent.',
          explanation: 'Listen to the correct pronunciation.',
        },
        {
          id: 'cns-33',
          learningItemId: 'impulsion',
          type: 'multiple_choice',
          stage: 'recognition',
          prompt: 'Quel est le sens de "Un achat impulsif" ?',
          content: {"options":["A planned purchase","A spontaneous purchase","A sale event","A discount offer"]},
          answer: 'A spontaneous purchase',
          explanation: 'It refers to buying on a sudden impulse.',
        },
        {
          id: 'cns-34',
          learningItemId: 'impulsion',
          type: 'fill_blank',
          stage: 'context',
          prompt: 'Complétez : "Je n’ai pas pu résister à ce ___, j’ai acheté le produit sans réfléchir."',
          content: {"sentence":"Je n’ai pas pu résister à ce ___, j’ai acheté le produit sans réfléchir.","options":["achat impulsif","achat impulsive","achat impulsifs","achat impulsives"]},
          answer: 'achat impulsif',
          explanation: 'The expression is invariable: "achat impulsif".',
        },
        {
          id: 'cns-35',
          learningItemId: 'impulsion',
          type: 'pronunciation',
          stage: 'production',
          prompt: 'Prononcez : "Il faut éviter les achats impulsifs."',
          content: {"sentence":"Il faut éviter les achats impulsifs."},
          answer: 'Il faut éviter les achats impulsifs.',
          explanation: 'Listen to the correct pronunciation.',
        },
      ],
    },
  ],
}

export const items = {
  achat: {
    id: 'achat',
    type: 'vocabulary',
    word: 'achat',
    meaning: 'purchase',
    partOfSpeech: 'noun (m.)',
    level: 'A2',
    topic: 'La consommation',
    example: 'Je réfléchis avant de faire un achat en ligne.',
    related: ['achèter', 'article'],
  },
  produit: {
    id: 'produit',
    type: 'vocabulary',
    word: 'produit',
    meaning: 'product',
    partOfSpeech: 'noun (m.)',
    level: 'A2',
    topic: 'La consommation',
    example: 'Ce produit local est de bonne qualité.',
    related: ['bien', 'marchandise'],
  },
  prix: {
    id: 'prix',
    type: 'vocabulary',
    word: 'prix',
    meaning: 'price',
    partOfSpeech: 'noun (m.)',
    level: 'A2',
    topic: 'La consommation',
    example: 'Le prix de l\u2019essence ne cesse d\u2019augmenter.',
    related: ['coût', 'tarif'],
  },
  vente: {
    id: 'vente',
    type: 'vocabulary',
    word: 'vente',
    meaning: 'sale',
    partOfSpeech: 'noun (f.)',
    level: 'A2',
    topic: 'La consommation',
    example: 'Les soldes commencent à la fin de la vente.',
    related: ['soldes', 'commerce'],
  },

  'faire-du-shopping': {
    id: 'faire-du-shopping',
    type: 'phrase',
    phrase: 'Faire du shopping',
    meaning: 'To go shopping',
    function: 'Leisure and spending',
    level: 'A2',
    topic: 'La consommation',
    tefUsage: 'Expression orale — décrire ses loisirs',
    example: 'Le week-end, on fait du shopping en ville.',
    related: ['Faire des achats', 'Acheter'],
    conjugation: {
      je: 'fais du shopping',
      tu: 'fais du shopping',
      ilElle: 'fait du shopping',
      nous: 'faisons du shopping',
      vous: 'faites du shopping',
      ilsElles: 'font du shopping',
    },
  },
  'payer-cher': {
    id: 'payer-cher',
    type: 'phrase',
    phrase: 'Payer cher',
    meaning: 'To pay a lot / dearly',
    function: 'Price',
    level: 'B1',
    topic: 'La consommation',
    tefUsage: 'Expression orale — commenter un prix',
    example: 'On paie trop cher pour un simple café.',
    related: ['Coûter cher'],
    conjugation: {
      je: 'paie cher',
      tu: 'paies cher',
      ilElle: 'paie cher',
      nous: 'payons cher',
      vous: 'payez cher',
      ilsElles: 'paient cher',
    },
  },
  'en-avoir-pour-son-argent': {
    id: 'en-avoir-pour-son-argent',
    type: 'phrase',
    phrase: 'En avoir pour son argent',
    meaning: 'To get your money\u2019s worth',
    function: 'Value for money',
    level: 'B1',
    topic: 'La consommation',
    tefUsage: 'Expression orale — évaluer un achat',
    example: 'En attendant les soldes, on en a pour son argent.',
    related: ['En valoir la peine'],
    conjugation: {
      je: "J'en ai pour mon argent",
      tu: "Tu en as pour ton argent",
      ilElle: "Il/Elle en a pour son argent",
      nous: "Nous en avons pour notre argent",
      vous: "Vous en avez pour votre argent",
      ilsElles: "Ils/Elles en ont pour leur argent",
    },
  },
  impulsion: {
    id: 'impulsion',
    type: 'phrase',
    phrase: 'Un achat impulsif',
    meaning: 'A spur-of-the-moment purchase',
    function: 'Consumer behavior',
    level: 'B1',
    topic: 'La consommation',
    tefUsage: 'Expression orale — parler de ses habitudes de consommation',
    example: 'Il faut éviter les achats impulsifs.',
    related: ['Sur un coup de tête'],
  },

  quantiteurs: {
    id: 'quantiteurs',
    type: 'grammar',
    title: 'Les quantificateurs: trop, assez, pas assez + de',
    level: 'B1',
    explanation:
      'After "trop", "assez" or "pas assez", the partitive becomes "de": trop de sucre, assez d\u2019argent, pas assez de temps.',
    examples: ['Je bois trop de sucre.', 'On n\u2019a pas assez de temps.'],
    counterexamples: ['Je bois trop du sucre. (incorrect — "trop" is followed by de, not du/de la/des)'],
  },
}