// Hand-authored TEF theme unit (spec §3.2.1) — "La culture" (Culture). Part of the full TEF theme
// coverage in the Learn path. Exports the same { unit, items } shape as generated units
// (spec §3.2.6). All exercises are tap-only (spec §3.2.2).

export const unit = {
  id: 'culture',
  title: 'La culture',
  description: 'Talk about museums, shows, and how culture shapes us.',
  lessons: [
    {
      id: 'culture-vocabulaire',
      title: 'Vocabulaire de la culture',
      learningItemIds: ['musee', 'exposition', 'spectacle', 'patrimoine'],
      exercises: [
        {
          id: 'cul-1',
          learningItemId: 'patrimoine',
          type: 'multiple_choice',
          stage: 'recognition',
          prompt: 'What does "le patrimoine" mean?',
          content: { options: ['heritage', 'patronage', 'a pattern', 'a patrol'] },
          answer: 'heritage',
          explanation: '"Le patrimoine" is "heritage."',
        },
        {
          id: 'cul-2',
          learningItemId: 'exposition',
          type: 'multiple_choice',
          stage: 'recognition',
          prompt: 'What does "une exposition" mean?',
          content: { options: ['an exhibition', 'an exposure', 'an expression', 'an expedition'] },
          answer: 'an exhibition',
          explanation: '"Une exposition" is an "exhibition."',
        },
        {
          id: 'cul-3',
          learningItemId: 'musee',
          type: 'translation',
          stage: 'recall',
          prompt: 'Translate: museum',
          content: { direction: 'en_to_fr', options: ['musée', 'musique', 'mousse', 'mur'] },
          answer: 'musée',
          explanation: '"Museum" translates to "musée."',
        },
        {
          id: 'cul-4',
          learningItemId: 'spectacle',
          type: 'translation',
          stage: 'recall',
          prompt: 'Translate: show',
          content: { direction: 'en_to_fr', options: ['spectacle', 'spectateur', 'spectre', 'spécialité'] },
          answer: 'spectacle',
          explanation: '"Show" translates to "spectacle."',
        },
        {
          id: 'cul-5',
          learningItemId: 'musee',
          type: 'fill_blank',
          stage: 'context',
          prompt: 'Complete the sentence',
          content: {
            sentence: 'Le musée est gratuit le premier dimanche du ______.',
            options: ['mois', 'matin', 'midi', 'mardi'],
          },
          answer: 'mois',
          explanation: '"Le premier dimanche du mois" — the first Sunday of the month.',
        },
        {
          id: 'cul-6',
          learningItemId: 'exposition',
          type: 'fill_blank',
          stage: 'context',
          prompt: 'Complete the sentence',
          content: {
            sentence: "Il y a une ______ sur l'art moderne au musée.",
            options: ['exposition', 'expédition', 'exception', 'exploration'],
          },
          answer: 'exposition',
          explanation: '"Une exposition sur" — an exhibition about a subject.',
        },
      
        {
          id: 'cul-19',
          learningItemId: 'exposition',
          type: 'translation',
          stage: 'recall',
          prompt: 'Translate: "Une exposition sur l\'art moderne."',
          content: {"options":["An exhibition on modern art.","A show about modern art.","A museum of modern art.","A collection of modern art."],"sentence":"Une exposition sur l'art moderne."},
          answer: 'An exhibition on modern art.',
          explanation: '"Une exposition" translates to "An exhibition."',
        },
        {
          id: 'cul-20',
          learningItemId: 'exposition',
          type: 'pronunciation',
          stage: 'recall',
          prompt: 'Pronounce the following phrase:',
          content: {"sentence":"Il y a une exposition sur l'art moderne au musée."},
          answer: 'Il y a une exposition sur l\'art moderne au musée.',
          explanation: 'Pronunciation of the phrase.',
        },
        {
          id: 'cul-21',
          learningItemId: 'spectacle',
          type: 'multiple_choice',
          stage: 'context',
          prompt: 'Which sentence uses "spectacle" correctly?',
          content: {"options":["Le spectacle était magnifique.","Le spectacle est un musée.","Le spectacle est une exposition.","Le spectacle est un patrimoine."],"sentence":"Le spectacle était magnifique."},
          answer: 'Le spectacle était magnifique.',
          explanation: '"Spectacle" means "show" and fits the sentence.',
        },
        {
          id: 'cul-22',
          learningItemId: 'spectacle',
          type: 'fill_blank',
          stage: 'completion',
          prompt: 'Le ___ était magnifique.',
          content: {"sentence":"Le ___ était magnifique.","options":["musée","exposition","spectacle","patrimoine"]},
          answer: 'spectacle',
          explanation: 'The blank is "spectacle."',
        },
        {
          id: 'cul-23',
          learningItemId: 'patrimoine',
          type: 'multiple_choice',
          stage: 'recognition',
          prompt: 'What does "le patrimoine" refer to?',
          content: {"options":["heritage","patronage","pattern","patrol"]},
          answer: 'heritage',
          explanation: '"Le patrimoine" means "heritage."',
        },
        {
          id: 'cul-24',
          learningItemId: 'patrimoine',
          type: 'translation',
          stage: 'recall',
          prompt: 'Translate: "Le patrimoine français attire des millions de touristes."',
          content: {"options":["French heritage attracts millions of tourists.","French patronage attracts millions of tourists.","French pattern attracts millions of tourists.","French patrol attracts millions of tourists."],"sentence":"Le patrimoine français attire des millions de touristes."},
          answer: 'French heritage attracts millions of tourists.',
          explanation: 'Correct translation of the sentence.',
        },
      ],
    },
    {
      id: 'culture-idees',
      title: 'Construire des idées',
      learningItemIds: ['gerondif', 'etre-passionne-de', 'tradition'],
      exercises: [
        {
          id: 'cul-7',
          learningItemId: 'gerondif',
          type: 'multiple_choice',
          stage: 'recognition',
          prompt: 'Which sentence uses the gérondif correctly?',
          content: {
            options: [
              "J'apprends le français en écoutant la radio.",
              "J'apprends le français en écouter la radio.",
            ],
          },
          answer: "J'apprends le français en écoutant la radio.",
          explanation: 'The gérondif is "en" + the -ant participle: "en écoutant."',
        },
        {
          id: 'cul-8',
          learningItemId: 'gerondif',
          type: 'fill_blank',
          stage: 'context',
          prompt: 'Complete the sentence',
          content: {
            sentence: "J'apprends le français en écoutant la ______.",
            options: ['radio', 'radis', 'source', 'chose'],
          },
          answer: 'radio',
          explanation: '"En écoutant la radio" — while listening to the radio.',
        },
        {
          id: 'cul-9',
          learningItemId: 'etre-passionne-de',
          type: 'multiple_choice',
          stage: 'recognition',
          prompt: 'What does "Être passionné de" mean?',
          content: { options: ['To be passionate about', 'To be patient with', 'To be paid for', 'To be part of'] },
          answer: 'To be passionate about',
          explanation: '"Être passionné de" = "to be passionate about."',
        },
        {
          id: 'cul-10',
          learningItemId: 'etre-passionne-de',
          type: 'fill_blank',
          stage: 'context',
          prompt: 'Complete the sentence',
          content: {
            sentence: 'Je suis ______ de jazz.',
            options: ['passionné', 'passionnée', 'passionner', 'passionnant'],
          },
          answer: 'passionné',
          explanation: '"Je suis passionné de" — masculine singular to agree with "je" (male speaker).',
        },
        {
          id: 'cul-11',
          learningItemId: 'tradition',
          type: 'translation',
          stage: 'recall',
          prompt: 'Translate: tradition',
          content: { direction: 'en_to_fr', options: ['tradition', 'traduction', 'transaction', 'traction'] },
          answer: 'tradition',
          explanation: '"Tradition" translates to "tradition."',
        },
        {
          id: 'cul-12',
          learningItemId: 'tradition',
          type: 'fill_blank',
          stage: 'context',
          prompt: 'Complete the sentence',
          content: {
            sentence: 'Une ______ peut évoluer avec le temps.',
            options: ['tradition', 'traduit', 'transmission', 'tribunal'],
          },
          answer: 'tradition',
          explanation: '"Une tradition" — a custom that can evolve over time.',
        },
      
        {
          id: 'cul-31',
          learningItemId: 'gerondif',
          type: 'multiple_choice',
          stage: 'recognition',
          prompt: 'Choose the correct sentence using the gérondif with "en" + -ant.',
          content: {"options":["Je lis un livre en écoutant la radio.","Je lis un livre en écouter la radio."]},
          answer: 'Je lis un livre en écoutant la radio.',
          explanation: 'The gérondif is "en" + the -ant participle.',
        },
        {
          id: 'cul-32',
          learningItemId: 'gerondif',
          type: 'fill_blank',
          stage: 'context',
          prompt: 'Complete the sentence with the correct form of the gérondif.',
          content: {"sentence":"Elle voyage en visitant les musées.","options":["en visitant","en visiter"]},
          answer: 'en visitant',
          explanation: 'The gérondif uses the -ant participle.',
        },
        {
          id: 'cul-33',
          learningItemId: 'etre-passionne-de',
          type: 'translation',
          stage: 'recall',
          prompt: 'Translate into French: "I am passionate about literature."',
          content: {"options":["Je suis passionné de littérature.","Je suis passionné de les littérature.","Je suis passionné de littéraire.","Je suis passionné de literatures."]},
          answer: 'Je suis passionné de littérature.',
          explanation: 'Use "être passionné de" + noun.',
        },
        {
          id: 'cul-34',
          learningItemId: 'tradition',
          type: 'translation',
          stage: 'recall',
          prompt: 'Translate into French: "Traditions evolve over time."',
          content: {"options":["Les traditions évoluent au fil du temps.","Les traditions évoluent dans le temps.","Les traditions évoluent à travers le temps.","Les traditions évoluent en temps."]},
          answer: 'Les traditions évoluent au fil du temps.',
          explanation: 'Use "au fil du temps" for "over time".',
        },
        {
          id: 'cul-35',
          learningItemId: 'gerondif',
          type: 'pronunciation',
          stage: 'production',
          prompt: 'Pronounce the following sentence correctly.',
          content: {"sentence":"Je suis passionné de théâtre, et j'apprends le français en écoutant la radio."},
          answer: 'Je suis passionné de théâtre, et j\'apprends le français en écoutant la radio.',
          explanation: 'Focus on the rhythm of "en écoutant" and "passionné de".',
        },
      ],
    },
    {
      id: 'culture-argumenter',
      title: 'Argumenter sur la culture',
      learningItemIds: ['donner-envie-de', 'prendre-gout-a'],
      exercises: [
        {
          id: 'cul-13',
          learningItemId: 'donner-envie-de',
          type: 'multiple_choice',
          stage: 'recognition',
          prompt: 'What does "Donner envie de" mean?',
          content: { options: ['To make someone want to', 'To give permission to', 'To give up on', 'To remind someone of'] },
          answer: 'To make someone want to',
          explanation: '"Donner envie de" = "to make someone want to."',
        },
        {
          id: 'cul-14',
          learningItemId: 'donner-envie-de',
          type: 'fill_blank',
          stage: 'context',
          prompt: 'Complete the sentence',
          content: {
            sentence: 'Ce film donne ______ de voyager.',
            options: ['envie', 'effet', 'avis', 'peur'],
          },
          answer: 'envie',
          explanation: '"Donner envie de" + infinitive.',
        },
        {
          id: 'cul-15',
          learningItemId: 'prendre-gout-a',
          type: 'multiple_choice',
          stage: 'recognition',
          prompt: 'What does "Prendre goût à" mean?',
          content: { options: ['To develop a taste for', 'To take a sip of', 'To grow bored of', 'To taste something sweet'] },
          answer: 'To develop a taste for',
          explanation: '"Prendre goût à" = "to develop a taste for."',
        },
        {
          id: 'cul-16',
          learningItemId: 'prendre-gout-a',
          type: 'fill_blank',
          stage: 'context',
          prompt: 'Complete the sentence',
          content: {
            sentence: "Elle a pris ______ au cinéma d'auteur.",
            options: ['goût', 'goûter', 'goûte', 'goûté'],
          },
          answer: 'goût',
          explanation: '"Prendre goût à" — the noun "le goût."',
        },
        {
          id: 'cul-17',
          learningItemId: 'gerondif',
          type: 'pronunciation',
          stage: 'production',
          prompt: 'Say the sentence aloud.',
          content: { sentence: "J'apprends le français en écoutant la radio." },
          answer: "J'apprends le français en écoutant la radio.",
          explanation: 'The gérondif "en écoutant" expresses the "how" of learning.',
        },
        {
          id: 'cul-18',
          learningItemId: 'musee',
          type: 'pronunciation',
          stage: 'production',
          prompt: 'Say the sentence aloud.',
          content: { sentence: 'Le musée est gratuit le premier dimanche du mois.' },
          answer: 'Le musée est gratuit le premier dimanche du mois.',
          explanation: 'Word order: subject + "est" + adjective + time detail.',
        },
      
        {
          id: 'cul-25',
          learningItemId: 'donner-envie-de',
          type: 'fill_blank',
          stage: 'recall',
          prompt: 'Choose the correct form of the verb to complete the sentence: "Nous ___ de découvrir de nouveaux artistes."',
          content: {"sentence":"Nous ___ de découvrir de nouveaux artistes.","options":["donons envie","donne envie","donner","donnez envie"]},
          answer: 'donons envie',
          explanation: 'First person plural of "donner" in present.',
        },
        {
          id: 'cul-26',
          learningItemId: 'prendre-gout-a',
          type: 'multiple_choice',
          stage: 'recognition',
          prompt: 'What does "prendre goût à" mean?',
          content: {"options":["To develop a taste for","To lose interest in","To force someone to","To remember something"]},
          answer: 'To develop a taste for',
          explanation: 'It means to develop a taste for something.',
        },
        {
          id: 'cul-27',
          learningItemId: 'prendre-gout-a',
          type: 'translation',
          stage: 'recall',
          prompt: 'Translate: "J\'ai pris goût aux vins français."',
          content: {"options":["I have developed a taste for French wines.","I have lost interest in French wines.","I have forced French wines on myself.","I have remembered French wines."]},
          answer: 'I have developed a taste for French wines.',
          explanation: 'Literal translation of "prendre goût à".',
        },
        {
          id: 'cul-28',
          learningItemId: 'donner-envie-de',
          type: 'pronunciation',
          stage: 'transformation',
          prompt: 'Pronounce the following sentence correctly:',
          content: {"sentence":"Ce spectacle donne envie de danser."},
          answer: 'Ce spectacle donne envie de danser.',
          explanation: 'Focus on the liaison between "donne" and "envie".',
        },
        {
          id: 'cul-29',
          learningItemId: 'prendre-gout-a',
          type: 'fill_blank',
          stage: 'context',
          prompt: 'Complete the sentence: "Il a ___ de la musique classique après avoir assisté à un concert."',
          content: {"sentence":"Il a ___ de la musique classique après avoir assisté à un concert.","options":["pris goût à","pris goût en","pris goût sur","pris goût pour"]},
          answer: 'pris goût à',
          explanation: 'Correct preposition with "prendre goût à".',
        },
        {
          id: 'cul-30',
          learningItemId: 'prendre-gout-a',
          type: 'translation',
          stage: 'recall',
          prompt: 'Translate: "Nous avons pris goût aux plats épicés."',
          content: {"options":["We have developed a taste for spicy dishes.","We have lost interest in spicy dishes.","We have forced spicy dishes on us.","We have remembered spicy dishes."]},
          answer: 'We have developed a taste for spicy dishes.',
          explanation: 'Literal translation.',
        },
      ],
    },
  ],
}

export const items = {
  patrimoine: {
    id: 'patrimoine',
    type: 'vocabulary',
    word: 'patrimoine',
    meaning: 'heritage',
    partOfSpeech: 'noun (m.)',
    level: 'B1',
    topic: 'La culture',
    example: 'Le patrimoine français attire des millions de touristes.',
    related: ['héritage'],
  },
  exposition: {
    id: 'exposition',
    type: 'vocabulary',
    word: 'exposition',
    meaning: 'exhibition',
    partOfSpeech: 'noun (f.)',
    level: 'B1',
    topic: 'La culture',
    example: "Il y a une exposition sur l'art moderne au musée.",
    related: ['musée'],
  },
  spectacle: {
    id: 'spectacle',
    type: 'vocabulary',
    word: 'spectacle',
    meaning: 'show',
    partOfSpeech: 'noun (m.)',
    level: 'B1',
    topic: 'La culture',
    example: 'Le spectacle était magnifique.',
    related: ['théâtre', 'pièce'],
  },
  tradition: {
    id: 'tradition',
    type: 'vocabulary',
    word: 'tradition',
    meaning: 'tradition',
    partOfSpeech: 'noun (f.)',
    level: 'B1',
    topic: 'La culture',
    example: 'Une tradition peut évoluer avec le temps.',
    related: ['coutume'],
  },
  musee: {
    id: 'musee',
    type: 'vocabulary',
    word: 'musée',
    meaning: 'museum',
    partOfSpeech: 'noun (m.)',
    level: 'B1',
    topic: 'La culture',
    example: 'Le musée est gratuit le premier dimanche du mois.',
    related: ['galerie'],
  },

  'etre-passionne-de': {
    id: 'etre-passionne-de',
    type: 'phrase',
    phrase: 'Être passionné de',
    meaning: 'To be passionate about',
    function: 'Describing tastes',
    level: 'B1',
    topic: 'La culture',
    tefUsage: 'Expression orale — parler de ses goûts',
    example: 'Je suis passionné de jazz.',
    related: ['Adorer'],
    conjugation: {
      je: 'suis passionné(e) de',
      tu: 'es passionné(e) de',
      ilElle: 'est passionné(e) de',
      nous: 'sommes passionné(e)s de',
      vous: 'êtes passionné(e)(s) de',
      ilsElles: 'sont passionné(e)s de',
    },
  },
  'donner-envie-de': {
    id: 'donner-envie-de',
    type: 'phrase',
    phrase: 'Donner envie de',
    meaning: 'To make someone want to',
    function: 'Influence',
    level: 'B1',
    topic: 'La culture',
    tefUsage: 'Expression orale — donner son impression',
    example: 'Ce film donne envie de voyager.',
    related: ['Inciter à'],
    conjugation: {
      je: 'donne envie de',
      tu: 'donnes envie de',
      ilElle: 'donne envie de',
      nous: 'donnons envie de',
      vous: 'donnez envie de',
      ilsElles: 'donnent envie de',
    },
  },
  'prendre-gout-a': {
    id: 'prendre-gout-a',
    type: 'phrase',
    phrase: 'Prendre goût à',
    meaning: 'To develop a taste for',
    function: 'Change in taste',
    level: 'B1',
    topic: 'La culture',
    tefUsage: 'Expression orale — décrire une évolution',
    example: "Elle a pris goût au cinéma d'auteur.",
    related: ["S'initier à"],
    conjugation: {
      je: 'prends goût à',
      tu: 'prends goût à',
      ilElle: 'prend goût à',
      nous: 'prenons goût à',
      vous: 'prenez goût à',
      ilsElles: 'prennent goût à',
    },
  },

  gerondif: {
    id: 'gerondif',
    type: 'grammar',
    title: 'The gérondif (en + present participle)',
    level: 'B1',
    explanation:
      'Use "en" + -ant to say "while/by doing": en écoutant, en visitant. Great for describing cultural activities.',
    examples: ['J\u2019apprends le français en écoutant la radio.', 'En visitant ce musée, tu comprendras son histoire.'],
    counterexamples: ['En écouter la radio, j\u2019apprends. (incorrect — the gérondif is formed on the -ant participle: "en écoutant")'],
  },
}