// Hand-authored TEF theme unit (spec §3.2.1) — "La culture" (Culture). Part of the full TEF theme
// coverage in the Learn path. Exports the same { unit, items } shape as generated units
// (spec §3.2.6). All exercises are tap-only (spec §3.2.2).

export const unit = {
  id: 'culture',
  title: 'La culture',
  description: 'Talk about museums, shows, and how culture shapes us.',
  lessons: [
    {
      id: 'culture-vocabulaire',
      title: 'Vocabulaire de la culture',
      learningItemIds: ['musee', 'exposition', 'spectacle', 'patrimoine'],
      exercises: [
        {
          id: 'cul-1',
          learningItemId: 'patrimoine',
          type: 'multiple_choice',
          stage: 'recognition',
          prompt: 'What does "le patrimoine" mean?',
          content: { options: ['heritage', 'patronage', 'a pattern', 'a patrol'] },
          answer: 'heritage',
          explanation: '"Le patrimoine" is "heritage."',
        },
        {
          id: 'cul-2',
          learningItemId: 'exposition',
          type: 'multiple_choice',
          stage: 'recognition',
          prompt: 'What does "une exposition" mean?',
          content: { options: ['an exhibition', 'an exposure', 'an expression', 'an expedition'] },
          answer: 'an exhibition',
          explanation: '"Une exposition" is an "exhibition."',
        },
        {
          id: 'cul-3',
          learningItemId: 'musee',
          type: 'translation',
          stage: 'recall',
          prompt: 'Translate: museum',
          content: { direction: 'en_to_fr', options: ['musée', 'musique', 'mousse', 'mur'] },
          answer: 'musée',
          explanation: '"Museum" translates to "musée."',
        },
        {
          id: 'cul-4',
          learningItemId: 'spectacle',
          type: 'translation',
          stage: 'recall',
          prompt: 'Translate: show',
          content: { direction: 'en_to_fr', options: ['spectacle', 'spectateur', 'spectre', 'spécialité'] },
          answer: 'spectacle',
          explanation: '"Show" translates to "spectacle."',
        },
        {
          id: 'cul-5',
          learningItemId: 'musee',
          type: 'fill_blank',
          stage: 'context',
          prompt: 'Complete the sentence',
          content: {
            sentence: 'Le musée est gratuit le premier dimanche du ______.',
            options: ['mois', 'matin', 'midi', 'mardi'],
          },
          answer: 'mois',
          explanation: '"Le premier dimanche du mois" — the first Sunday of the month.',
        },
        {
          id: 'cul-6',
          learningItemId: 'exposition',
          type: 'fill_blank',
          stage: 'context',
          prompt: 'Complete the sentence',
          content: {
            sentence: "Il y a une ______ sur l'art moderne au musée.",
            options: ['exposition', 'expédition', 'exception', 'exploration'],
          },
          answer: 'exposition',
          explanation: '"Une exposition sur" — an exhibition about a subject.',
        },
      ],
    },
    {
      id: 'culture-idees',
      title: 'Construire des idées',
      learningItemIds: ['gerondif', 'etre-passionne-de', 'tradition'],
      exercises: [
        {
          id: 'cul-7',
          learningItemId: 'gerondif',
          type: 'multiple_choice',
          stage: 'recognition',
          prompt: 'Which sentence uses the gérondif correctly?',
          content: {
            options: [
              "J'apprends le français en écoutant la radio.",
              "J'apprends le français en écouter la radio.",
            ],
          },
          answer: "J'apprends le français en écoutant la radio.",
          explanation: 'The gérondif is "en" + the -ant participle: "en écoutant."',
        },
        {
          id: 'cul-8',
          learningItemId: 'gerondif',
          type: 'fill_blank',
          stage: 'context',
          prompt: 'Complete the sentence',
          content: {
            sentence: "J'apprends le français en écoutant la ______.",
            options: ['radio', 'radis', 'source', 'chose'],
          },
          answer: 'radio',
          explanation: '"En écoutant la radio" — while listening to the radio.',
        },
        {
          id: 'cul-9',
          learningItemId: 'etre-passionne-de',
          type: 'multiple_choice',
          stage: 'recognition',
          prompt: 'What does "Être passionné de" mean?',
          content: { options: ['To be passionate about', 'To be patient with', 'To be paid for', 'To be part of'] },
          answer: 'To be passionate about',
          explanation: '"Être passionné de" = "to be passionate about."',
        },
        {
          id: 'cul-10',
          learningItemId: 'etre-passionne-de',
          type: 'fill_blank',
          stage: 'context',
          prompt: 'Complete the sentence',
          content: {
            sentence: 'Je suis ______ de jazz.',
            options: ['passionné', 'passionnée', 'passionner', 'passionnant'],
          },
          answer: 'passionné',
          explanation: '"Je suis passionné de" — masculine singular to agree with "je" (male speaker).',
        },
        {
          id: 'cul-11',
          learningItemId: 'tradition',
          type: 'translation',
          stage: 'recall',
          prompt: 'Translate: tradition',
          content: { direction: 'en_to_fr', options: ['tradition', 'traduction', 'transaction', 'traction'] },
          answer: 'tradition',
          explanation: '"Tradition" translates to "tradition."',
        },
        {
          id: 'cul-12',
          learningItemId: 'tradition',
          type: 'fill_blank',
          stage: 'context',
          prompt: 'Complete the sentence',
          content: {
            sentence: 'Une ______ peut évoluer avec le temps.',
            options: ['tradition', 'traduit', 'transmission', 'tribunal'],
          },
          answer: 'tradition',
          explanation: '"Une tradition" — a custom that can evolve over time.',
        },
      ],
    },
    {
      id: 'culture-argumenter',
      title: 'Argumenter sur la culture',
      learningItemIds: ['donner-envie-de', 'prendre-gout-a'],
      exercises: [
        {
          id: 'cul-13',
          learningItemId: 'donner-envie-de',
          type: 'multiple_choice',
          stage: 'recognition',
          prompt: 'What does "Donner envie de" mean?',
          content: { options: ['To make someone want to', 'To give permission to', 'To give up on', 'To remind someone of'] },
          answer: 'To make someone want to',
          explanation: '"Donner envie de" = "to make someone want to."',
        },
        {
          id: 'cul-14',
          learningItemId: 'donner-envie-de',
          type: 'fill_blank',
          stage: 'context',
          prompt: 'Complete the sentence',
          content: {
            sentence: 'Ce film donne ______ de voyager.',
            options: ['envie', 'effet', 'avis', 'peur'],
          },
          answer: 'envie',
          explanation: '"Donner envie de" + infinitive.',
        },
        {
          id: 'cul-15',
          learningItemId: 'prendre-gout-a',
          type: 'multiple_choice',
          stage: 'recognition',
          prompt: 'What does "Prendre goût à" mean?',
          content: { options: ['To develop a taste for', 'To take a sip of', 'To grow bored of', 'To taste something sweet'] },
          answer: 'To develop a taste for',
          explanation: '"Prendre goût à" = "to develop a taste for."',
        },
        {
          id: 'cul-16',
          learningItemId: 'prendre-gout-a',
          type: 'fill_blank',
          stage: 'context',
          prompt: 'Complete the sentence',
          content: {
            sentence: "Elle a pris ______ au cinéma d'auteur.",
            options: ['goût', 'goûter', 'goûte', 'goûté'],
          },
          answer: 'goût',
          explanation: '"Prendre goût à" — the noun "le goût."',
        },
        {
          id: 'cul-17',
          learningItemId: 'gerondif',
          type: 'production',
          stage: 'production',
          prompt: 'Build the sentence: "J\u2019apprends le français en écoutant la radio."',
          content: {
            tiles: ["J'apprends", 'le', 'français', 'en', 'écoutant', 'la', 'radio.', 'écouter', 'et'],
          },
          answer: "J'apprends le français en écoutant la radio.",
          explanation: 'The gérondif "en écoutant" expresses the "how" of learning.',
        },
        {
          id: 'cul-18',
          learningItemId: 'musee',
          type: 'production',
          stage: 'production',
          prompt: 'Build the sentence: "Le musée est gratuit le premier dimanche du mois."',
          content: {
            tiles: ['Le', 'musée', 'est', 'gratuit', 'le', 'premier', 'dimanche', 'du', 'mois.', 'es', 'son'],
          },
          answer: 'Le musée est gratuit le premier dimanche du mois.',
          explanation: 'Word order: subject + "est" + adjective + time detail.',
        },
      ],
    },
  ],
}

export const items = {
  patrimoine: {
    id: 'patrimoine',
    type: 'vocabulary',
    word: 'patrimoine',
    meaning: 'heritage',
    partOfSpeech: 'noun (m.)',
    level: 'B1',
    topic: 'La culture',
    example: 'Le patrimoine français attire des millions de touristes.',
    related: ['héritage'],
  },
  exposition: {
    id: 'exposition',
    type: 'vocabulary',
    word: 'exposition',
    meaning: 'exhibition',
    partOfSpeech: 'noun (f.)',
    level: 'B1',
    topic: 'La culture',
    example: "Il y a une exposition sur l'art moderne au musée.",
    related: ['musée'],
  },
  spectacle: {
    id: 'spectacle',
    type: 'vocabulary',
    word: 'spectacle',
    meaning: 'show',
    partOfSpeech: 'noun (m.)',
    level: 'B1',
    topic: 'La culture',
    example: 'Le spectacle était magnifique.',
    related: ['théâtre', 'pièce'],
  },
  tradition: {
    id: 'tradition',
    type: 'vocabulary',
    word: 'tradition',
    meaning: 'tradition',
    partOfSpeech: 'noun (f.)',
    level: 'B1',
    topic: 'La culture',
    example: 'Une tradition peut évoluer avec le temps.',
    related: ['coutume'],
  },
  musee: {
    id: 'musee',
    type: 'vocabulary',
    word: 'musée',
    meaning: 'museum',
    partOfSpeech: 'noun (m.)',
    level: 'B1',
    topic: 'La culture',
    example: 'Le musée est gratuit le premier dimanche du mois.',
    related: ['galerie'],
  },

  'etre-passionne-de': {
    id: 'etre-passionne-de',
    type: 'phrase',
    phrase: 'Être passionné de',
    meaning: 'To be passionate about',
    function: 'Describing tastes',
    level: 'B1',
    topic: 'La culture',
    tefUsage: 'Expression orale — parler de ses goûts',
    example: 'Je suis passionné de jazz.',
    related: ['Adorer'],
  },
  'donner-envie-de': {
    id: 'donner-envie-de',
    type: 'phrase',
    phrase: 'Donner envie de',
    meaning: 'To make someone want to',
    function: 'Influence',
    level: 'B1',
    topic: 'La culture',
    tefUsage: 'Expression orale — donner son impression',
    example: 'Ce film donne envie de voyager.',
    related: ['Inciter à'],
  },
  'prendre-gout-a': {
    id: 'prendre-gout-a',
    type: 'phrase',
    phrase: 'Prendre goût à',
    meaning: 'To develop a taste for',
    function: 'Change in taste',
    level: 'B1',
    topic: 'La culture',
    tefUsage: 'Expression orale — décrire une évolution',
    example: "Elle a pris goût au cinéma d'auteur.",
    related: ["S'initier à"],
  },

  gerondif: {
    id: 'gerondif',
    type: 'grammar',
    title: 'The gérondif (en + present participle)',
    level: 'B1',
    explanation:
      'Use "en" + -ant to say "while/by doing": en écoutant, en visitant. Great for describing cultural activities.',
    examples: ['J\u2019apprends le français en écoutant la radio.', 'En visitant ce musée, tu comprendras son histoire.'],
    counterexamples: ['En écouter la radio, j\u2019apprends. (incorrect — the gérondif is formed on the -ant participle: "en écoutant")'],
  },
}