// Hand-authored TEF theme unit (spec §3.2.1) — "L'économie" (Economy). Part of the full TEF theme
// coverage in the Learn path. Exports the same { unit, items } shape as generated units
// (spec §3.2.6). All exercises are tap-only (spec §3.2.2).

export const unit = {
  id: 'economie',
  title: 'L’économie',
  description: 'Handle money, prices, and economic debates in simple French.',
  lessons: [
    {
      id: 'economie-vocabulaire',
      title: 'Vocabulaire de l’économie',
      learningItemIds: ['entreprise', 'budget', 'depense', 'marche'],
      exercises: [
        {
          id: 'eco-1',
          learningItemId: 'entreprise',
          type: 'multiple_choice',
          stage: 'recognition',
          prompt: 'What does "une entreprise" mean?',
          content: { options: ['a company', 'an attempt', 'a surprise', 'an entrance'] },
          answer: 'a company',
          explanation: '"Une entreprise" is a "company."',
        },
        {
          id: 'eco-2',
          learningItemId: 'budget',
          type: 'multiple_choice',
          stage: 'recognition',
          prompt: 'What does "un budget" mean?',
          content: { options: ['a budget', 'a wallet', 'a subsidy', 'a brand'] },
          answer: 'a budget',
          explanation: '"Un budget" is a "budget."',
        },
        {
          id: 'eco-3',
          learningItemId: 'depense',
          type: 'translation',
          stage: 'recall',
          prompt: 'Translate: expense',
          content: { direction: 'en_to_fr', options: ['dépense', 'dépendance', 'départ', 'député'] },
          answer: 'dépense',
          explanation: '"Expense" translates to "la dépense."',
        },
        {
          id: 'eco-4',
          learningItemId: 'marche',
          type: 'translation',
          stage: 'recall',
          prompt: 'Translate: market',
          content: { direction: 'en_to_fr', options: ['marché', 'marcher', 'matin', 'marque'] },
          answer: 'marché',
          explanation: '"Market" translates to "le marché."',
        },
        {
          id: 'eco-5',
          learningItemId: 'entreprise',
          type: 'fill_blank',
          stage: 'context',
          prompt: 'Complete the sentence',
          content: {
            sentence: "L'______ embauche de nouveaux employés.",
            options: ['entreprise', 'entraîne', 'enseigne', 'entretien'],
          },
          answer: 'entreprise',
          explanation: '"L\u2019entreprise embauche" — the company is hiring.',
        },
        {
          id: 'eco-6',
          learningItemId: 'budget',
          type: 'fill_blank',
          stage: 'context',
          prompt: 'Complete the sentence',
          content: {
            sentence: 'Il faut établir un ______ mensuel.',
            options: ['budget', 'bulletin', 'bureau', 'buffet'],
          },
          answer: 'budget',
          explanation: '"Établir un budget" — to draw up a budget.',
        },
      ],
    },
    {
      id: 'economie-idees',
      title: 'Construire des idées',
      learningItemIds: ['partitif', 'couter-cher', 'credit'],
      exercises: [
        {
          id: 'eco-7',
          learningItemId: 'partitif',
          type: 'multiple_choice',
          stage: 'recognition',
          prompt: 'Which sentence is correct?',
          content: { options: ["Il n'achète pas de luxe.", "Il n'achète pas des luxe."] },
          answer: "Il n'achète pas de luxe.",
          explanation: 'After a negative, the partitive becomes "de."',
        },
        {
          id: 'eco-8',
          learningItemId: 'partitif',
          type: 'fill_blank',
          stage: 'transformation',
          prompt: 'Complete the sentence',
          content: {
            sentence: "Il n'y a pas ______ concurrence sur ce marché.",
            options: ['de', 'des', 'du', 'de la'],
          },
          answer: 'de',
          explanation: 'After "pas," the partitive "de la" becomes "de."',
        },
        {
          id: 'eco-9',
          learningItemId: 'couter-cher',
          type: 'multiple_choice',
          stage: 'recognition',
          prompt: 'What does "Coûter cher" mean?',
          content: { options: ['To cost a lot', 'To cost little', 'To be free', 'To be worth it'] },
          answer: 'To cost a lot',
          explanation: '"Coûter cher" means "to cost a lot."',
        },
        {
          id: 'eco-10',
          learningItemId: 'couter-cher',
          type: 'fill_blank',
          stage: 'context',
          prompt: 'Complete the sentence',
          content: {
            sentence: 'Ce logement coûte très ______.',
            options: ['cher', 'chère', 'chercher', 'chant'],
          },
          answer: 'cher',
          explanation: '"Le logement" is masculine, so the adverb use is "cher."',
        },
        {
          id: 'eco-11',
          learningItemId: 'credit',
          type: 'translation',
          stage: 'recall',
          prompt: 'Translate: loan / credit',
          content: { direction: 'en_to_fr', options: ['crédit', 'crédibilité', 'crise', 'cédille'] },
          answer: 'crédit',
          explanation: '"Loan / credit" translates to "le crédit."',
        },
        {
          id: 'eco-12',
          learningItemId: 'credit',
          type: 'fill_blank',
          stage: 'context',
          prompt: 'Complete the sentence',
          content: {
            sentence: "Elle a contracté un ______ pour acheter sa voiture.",
            options: ['crédit', 'choix', 'creux', 'cours'],
          },
          answer: 'crédit',
          explanation: '"Contracter un crédit" — to take out a loan.',
        },
      ],
    },
    {
      id: 'economie-argumenter',
      title: 'Argumenter sur l’économie',
      learningItemIds: ['faire-des-economies', 'ca-ne-vaut-pas-la-peine'],
      exercises: [
        {
          id: 'eco-13',
          learningItemId: 'faire-des-economies',
          type: 'multiple_choice',
          stage: 'recognition',
          prompt: 'What does "Faire des économies" mean?',
          content: { options: ['To save money', 'To spend money', 'To waste money', 'To count money'] },
          answer: 'To save money',
          explanation: '"Faire des économies" means "to save money."',
        },
        {
          id: 'eco-14',
          learningItemId: 'faire-des-economies',
          type: 'fill_blank',
          stage: 'context',
          prompt: 'Complete the sentence',
          content: {
            sentence: 'On fait des ______ en cuisinant à la maison.',
            options: ['économies', 'économistes', 'échecs', 'accidents'],
          },
          answer: 'économies',
          explanation: '"Faire des économies" — the plural noun "économies."',
        },
        {
          id: 'eco-15',
          learningItemId: 'ca-ne-vaut-pas-la-peine',
          type: 'multiple_choice',
          stage: 'recognition',
          prompt: 'What does "Ça ne vaut pas la peine" mean?',
          content: { options: ["It's not worth it", "It's priceless", "It's a bargain", "It's unavoidable"] },
          answer: "It's not worth it",
          explanation: '"Ça ne vaut pas la peine" = "it\u2019s not worth it."',
        },
        {
          id: 'eco-16',
          learningItemId: 'ca-ne-vaut-pas-la-peine',
          type: 'fill_blank',
          stage: 'context',
          prompt: 'Complete the sentence',
          content: {
            sentence: "Ça ne vaut pas la ______ d'acheter neuf.",
            options: ['peine', 'peigne', 'peinture', 'panne'],
          },
          answer: 'peine',
          explanation: 'The fixed expression is "ça ne vaut pas la peine d\u2019" + infinitive.',
        },
        {
          id: 'eco-17',
          learningItemId: 'faire-des-economies',
          type: 'production',
          stage: 'production',
          prompt: 'Build the sentence: "On fait des économies en cuisinant à la maison."',
          content: {
            tiles: ['On', 'fait', 'des', 'économies', 'en', 'cuisinant', 'à', 'la', 'maison.', 'économique', 'maison'],
          },
          answer: 'On fait des économies en cuisinant à la maison.',
          explanation: '"Faire des économies" + how, with the gérondif "en cuisinant."',
        },
        {
          id: 'eco-18',
          learningItemId: 'ca-ne-vaut-pas-la-peine',
          type: 'production',
          stage: 'production',
          prompt: 'Build the sentence: "Ça ne vaut pas la peine d\u2019acheter neuf."',
          content: {
            tiles: ['Ça', 'ne', 'vaut', 'pas', 'la', 'peine', "d'acheter", 'neuf.', 'vaux', 'achat'],
          },
          answer: "Ça ne vaut pas la peine d'acheter neuf.",
          explanation: '"Ne pas valoir la peine de" + infinitive.',
        },
      ],
    },
  ],
}

export const items = {
  budget: {
    id: 'budget',
    type: 'vocabulary',
    word: 'budget',
    meaning: 'budget',
    partOfSpeech: 'noun (m.)',
    level: 'B1',
    topic: "L'économie",
    example: 'Il faut établir un budget mensuel.',
    related: ['dépenses', 'finances'],
  },
  depense: {
    id: 'depense',
    type: 'vocabulary',
    word: 'dépense',
    meaning: 'expense / spending',
    partOfSpeech: 'noun (f.)',
    level: 'B1',
    topic: "L'économie",
    example: 'Les dépenses ont augmenté cette année.',
    related: ['coût'],
  },
  credit: {
    id: 'credit',
    type: 'vocabulary',
    word: 'crédit',
    meaning: 'credit / loan',
    partOfSpeech: 'noun (m.)',
    level: 'B1',
    topic: "L'économie",
    example: 'Elle a contracté un crédit pour acheter sa voiture.',
    related: ['prêt', 'emprunt'],
  },
  entreprise: {
    id: 'entreprise',
    type: 'vocabulary',
    word: 'entreprise',
    meaning: 'company',
    partOfSpeech: 'noun (f.)',
    level: 'B1',
    topic: "L'économie",
    example: "L'entreprise embauche de nouveaux employés.",
    related: ['société', 'firme'],
  },
  marche: {
    id: 'marche',
    type: 'vocabulary',
    word: 'marché',
    meaning: 'market',
    partOfSpeech: 'noun (m.)',
    level: 'B1',
    topic: "L'économie",
    example: "Le marché de l'emploi est dynamique.",
    related: ['secteur'],
  },

  'couter-cher': {
    id: 'couter-cher',
    type: 'phrase',
    phrase: 'Coûter cher',
    meaning: 'To cost a lot',
    function: 'Price',
    level: 'B1',
    topic: "L'économie",
    tefUsage: 'Expression orale — parler des prix',
    example: 'Ce logement coûte très cher.',
    related: ['Être hors de prix'],
  },
  'faire-des-economies': {
    id: 'faire-des-economies',
    type: 'phrase',
    phrase: 'Faire des économies',
    meaning: 'To save money',
    function: 'Personal finance',
    level: 'B1',
    topic: "L'économie",
    tefUsage: 'Expression orale — parler de son budget',
    example: 'On fait des économies en cuisinant à la maison.',
    related: ['Épargner'],
  },
  'ca-ne-vaut-pas-la-peine': {
    id: 'ca-ne-vaut-pas-la-peine',
    type: 'phrase',
    phrase: 'Ça ne vaut pas la peine',
    meaning: "It's not worth it",
    function: 'Evaluating',
    level: 'B1',
    topic: "L'économie",
    tefUsage: 'Expression orale — donner une appréciation',
    example: "Ça ne vaut pas la peine d'acheter neuf.",
    related: ["Ça ne vaut pas le coup"],
  },

  partitif: {
    id: 'partitif',
    type: 'grammar',
    title: 'Le partitif: du, de la, des (de after negatives)',
    level: 'B1',
    explanation:
      'Use du/de la/des for "some": je bois du café, il y a de la concurrence. After a negative or a quantity expression, it becomes de.',
    examples: ['Ce magasin vend du luxe.', "Il n'achète pas de luxe."],
    counterexamples: ["Il n'achète pas des luxe. (incorrect — after a negative, du/de la/des becomes de)"],
  },
}