// Hand-authored TEF theme unit (spec §3.2.1) — "L'éducation" (Education). Part of the full TEF
// theme coverage in the Learn path. Exports the same { unit, items } shape as generated units
// (spec §3.2.6). All exercises are tap-only (spec §3.2.2).

export const unit = {
  id: 'education',
  title: 'L’éducation',
  description: 'Describe school, training, and learning — past habits and concrete results.',
  lessons: [
    {
      id: 'education-vocabulaire',
      title: 'Vocabulaire de l’éducation',
      learningItemIds: ['formation', 'diplome', 'matiere', 'apprentissage'],
      exercises: [
        {
          id: 'edu-1',
          learningItemId: 'formation',
          type: 'multiple_choice',
          stage: 'recognition',
          prompt: 'What does "une formation" mean?',
          content: { options: ['training', 'a uniform', 'a formation (geology)', 'a fine'] },
          answer: 'training',
          explanation: '"Une formation" is "training" — a course of study or qualifying program.',
        },
        {
          id: 'edu-2',
          learningItemId: 'diplome',
          type: 'multiple_choice',
          stage: 'recognition',
          prompt: 'What does "un diplôme" mean?',
          content: { options: ['a diploma', 'a doctor', 'a document', 'an essay'] },
          answer: 'a diploma',
          explanation: '"Un diplôme" is a "diploma" or "degree."',
        },
        {
          id: 'edu-3',
          learningItemId: 'matiere',
          type: 'translation',
          stage: 'recall',
          prompt: 'Translate: school subject',
          content: { direction: 'en_to_fr', options: ['matière', 'matériel', 'matin', 'maison'] },
          answer: 'matière',
          explanation: 'A school subject is "une matière."',
        },
        {
          id: 'edu-4',
          learningItemId: 'apprentissage',
          type: 'translation',
          stage: 'recall',
          prompt: 'Translate: learning',
          content: { direction: 'en_to_fr', options: ['apprentissage', 'appréciation', 'attente', 'après-midi'] },
          answer: 'apprentissage',
          explanation: '"Learning" translates to "l\u2019apprentissage."',
        },
        {
          id: 'edu-5',
          learningItemId: 'formation',
          type: 'fill_blank',
          stage: 'context',
          prompt: 'Complete the sentence',
          content: {
            sentence: "La ______ continue permet d'évoluer dans son travail.",
            options: ['formation', 'famille', 'fortune', 'fonction'],
          },
          answer: 'formation',
          explanation: '"La formation continue" is "continuing education."',
        },
        {
          id: 'edu-6',
          learningItemId: 'diplome',
          type: 'fill_blank',
          stage: 'context',
          prompt: 'Complete the sentence',
          content: {
            sentence: "Ce ______ est reconnu à l'étranger.",
            options: ['diplôme', 'diplômé', 'diplomate', 'dossier'],
          },
          answer: 'diplôme',
          explanation: '"Le diplôme" (noun) has no final e — "diplômé" is the adjective.',
        },
      
        {
          id: 'edu-31',
          learningItemId: 'formation',
          type: 'fill_blank',
          stage: 'context',
          prompt: 'Complétez la phrase : La ________ professionnelle aide les salariés à acquérir de nouvelles compétences.',
          content: {"sentence":"La ________ professionnelle aide les salariés à acquérir de nouvelles compétences.","options":["formation","diplôme","matière","apprentissage"]},
          answer: 'formation',
          explanation: '"formation" means training or professional development.',
        },
        {
          id: 'edu-32',
          learningItemId: 'diplome',
          type: 'multiple_choice',
          stage: 'recognition',
          prompt: 'What is the meaning of "un diplôme" in English?',
          content: {"options":["a diploma","a certificate","a diploma (geology)","a fine"]},
          answer: 'a diploma',
          explanation: '"un diplôme" translates to "a diploma" or "degree."',
        },
        {
          id: 'edu-33',
          learningItemId: 'matiere',
          type: 'translation',
          stage: 'recall',
          prompt: 'Translate to French: "school subject"',
          content: {"options":["une matière","un diplôme","une formation","un apprentissage"]},
          answer: 'une matière',
          explanation: 'The French word for school subject is "une matière."',
        },
        {
          id: 'edu-34',
          learningItemId: 'apprentissage',
          type: 'pronunciation',
          stage: 'completion',
          prompt: 'Pronounce the following sentence correctly:',
          content: {"sentence":"L'apprentissage de la langue nécessite de la régularité."},
          answer: 'L\'apprentissage de la langue nécessite de la régularité.',
          explanation: 'Listen and repeat the sentence to master pronunciation.',
        },
        {
          id: 'edu-35',
          learningItemId: 'formation',
          type: 'multiple_choice',
          stage: 'context',
          prompt: 'Which phrase best completes: "Je participe à une ________ pour améliorer mes compétences professionnelles."',
          content: {"options":["formation","diplôme","matière","apprentissage"]},
          answer: 'formation',
          explanation: 'The sentence refers to a training program.',
        },
        {
          id: 'edu-36',
          learningItemId: 'diplome',
          type: 'fill_blank',
          stage: 'recall',
          prompt: 'Complete the sentence: "Pour obtenir ce ________, il faut réussir l\'examen final."',
          content: {"sentence":"Pour obtenir ce ________, il faut réussir l'examen final.","options":["diplôme","formation","matière","apprentissage"]},
          answer: 'diplôme',
          explanation: 'The blank refers to a diploma or degree.',
        },
        {
          id: 'edu-37',
          learningItemId: 'matiere',
          type: 'multiple_choice',
          stage: 'recognition',
          prompt: 'Which word means "discipline" in French?',
          content: {"options":["matière","diplôme","formation","apprentissage"]},
          answer: 'matière',
          explanation: '"matière" can mean both school subject and discipline.',
        },
        {
          id: 'edu-38',
          learningItemId: 'apprentissage',
          type: 'translation',
          stage: 'context',
          prompt: 'Translate to French: "learning process"',
          content: {"options":["processus d'apprentissage","processus de formation","processus de diplôme","processus de matière"]},
          answer: 'processus d\'apprentissage',
          explanation: 'The French translation is "processus d\'apprentissage."',
        },
        {
          id: 'edu-39',
          learningItemId: 'formation',
          type: 'multiple_choice',
          stage: 'recall',
          prompt: 'What does "une formation" refer to?',
          content: {"options":["a training program","a diploma","a school subject","an apprenticeship"]},
          answer: 'a training program',
          explanation: '"une formation" is a training or course of study.',
        },
        {
          id: 'edu-40',
          learningItemId: 'apprentissage',
          type: 'pronunciation',
          stage: 'completion',
          prompt: 'Pronounce: "L\'apprentissage exige de la persévérance."',
          content: {"sentence":"L'apprentissage exige de la persévérance."},
          answer: 'L\'apprentissage exige de la persévérance.',
          explanation: 'Practice the sentence to improve pronunciation.',
        },
      ],
    },
    {
      id: 'education-idees',
      title: 'Construire des idées',
      learningItemIds: ['passe-compose-imparfait', 'au-fil-des-annees'],
      exercises: [
        {
          id: 'edu-7',
          learningItemId: 'passe-compose-imparfait',
          type: 'multiple_choice',
          stage: 'recognition',
          prompt: 'Which sentence describes a past habit correctly?',
          content: {
            options: [
              "Quand j'étais enfant, je jouais au football.",
              "Quand j'ai été enfant, j'ai joué au football.",
            ],
          },
          answer: "Quand j'étais enfant, je jouais au football.",
          explanation: 'Past habits and background use the imparfait.',
        },
        {
          id: 'edu-8',
          learningItemId: 'passe-compose-imparfait',
          type: 'fill_blank',
          stage: 'context',
          prompt: 'Complete the sentence',
          content: {
            sentence: "Quand j'______ enfant, je jouais au football.",
            options: ['étais', 'était', 'été', 'étaient'],
          },
          answer: 'étais',
          explanation: 'Subject "je" takes the imparfait form "étais."',
        },
        {
          id: 'edu-9',
          learningItemId: 'passe-compose-imparfait',
          type: 'fill_blank',
          stage: 'transformation',
          prompt: 'Complete the sentence (a single completed action)',
          content: {
            sentence: "L'année dernière, j'ai ______ le français.",
            options: ['étudié', 'étudiais', 'étudie', 'étudiée'],
          },
          answer: 'étudié',
          explanation: 'A single completed action takes the passé composé: "j\u2019ai étudié."',
        },
        {
          id: 'edu-10',
          learningItemId: 'au-fil-des-annees',
          type: 'multiple_choice',
          stage: 'recognition',
          prompt: 'What does "Au fil des années" mean?',
          content: { options: ['Over the years', 'From year one', 'During the year', 'Every other year'] },
          answer: 'Over the years',
          explanation: '"Au fil des années" means progressively, "over the years."',
        },
        {
          id: 'edu-11',
          learningItemId: 'au-fil-des-annees',
          type: 'fill_blank',
          stage: 'context',
          prompt: 'Complete the sentence',
          content: {
            sentence: "______ des années, l'école a beaucoup changé.",
            options: ['Au fil', 'Au sein', 'Au bord', 'Au fond'],
          },
          answer: 'Au fil',
          explanation: 'The fixed expression is "au fil des années."',
        },
        {
          id: 'edu-12',
          learningItemId: 'au-fil-des-annees',
          type: 'translation',
          stage: 'recall',
          prompt: 'Translate: over the years',
          content: {
            direction: 'en_to_fr',
            options: ['au fil des années', 'au milieu des années', 'au bout des années', 'au début des années'],
          },
          answer: 'au fil des années',
          explanation: '"Over the years" translates to "au fil des années."',
        },
      
        {
          id: 'edu-19',
          learningItemId: 'passe-compose-imparfait',
          type: 'multiple_choice',
          stage: 'recognition',
          prompt: 'Which sentence uses the imparfait for a past habit?',
          content: {"options":["Quand j'ai été enfant, j'ai joué au football.","Quand j'étais enfant, je jouais au football."]},
          answer: 'Quand j\'étais enfant, je jouais au football.',
          explanation: 'Past habits use the imparfait.',
        },
        {
          id: 'edu-20',
          learningItemId: 'passe-compose-imparfait',
          type: 'fill_blank',
          stage: 'context',
          prompt: 'Complete the sentence with the correct form of "être" in the imparfait for "nous".',
          content: {"sentence":"Nous ________ toujours à l'école à 8h.","options":["étions","étiez","étaient","été"]},
          answer: 'étions',
          explanation: 'Subject "nous" takes the imparfait form "étions."',
        },
        {
          id: 'edu-21',
          learningItemId: 'passe-compose-imparfait',
          type: 'translation',
          stage: 'recall',
          prompt: 'Translate into French: "They were studying when the teacher entered the room."',
          content: {"options":["Ils étaient étudié quand l'enseignant est entré.","Ils étudiaient quand l'enseignant est entré.","Ils étudiaient quand le professeur est entré.","Ils étaient étudier quand l'enseignant est entré."]},
          answer: 'Ils étudiaient quand le professeur est entré.',
          explanation: 'Use the imparfait for ongoing action and passé composé for the completed action.',
        },
        {
          id: 'edu-22',
          learningItemId: 'passe-compose-imparfait',
          type: 'fill_blank',
          stage: 'recall',
          prompt: 'Choose the correct form of "avoir" in the passé composé for "vous".',
          content: {"sentence":"Vous _______ étudié la leçon hier.","options":["avez eu","avez étudié","aviez étudié","avez été"]},
          answer: 'avez étudié',
          explanation: 'Passé composé uses auxiliary "avoir" + past participle.',
        },
        {
          id: 'edu-23',
          learningItemId: 'au-fil-des-annees',
          type: 'pronunciation',
          stage: 'production',
          prompt: 'Pronounce the following phrase correctly:',
          content: {"sentence":"Au fil des années, l'école a beaucoup changé."},
          answer: 'Au fil des années, l\'école a beaucoup changé.',
          explanation: 'Focus on the nasal vowel in "fil" and the liaison in "des années."',
        },
        {
          id: 'edu-24',
          learningItemId: 'passe-compose-imparfait',
          type: 'fill_blank',
          stage: 'recall',
          prompt: 'Complete with the appropriate form of "avoir" in the passé composé for "ils".',
          content: {"sentence":"Ils _______ fini le projet avant l'échéance.","options":["ont fini","avaient fini","ont été fini","avaient été fini"]},
          answer: 'ont fini',
          explanation: 'Passé composé uses "avoir" + past participle.',
        },
      ],
    },
    {
      id: 'education-argumenter',
      title: 'Argumenter sur l’éducation',
      learningItemIds: ['avoir-la-chance-de', 'non-seulement', 'reussite'],
      exercises: [
        {
          id: 'edu-13',
          learningItemId: 'avoir-la-chance-de',
          type: 'multiple_choice',
          stage: 'recognition',
          prompt: 'What does "Avoir la chance de" mean?',
          content: { options: ['To be lucky enough to', 'To take a chance on', 'To miss a chance', 'To give a chance to'] },
          answer: 'To be lucky enough to',
          explanation: '"Avoir la chance de" = "to be lucky enough to."',
        },
        {
          id: 'edu-14',
          learningItemId: 'avoir-la-chance-de',
          type: 'fill_blank',
          stage: 'context',
          prompt: 'Complete the sentence',
          content: {
            sentence: "J'ai eu la ______ de partir en échange universitaire.",
            options: ['chance', 'chanson', 'chambre', 'chapeau'],
          },
          answer: 'chance',
          explanation: 'The expression is "avoir la chance de" + infinitive.',
        },
        {
          id: 'edu-15',
          learningItemId: 'non-seulement',
          type: 'multiple_choice',
          stage: 'recognition',
          prompt: 'What does "Non seulement… mais aussi" do?',
          content: { options: ['Adds an extra point with emphasis', 'Shows cause and effect', 'Introduces a contrast', 'Gives an example'] },
          answer: 'Adds an extra point with emphasis',
          explanation: '"Non seulement… mais aussi" = "not only… but also" — it emphasizes an added point.',
        },
        {
          id: 'edu-16',
          learningItemId: 'reussite',
          type: 'fill_blank',
          stage: 'context',
          prompt: 'Complete the sentence',
          content: {
            sentence: 'La ______ scolaire dépend de beaucoup de facteurs.',
            options: ['réussite', 'résistance', 'recherche', 'raison'],
          },
          answer: 'réussite',
          explanation: '"La réussite scolaire" is "academic success."',
        },
        {
          id: 'edu-17',
          learningItemId: 'avoir-la-chance-de',
          type: 'pronunciation',
          stage: 'production',
          prompt: 'Say the sentence aloud.',
          content: { sentence: "J'ai eu la chance de partir en échange universitaire." },
          answer: "J'ai eu la chance de partir en échange universitaire.",
          explanation: '"Avoir la chance de" + infinitive in the passé composé.',
        },
        {
          id: 'edu-18',
          learningItemId: 'non-seulement',
          type: 'pronunciation',
          stage: 'production',
          prompt: 'Say the sentence aloud.',
          content: { sentence: 'Non seulement les cours sont gratuits, mais aussi la cantine.' },
          answer: 'Non seulement les cours sont gratuits, mais aussi la cantine.',
          explanation: '"Non seulement… mais aussi" brackets the two additions.',
        },
      
        {
          id: 'edu-25',
          learningItemId: 'non-seulement',
          type: 'multiple_choice',
          stage: 'recall',
          prompt: 'Which expression means "Not only… but also" in French?',
          content: {"options":["Avoir la chance de","Non seulement… mais aussi","Réussite","Et même"]},
          answer: 'Non seulement… mais aussi',
          explanation: 'The phrase "Non seulement… mais aussi" translates to "Not only… but also."',
        },
        {
          id: 'edu-26',
          learningItemId: 'reussite',
          type: 'fill_blank',
          stage: 'context',
          prompt: 'Complete the sentence: "Il est important de ______ la réussite de ses projets."',
          content: {"sentence":"Il est important de ______ la réussite de ses projets.","options":["favoriser","défavoriser","favorisant","favorisé"]},
          answer: 'favoriser',
          explanation: 'The verb "favoriser" means to promote or encourage.',
        },
        {
          id: 'edu-27',
          learningItemId: 'non-seulement',
          type: 'pronunciation',
          stage: 'production',
          prompt: 'Pronounce the following sentence correctly:',
          content: {"sentence":"Non seulement les examens sont difficiles, mais aussi les devoirs à rendre."},
          answer: 'Non seulement les examens sont difficiles, mais aussi les devoirs à rendre.',
          explanation: 'Focus on the liaison between "non seulement" and "les" and the nasal vowel in "difficultés."',
        },
        {
          id: 'edu-28',
          learningItemId: 'reussite',
          type: 'fill_blank',
          stage: 'context',
          prompt: 'Complete the sentence: "J\'ai ______ la réussite de mes étudiants grâce à un tutorat adapté."',
          content: {"sentence":"J'ai ______ la réussite de mes étudiants grâce à un tutorat adapté.","options":["favorisé","favorisant","favorise","favoriser"]},
          answer: 'favoriser',
          explanation: 'The infinitive "favoriser" follows "avoir" in this construction.',
        },
        {
          id: 'edu-29',
          learningItemId: 'reussite',
          type: 'multiple_choice',
          stage: 'recall',
          prompt: 'Which option is the plural form of "réussite"?',
          content: {"options":["réussites","réussits","réussie","réussies"]},
          answer: 'réussites',
          explanation: 'The noun "réussite" is feminine; its plural is "réussites."',
        },
        {
          id: 'edu-30',
          learningItemId: 'avoir-la-chance-de',
          type: 'pronunciation',
          stage: 'production',
          prompt: 'Pronounce the following sentence:',
          content: {"sentence":"J'ai eu la chance de participer à la conférence internationale."},
          answer: 'J\'ai eu la chance de participer à la conférence internationale.',
          explanation: 'Pay attention to the liaison between "chance" and "de" and the nasal vowel in "chance."',
        },
      ],
    },
  ],
}

export const items = {
  formation: {
    id: 'formation',
    type: 'vocabulary',
    word: 'formation',
    meaning: 'training',
    partOfSpeech: 'noun (f.)',
    level: 'B1',
    topic: "L'éducation",
    example: "La formation continue permet d'évoluer dans son travail.",
    related: ['cours', 'stage'],
  },
  diplome: {
    id: 'diplome',
    type: 'vocabulary',
    word: 'diplôme',
    meaning: 'diploma / degree',
    partOfSpeech: 'noun (m.)',
    level: 'B1',
    topic: "L'éducation",
    example: "Ce diplôme est reconnu à l'étranger.",
    related: ['certificat'],
  },
  matiere: {
    id: 'matiere',
    type: 'vocabulary',
    word: 'matière',
    meaning: 'school subject',
    partOfSpeech: 'noun (f.)',
    level: 'B1',
    topic: "L'éducation",
    example: 'Quelle est ta matière préférée ?',
    related: ['discipline'],
  },
  reussite: {
    id: 'reussite',
    type: 'vocabulary',
    word: 'réussite',
    meaning: 'success',
    partOfSpeech: 'noun (f.)',
    level: 'B1',
    topic: "L'éducation",
    example: 'La réussite scolaire dépend de beaucoup de facteurs.',
    related: ['succès'],
  },
  apprentissage: {
    id: 'apprentissage',
    type: 'vocabulary',
    word: 'apprentissage',
    meaning: 'learning',
    partOfSpeech: 'noun (m.)',
    level: 'B1',
    topic: "L'éducation",
    example: "L'apprentissage d'une langue demande de la régularité.",
    related: ['étude'],
  },

  'au-fil-des-annees': {
    id: 'au-fil-des-annees',
    type: 'phrase',
    phrase: 'Au fil des années',
    meaning: 'Over the years',
    function: 'Describing change over time',
    level: 'B1',
    topic: "L'éducation",
    tefUsage: 'Expression orale / écrite — évoquer le changement',
    example: "Au fil des années, l'école a beaucoup changé.",
    related: ['Avec le temps'],
  },
  'avoir-la-chance-de': {
    id: 'avoir-la-chance-de',
    type: 'phrase',
    phrase: 'Avoir la chance de',
    meaning: 'To be lucky enough to',
    function: 'A positive opportunity',
    level: 'B1',
    topic: "L'éducation",
    tefUsage: 'Expression orale — raconter une expérience',
    example: "J'ai eu la chance de partir en échange universitaire.",
    related: ["Avoir l'occasion de"],
    conjugation: {
      je: "J'ai la chance de",
      tu: "Tu as la chance de",
      ilElle: "Il/Elle a la chance de",
      nous: "Nous avons la chance de",
      vous: "Vous avez la chance de",
      ilsElles: "Ils/Elles ont la chance de",
    },
  },
  'non-seulement': {
    id: 'non-seulement',
    type: 'phrase',
    phrase: 'Non seulement… mais aussi',
    meaning: 'Not only… but also',
    function: 'Adding emphasis',
    level: 'B1',
    topic: "L'éducation",
    tefUsage: 'Expression orale / écrite — argumentation',
    example: 'Non seulement les cours sont gratuits, mais aussi la cantine.',
    related: ['Et même'],
  },

  'passe-compose-imparfait': {
    id: 'passe-compose-imparfait',
    type: 'grammar',
    title: 'Imparfait for past habits and descriptions',
    level: 'B1',
    explanation:
      'Use the imparfait (j\u2019étais, j\u2019habitais) for past habits and descriptions; use the passé composé for single completed actions.',
    examples: ["Quand j'étais enfant, je jouais au football.", "L'année dernière, j'ai étudié le français."],
    counterexamples: ['Hier, je jouais au football. (ambiguous — for one completed action, prefer "j\u2019ai joué")'],
  },
}