// Hand-authored TEF theme unit (spec §3.2.1) — "L'éducation" (Education). Part of the full TEF
// theme coverage in the Learn path. Exports the same { unit, items } shape as generated units
// (spec §3.2.6). All exercises are tap-only (spec §3.2.2).

export const unit = {
  id: 'education',
  title: 'L’éducation',
  description: 'Describe school, training, and learning — past habits and concrete results.',
  lessons: [
    {
      id: 'education-vocabulaire',
      title: 'Vocabulaire de l’éducation',
      learningItemIds: ['formation', 'diplome', 'matiere', 'apprentissage'],
      exercises: [
        {
          id: 'edu-1',
          learningItemId: 'formation',
          type: 'multiple_choice',
          stage: 'recognition',
          prompt: 'What does "une formation" mean?',
          content: { options: ['training', 'a uniform', 'a formation (geology)', 'a fine'] },
          answer: 'training',
          explanation: '"Une formation" is "training" — a course of study or qualifying program.',
        },
        {
          id: 'edu-2',
          learningItemId: 'diplome',
          type: 'multiple_choice',
          stage: 'recognition',
          prompt: 'What does "un diplôme" mean?',
          content: { options: ['a diploma', 'a doctor', 'a document', 'an essay'] },
          answer: 'a diploma',
          explanation: '"Un diplôme" is a "diploma" or "degree."',
        },
        {
          id: 'edu-3',
          learningItemId: 'matiere',
          type: 'translation',
          stage: 'recall',
          prompt: 'Translate: school subject',
          content: { direction: 'en_to_fr', options: ['matière', 'matériel', 'matin', 'maison'] },
          answer: 'matière',
          explanation: 'A school subject is "une matière."',
        },
        {
          id: 'edu-4',
          learningItemId: 'apprentissage',
          type: 'translation',
          stage: 'recall',
          prompt: 'Translate: learning',
          content: { direction: 'en_to_fr', options: ['apprentissage', 'appréciation', 'attente', 'après-midi'] },
          answer: 'apprentissage',
          explanation: '"Learning" translates to "l\u2019apprentissage."',
        },
        {
          id: 'edu-5',
          learningItemId: 'formation',
          type: 'fill_blank',
          stage: 'context',
          prompt: 'Complete the sentence',
          content: {
            sentence: "La ______ continue permet d'évoluer dans son travail.",
            options: ['formation', 'famille', 'fortune', 'fonction'],
          },
          answer: 'formation',
          explanation: '"La formation continue" is "continuing education."',
        },
        {
          id: 'edu-6',
          learningItemId: 'diplome',
          type: 'fill_blank',
          stage: 'context',
          prompt: 'Complete the sentence',
          content: {
            sentence: "Ce ______ est reconnu à l'étranger.",
            options: ['diplôme', 'diplômé', 'diplomate', 'dossier'],
          },
          answer: 'diplôme',
          explanation: '"Le diplôme" (noun) has no final e — "diplômé" is the adjective.',
        },
      ],
    },
    {
      id: 'education-idees',
      title: 'Construire des idées',
      learningItemIds: ['passe-compose-imparfait', 'au-fil-des-annees'],
      exercises: [
        {
          id: 'edu-7',
          learningItemId: 'passe-compose-imparfait',
          type: 'multiple_choice',
          stage: 'recognition',
          prompt: 'Which sentence describes a past habit correctly?',
          content: {
            options: [
              "Quand j'étais enfant, je jouais au football.",
              "Quand j'ai été enfant, j'ai joué au football.",
            ],
          },
          answer: "Quand j'étais enfant, je jouais au football.",
          explanation: 'Past habits and background use the imparfait.',
        },
        {
          id: 'edu-8',
          learningItemId: 'passe-compose-imparfait',
          type: 'fill_blank',
          stage: 'context',
          prompt: 'Complete the sentence',
          content: {
            sentence: "Quand j'______ enfant, je jouais au football.",
            options: ['étais', 'était', 'été', 'étaient'],
          },
          answer: 'étais',
          explanation: 'Subject "je" takes the imparfait form "étais."',
        },
        {
          id: 'edu-9',
          learningItemId: 'passe-compose-imparfait',
          type: 'fill_blank',
          stage: 'transformation',
          prompt: 'Complete the sentence (a single completed action)',
          content: {
            sentence: "L'année dernière, j'ai ______ le français.",
            options: ['étudié', 'étudiais', 'étudie', 'étudiée'],
          },
          answer: 'étudié',
          explanation: 'A single completed action takes the passé composé: "j\u2019ai étudié."',
        },
        {
          id: 'edu-10',
          learningItemId: 'au-fil-des-annees',
          type: 'multiple_choice',
          stage: 'recognition',
          prompt: 'What does "Au fil des années" mean?',
          content: { options: ['Over the years', 'From year one', 'During the year', 'Every other year'] },
          answer: 'Over the years',
          explanation: '"Au fil des années" means progressively, "over the years."',
        },
        {
          id: 'edu-11',
          learningItemId: 'au-fil-des-annees',
          type: 'fill_blank',
          stage: 'context',
          prompt: 'Complete the sentence',
          content: {
            sentence: "______ des années, l'école a beaucoup changé.",
            options: ['Au fil', 'Au sein', 'Au bord', 'Au fond'],
          },
          answer: 'Au fil',
          explanation: 'The fixed expression is "au fil des années."',
        },
        {
          id: 'edu-12',
          learningItemId: 'au-fil-des-annees',
          type: 'translation',
          stage: 'recall',
          prompt: 'Translate: over the years',
          content: {
            direction: 'en_to_fr',
            options: ['au fil des années', 'au milieu des années', 'au bout des années', 'au début des années'],
          },
          answer: 'au fil des années',
          explanation: '"Over the years" translates to "au fil des années."',
        },
      ],
    },
    {
      id: 'education-argumenter',
      title: 'Argumenter sur l’éducation',
      learningItemIds: ['avoir-la-chance-de', 'non-seulement', 'reussite'],
      exercises: [
        {
          id: 'edu-13',
          learningItemId: 'avoir-la-chance-de',
          type: 'multiple_choice',
          stage: 'recognition',
          prompt: 'What does "Avoir la chance de" mean?',
          content: { options: ['To be lucky enough to', 'To take a chance on', 'To miss a chance', 'To give a chance to'] },
          answer: 'To be lucky enough to',
          explanation: '"Avoir la chance de" = "to be lucky enough to."',
        },
        {
          id: 'edu-14',
          learningItemId: 'avoir-la-chance-de',
          type: 'fill_blank',
          stage: 'context',
          prompt: 'Complete the sentence',
          content: {
            sentence: "J'ai eu la ______ de partir en échange universitaire.",
            options: ['chance', 'chanson', 'chambre', 'chapeau'],
          },
          answer: 'chance',
          explanation: 'The expression is "avoir la chance de" + infinitive.',
        },
        {
          id: 'edu-15',
          learningItemId: 'non-seulement',
          type: 'multiple_choice',
          stage: 'recognition',
          prompt: 'What does "Non seulement… mais aussi" do?',
          content: { options: ['Adds an extra point with emphasis', 'Shows cause and effect', 'Introduces a contrast', 'Gives an example'] },
          answer: 'Adds an extra point with emphasis',
          explanation: '"Non seulement… mais aussi" = "not only… but also" — it emphasizes an added point.',
        },
        {
          id: 'edu-16',
          learningItemId: 'reussite',
          type: 'fill_blank',
          stage: 'context',
          prompt: 'Complete the sentence',
          content: {
            sentence: 'La ______ scolaire dépend de beaucoup de facteurs.',
            options: ['réussite', 'résistance', 'recherche', 'raison'],
          },
          answer: 'réussite',
          explanation: '"La réussite scolaire" is "academic success."',
        },
        {
          id: 'edu-17',
          learningItemId: 'avoir-la-chance-de',
          type: 'production',
          stage: 'production',
          prompt: 'Build the sentence: "J\u2019ai eu la chance de partir en échange universitaire."',
          content: {
            tiles: ["J'ai", 'eu', 'la', 'chance', 'de', 'partir', 'en', 'échange', 'universitaire.', 'été', 'chanceux'],
          },
          answer: "J'ai eu la chance de partir en échange universitaire.",
          explanation: '"Avoir la chance de" + infinitive in the passé composé.',
        },
        {
          id: 'edu-18',
          learningItemId: 'non-seulement',
          type: 'production',
          stage: 'production',
          prompt: 'Build the sentence: "Non seulement les cours sont gratuits, mais aussi la cantine."',
          content: {
            tiles: ['Non', 'seulement', 'les', 'cours', 'sont', 'gratuits,', 'mais', 'aussi', 'la', 'cantine.', 'même', 'aussi bien'],
          },
          answer: 'Non seulement les cours sont gratuits, mais aussi la cantine.',
          explanation: '"Non seulement… mais aussi" brackets the two additions.',
        },
      ],
    },
  ],
}

export const items = {
  formation: {
    id: 'formation',
    type: 'vocabulary',
    word: 'formation',
    meaning: 'training',
    partOfSpeech: 'noun (f.)',
    level: 'B1',
    topic: "L'éducation",
    example: "La formation continue permet d'évoluer dans son travail.",
    related: ['cours', 'stage'],
  },
  diplome: {
    id: 'diplome',
    type: 'vocabulary',
    word: 'diplôme',
    meaning: 'diploma / degree',
    partOfSpeech: 'noun (m.)',
    level: 'B1',
    topic: "L'éducation",
    example: "Ce diplôme est reconnu à l'étranger.",
    related: ['certificat'],
  },
  matiere: {
    id: 'matiere',
    type: 'vocabulary',
    word: 'matière',
    meaning: 'school subject',
    partOfSpeech: 'noun (f.)',
    level: 'B1',
    topic: "L'éducation",
    example: 'Quelle est ta matière préférée ?',
    related: ['discipline'],
  },
  reussite: {
    id: 'reussite',
    type: 'vocabulary',
    word: 'réussite',
    meaning: 'success',
    partOfSpeech: 'noun (f.)',
    level: 'B1',
    topic: "L'éducation",
    example: 'La réussite scolaire dépend de beaucoup de facteurs.',
    related: ['succès'],
  },
  apprentissage: {
    id: 'apprentissage',
    type: 'vocabulary',
    word: 'apprentissage',
    meaning: 'learning',
    partOfSpeech: 'noun (m.)',
    level: 'B1',
    topic: "L'éducation",
    example: "L'apprentissage d'une langue demande de la régularité.",
    related: ['étude'],
  },

  'au-fil-des-annees': {
    id: 'au-fil-des-annees',
    type: 'phrase',
    phrase: 'Au fil des années',
    meaning: 'Over the years',
    function: 'Describing change over time',
    level: 'B1',
    topic: "L'éducation",
    tefUsage: 'Expression orale / écrite — évoquer le changement',
    example: "Au fil des années, l'école a beaucoup changé.",
    related: ['Avec le temps'],
  },
  'avoir-la-chance-de': {
    id: 'avoir-la-chance-de',
    type: 'phrase',
    phrase: 'Avoir la chance de',
    meaning: 'To be lucky enough to',
    function: 'A positive opportunity',
    level: 'B1',
    topic: "L'éducation",
    tefUsage: 'Expression orale — raconter une expérience',
    example: "J'ai eu la chance de partir en échange universitaire.",
    related: ["Avoir l'occasion de"],
  },
  'non-seulement': {
    id: 'non-seulement',
    type: 'phrase',
    phrase: 'Non seulement… mais aussi',
    meaning: 'Not only… but also',
    function: 'Adding emphasis',
    level: 'B1',
    topic: "L'éducation",
    tefUsage: 'Expression orale / écrite — argumentation',
    example: 'Non seulement les cours sont gratuits, mais aussi la cantine.',
    related: ['Et même'],
  },

  'passe-compose-imparfait': {
    id: 'passe-compose-imparfait',
    type: 'grammar',
    title: 'Imparfait for past habits and descriptions',
    level: 'B1',
    explanation:
      'Use the imparfait (j\u2019étais, j\u2019habitais) for past habits and descriptions; use the passé composé for single completed actions.',
    examples: ["Quand j'étais enfant, je jouais au football.", "L'année dernière, j'ai étudié le français."],
    counterexamples: ['Hier, je jouais au football. (ambiguous — for one completed action, prefer "j\u2019ai joué")'],
  },
}