// Hand-authored TEF theme unit (spec §3.2.1) — "L'environnement" (Environment). Part of the full
// TEF theme coverage in the Learn path. Exports the same { unit, items } shape as generated units
// (spec §3.2.6). All exercises are tap-only (spec §3.2.2).

export const unit = {
  id: 'environnement',
  title: 'L’environnement',
  description: 'Discuss climate, pollution, and sustainability with the right arguments.',
  lessons: [
    {
      id: 'environnement-vocabulaire',
      title: 'Vocabulaire de l’environnement',
      learningItemIds: ['changement-climatique', 'pollution', 'dechets', 'recyclage'],
      exercises: [
        {
          id: 'env-1',
          learningItemId: 'pollution',
          type: 'multiple_choice',
          stage: 'recognition',
          prompt: 'What does "la pollution" mean?',
          content: { options: ['pollution', 'volunteering', 'purification', 'population'] },
          answer: 'pollution',
          explanation: '"La pollution" means "pollution" — contamination of air, water, or soil.',
        },
        {
          id: 'env-2',
          learningItemId: 'recyclage',
          type: 'multiple_choice',
          stage: 'recognition',
          prompt: 'What does "le recyclage" mean?',
          content: { options: ['recycling', 'recovering', 'returning', 'risk'] },
          answer: 'recycling',
          explanation: '"Le recyclage" is "recycling."',
        },
        {
          id: 'env-3',
          learningItemId: 'changement-climatique',
          type: 'translation',
          stage: 'recall',
          prompt: 'Translate: climate change',
          content: { direction: 'en_to_fr', options: ['changement climatique', 'saison des pluies', 'changement de décor', 'près de la mer'] },
          answer: 'changement climatique',
          explanation: '"Climate change" translates to "le changement climatique."',
        },
        {
          id: 'env-4',
          learningItemId: 'dechets',
          type: 'translation',
          stage: 'recall',
          prompt: 'Translate: waste',
          content: { direction: 'en_to_fr', options: ['déchets', 'détails', 'dettes', 'degrés'] },
          answer: 'déchets',
          explanation: '"Waste" translates to "les déchets."',
        },
        {
          id: 'env-5',
          learningItemId: 'dechets',
          type: 'fill_blank',
          stage: 'context',
          prompt: 'Complete the sentence',
          content: {
            sentence: 'Il faut réduire les ______.',
            options: ['déchets', 'pollution', 'recyclage', 'dépenses'],
          },
          answer: 'déchets',
          explanation: '"Les déchets" are the things we throw away — "waste."',
        },
        {
          id: 'env-6',
          learningItemId: 'changement-climatique',
          type: 'fill_blank',
          stage: 'context',
          prompt: 'Complete the sentence',
          content: {
            sentence: 'Le ______ climatique menace les côtes.',
            options: ['changement', 'changer', 'changeait', 'changeant'],
          },
          answer: 'changement',
          explanation: '"Le changement climatique" is the fixed noun phrase for "climate change."',
        },
      
        {
          id: 'env-19',
          learningItemId: 'changement-climatique',
          type: 'translation',
          stage: 'recall',
          prompt: 'Translate "Le changement climatique" into English.',
          content: {"options":["Climate change","Climate shift","Weather change","Temperature shift"]},
          answer: 'Climate change',
          explanation: '"Le changement climatique" means "Climate change."',
        },
        {
          id: 'env-20',
          learningItemId: 'changement-climatique',
          type: 'fill_blank',
          stage: 'context',
          prompt: 'Le ________ menace les côtes.',
          content: {"sentence":"Le ________ menace les côtes.","options":["changement climatique","pollution","déchets","recyclage"]},
          answer: 'changement climatique',
          explanation: 'The phrase means "Climate change threatens the coasts."',
        },
        {
          id: 'env-21',
          learningItemId: 'pollution',
          type: 'multiple_choice',
          stage: 'recognition',
          prompt: 'What is the meaning of "la pollution"?',
          content: {"options":["pollution","cleaning","protection","growth"]},
          answer: 'pollution',
          explanation: '"La pollution" means "pollution."',
        },
        {
          id: 'env-22',
          learningItemId: 'pollution',
          type: 'multiple_choice',
          stage: 'recognition',
          prompt: 'Which word best matches "la pollution de l\'air"?',
          content: {"options":["air pollution","water pollution","soil pollution","noise pollution"]},
          answer: 'air pollution',
          explanation: 'It refers to pollution of the air.',
        },
        {
          id: 'env-23',
          learningItemId: 'dechets',
          type: 'fill_blank',
          stage: 'context',
          prompt: 'Nous devons réduire les ________ en triant les matériaux.',
          content: {"sentence":"Nous devons réduire les ________ en triant les matériaux.","options":["déchets","pollution","recyclage","changement climatique"]},
          answer: 'déchets',
          explanation: 'It means "We must reduce waste by sorting materials."',
        },
        {
          id: 'env-24',
          learningItemId: 'recyclage',
          type: 'multiple_choice',
          stage: 'recall',
          prompt: 'What is "le recyclage" in English?',
          content: {"options":["recycling","recovery","return","risk"]},
          answer: 'recycling',
          explanation: '"Le recyclage" is "recycling."',
        },
        {
          id: 'env-25',
          learningItemId: 'recyclage',
          type: 'fill_blank',
          stage: 'context',
          prompt: 'Le ________ réduit la quantité de déchets.',
          content: {"sentence":"Le ________ réduit la quantité de déchets.","options":["recyclage","pollution","déchets","changement climatique"]},
          answer: 'recyclage',
          explanation: 'It means "Recycling reduces the amount of waste."',
        },
      ],
    },
    {
      id: 'environnement-idees',
      title: 'Construire des idées',
      learningItemIds: ['il-faut', 'il-vaut-mieux', 'energie-renouvelable'],
      exercises: [
        {
          id: 'env-7',
          learningItemId: 'il-faut',
          type: 'multiple_choice',
          stage: 'recognition',
          prompt: 'Which sentence is correct?',
          content: { options: ['Il faut protéger les océans.', 'Il faut protégeons les océans.'] },
          answer: 'Il faut protéger les océans.',
          explanation: '"Il faut" is always followed by an infinitive — never a conjugated verb.',
        },
        {
          id: 'env-8',
          learningItemId: 'il-faut',
          type: 'fill_blank',
          stage: 'transformation',
          prompt: 'Complete the sentence',
          content: {
            sentence: "Il ______ réduire la consommation d'énergie.",
            options: ['faut', 'vaut', 'veut', 'fais'],
          },
          answer: 'faut',
          explanation: '"Il faut" + infinitive expresses necessity.',
        },
        {
          id: 'env-9',
          learningItemId: 'energie-renouvelable',
          type: 'translation',
          stage: 'recall',
          prompt: 'Translate: renewable energy',
          content: { direction: 'en_to_fr', options: ['énergie renouvelable', 'énergie fossile', 'énergie simple', 'électricité'] },
          answer: 'énergie renouvelable',
          explanation: '"Renewable energy" translates to "l\u2019énergie renouvelable."',
        },
        {
          id: 'env-10',
          learningItemId: 'il-vaut-mieux',
          type: 'multiple_choice',
          stage: 'recognition',
          prompt: 'What does "Il vaut mieux" mean?',
          content: { options: ["It's better to", "It's necessary to", "It's forbidden to", "It's possible to"] },
          answer: "It's better to",
          explanation: '"Il vaut mieux" means "it\u2019s better to" — a softer, preference-based suggestion.',
        },
        {
          id: 'env-11',
          learningItemId: 'il-vaut-mieux',
          type: 'fill_blank',
          stage: 'context',
          prompt: 'Complete the sentence',
          content: {
            sentence: 'Il vaut ______ prendre le train que la voiture.',
            options: ['mieux', 'moins', 'plus', 'peu'],
          },
          answer: 'mieux',
          explanation: 'The fixed expression is "il vaut mieux" + infinitive.',
        },
        {
          id: 'env-12',
          learningItemId: 'energie-renouvelable',
          type: 'fill_blank',
          stage: 'context',
          prompt: 'Complete the sentence',
          content: {
            sentence: 'Les énergies ______ se développent.',
            options: ['renouvelables', 'renouvelable', 'renouvelées', 'renouveler'],
          },
          answer: 'renouvelables',
          explanation: '"Énergies" is feminine plural, so the adjective agrees: "renouvelables."',
        },
      
        {
          id: 'env-26',
          learningItemId: 'il-faut',
          type: 'fill_blank',
          stage: 'recall',
          prompt: 'Choose the right form of "il faut" to complete the sentence.',
          content: {"sentence":"Il _______ réduire les émissions de CO₂.","options":["faut","vaut","veut","fait"]},
          answer: 'faut',
          explanation: 'The expression "il faut" always takes an infinitive.',
        },
        {
          id: 'env-27',
          learningItemId: 'il-vaut-mieux',
          type: 'multiple_choice',
          stage: 'recall',
          prompt: 'Which of these sentences is an example of "il vaut mieux"?',
          content: {"options":["Il vaut mieux rester à la maison.","Il vaut mieux rester à la maison?","Il vaut mieux rester à la maison;","Il vaut mieux rester à la maison!"]},
          answer: 'Il vaut mieux rester à la maison.',
          explanation: 'The phrase must end with a period (or question mark) and not have an extra exclamation in the option.',
        },
        {
          id: 'env-28',
          learningItemId: 'il-vaut-mieux',
          type: 'fill_blank',
          stage: 'transformation',
          prompt: 'Transform the sentence using "il vaut mieux".',
          content: {"sentence":"Il est préférable de recycler les plastiques.","options":["Il vaut mieux recycler les plastiques.","Il vaut mieux recycler les plastiques?","Il vaut mieux recycler les plastiques!","Il vaut mieux recycler les plastiques;"]},
          answer: 'Il vaut mieux recycler les plastiques.',
          explanation: '"Il vaut mieux" is equivalent to "il est préférable de".',
        },
        {
          id: 'env-29',
          learningItemId: 'energie-renouvelable',
          type: 'multiple_choice',
          stage: 'recognition',
          prompt: 'Which word is a renewable energy source?',
          content: {"options":["énergie fossile","énergie renouvelable","énergie nucléaire","énergie thermique"]},
          answer: 'énergie renouvelable',
          explanation: 'Renewable energy comes from natural sources that regenerate.',
        },
        {
          id: 'env-30',
          learningItemId: 'energie-renouvelable',
          type: 'fill_blank',
          stage: 'context',
          prompt: 'Complete the sentence about renewable energy.',
          content: {"sentence":"Les __________ se développent rapidement.","options":["énergies renouvelables","énergies fossiles","énergies nucléaires","énergies solaires"]},
          answer: 'énergies renouvelables',
          explanation: 'The plural form matches the plural noun "énergies".',
        },
      ],
    },
    {
      id: 'environnement-argumenter',
      title: 'Argumenter sur l’environnement',
      learningItemIds: ['grace-a', 'dans-le-but-de'],
      exercises: [
        {
          id: 'env-13',
          learningItemId: 'grace-a',
          type: 'multiple_choice',
          stage: 'recognition',
          prompt: 'What does "Grâce à" mean?',
          content: { options: ['Thanks to', 'Because of (negative)', 'In order to', 'Instead of'] },
          answer: 'Thanks to',
          explanation: '"Grâce à" attributes a positive outcome: "thanks to." Use "à cause de" for negative causes.',
        },
        {
          id: 'env-14',
          learningItemId: 'grace-a',
          type: 'fill_blank',
          stage: 'context',
          prompt: 'Complete the sentence',
          content: {
            sentence: '______ au recyclage, nous produisons moins de déchets.',
            options: ['Grâce', 'Grace', 'Gras', 'Gare'],
          },
          answer: 'Grâce',
          explanation: 'The expression is "grâce à" — with the accent circonflexe: "Grâce."',
        },
        {
          id: 'env-15',
          learningItemId: 'dans-le-but-de',
          type: 'multiple_choice',
          stage: 'recognition',
          prompt: 'What does "Dans le but de" express?',
          content: { options: ['A purpose', 'A consequence', 'A contrast', 'A condition'] },
          answer: 'A purpose',
          explanation: '"Dans le but de" ("in order to") states the purpose of an action.',
        },
        {
          id: 'env-16',
          learningItemId: 'dans-le-but-de',
          type: 'fill_blank',
          stage: 'context',
          prompt: 'Complete the sentence',
          content: {
            sentence: 'Dans le ______ de réduire la pollution, la ville a fermé le centre aux voitures.',
            options: ['but', 'bout', 'bûche', 'boue'],
          },
          answer: 'but',
          explanation: '"Le but" is the goal — don\u2019t confuse it with "le bout" (the end).',
        },
        {
          id: 'env-17',
          learningItemId: 'il-faut',
          type: 'pronunciation',
          stage: 'production',
          prompt: 'Say the sentence aloud.',
          content: { sentence: 'Il faut protéger les océans.' },
          answer: 'Il faut protéger les océans.',
          explanation: '"Il faut" + infinitive, then the object.',
        },
        {
          id: 'env-18',
          learningItemId: 'grace-a',
          type: 'pronunciation',
          stage: 'production',
          prompt: 'Say the sentence aloud.',
          content: { sentence: 'Grâce au recyclage, nous produisons moins de déchets.' },
          answer: 'Grâce au recyclage, nous produisons moins de déchets.',
          explanation: '"Grâce à" opens the positive cause, then the result follows.',
        },
      
        {
          id: 'env-31',
          learningItemId: 'grace-a',
          type: 'multiple_choice',
          stage: 'recognition',
          prompt: 'Which phrase best completes the sentence: "______ la campagne, nous avons gagné un prix national."',
          content: {"options":["Grâce à","À cause de","Dans le but de","Afin de"]},
          answer: 'Grâce à',
          explanation: '"Grâce à" expresses a positive cause, similar to "thanks to".',
        },
        {
          id: 'env-32',
          learningItemId: 'grace-a',
          type: 'fill_blank',
          stage: 'context',
          prompt: 'Complete the sentence: "Le projet a été un succès, ______ la collaboration de tous."',
          content: {"sentence":"Le projet a été un succès, ______ la collaboration de tous.","options":["Grâce à","À cause de","Dans le but de","Afin de"]},
          answer: 'Grâce à',
          explanation: 'The correct expression is "grâce à" indicating a positive cause.',
        },
        {
          id: 'env-33',
          learningItemId: 'grace-a',
          type: 'translation',
          stage: 'recall',
          prompt: 'Translate into French: "Thanks to the new policy, we can recycle more."',
          content: {"options":["Grâce à la nouvelle politique, nous pouvons recycler davantage.","À cause de la nouvelle politique, nous pouvons recycler davantage.","Dans le but de la nouvelle politique, nous pouvons recycler davantage.","Afin de la nouvelle politique, nous pouvons recycler davantage."]},
          answer: 'Grâce à la nouvelle politique, nous pouvons recycler davantage.',
          explanation: 'Use "grâce à" for a positive cause.',
        },
        {
          id: 'env-34',
          learningItemId: 'grace-a',
          type: 'pronunciation',
          stage: 'transformation',
          prompt: 'Pronounce the phrase: "Grâce à la nature"',
          content: {"sentence":"Grâce à la nature"},
          answer: 'Grâce à la nature',
          explanation: 'Listen to the correct pronunciation of "grâce à" with the accent circonflexe.',
        },
        {
          id: 'env-35',
          learningItemId: 'dans-le-but-de',
          type: 'multiple_choice',
          stage: 'recognition',
          prompt: 'What does "Dans le but de" mean?',
          content: {"options":["In order to","Because of (negative)","Thanks to","Instead of"]},
          answer: 'In order to',
          explanation: '"Dans le but de" expresses a purpose, equivalent to "in order to".',
        },
        {
          id: 'env-36',
          learningItemId: 'dans-le-but-de',
          type: 'fill_blank',
          stage: 'context',
          prompt: 'Complete the sentence: "Ils ont rénové le parc, ______ offrir un espace de détente."',
          content: {"sentence":"Ils ont rénové le parc, ______ offrir un espace de détente.","options":["Dans le but de","Grâce à","À cause de","Afin de"]},
          answer: 'Dans le but de',
          explanation: 'The correct phrase is "dans le but de" to express purpose.',
        },
        {
          id: 'env-37',
          learningItemId: 'dans-le-but-de',
          type: 'translation',
          stage: 'recall',
          prompt: 'Translate into French: "In order to protect wildlife, the reserve was expanded."',
          content: {"options":["Dans le but de protéger la faune, la réserve a été agrandie.","À cause de protéger la faune, la réserve a été agrandie.","Grâce à protéger la faune, la réserve a été agrandie.","Afin de protéger la faune, la réserve a été agrandie."]},
          answer: 'Dans le but de protéger la faune, la réserve a été agrandie.',
          explanation: 'Use "dans le but de" for purpose.',
        },
        {
          id: 'env-38',
          learningItemId: 'dans-le-but-de',
          type: 'pronunciation',
          stage: 'transformation',
          prompt: 'Pronounce: "Dans le but de préserver l\'eau"',
          content: {"sentence":"Dans le but de préserver l'eau"},
          answer: 'Dans le but de préserver l\'eau',
          explanation: 'Listen to the correct pronunciation of "dans le but de".',
        },
        {
          id: 'env-39',
          learningItemId: 'grace-a',
          type: 'multiple_choice',
          stage: 'recall',
          prompt: 'Which sentence uses "grâce à" correctly?',
          content: {"options":["Grâce à l'orage, nous avons perdu le match.","Grâce à l'orage, nous avons gagné le match.","Grâce à l'orage, nous avons annulé le match.","Grâce à l'orage, nous avons amélioré le match."]},
          answer: 'Grâce à l\'orage, nous avons gagné le match.',
          explanation: '"Grâce à" is used for a positive outcome.',
        },
        {
          id: 'env-40',
          learningItemId: 'dans-le-but-de',
          type: 'fill_blank',
          stage: 'context',
          prompt: 'Complete: "Pour réduire le bruit, ils ont construit une barrière, ______ garantir la tranquillité du voisinage."',
          content: {"sentence":"Pour réduire le bruit, ils ont construit une barrière, ______ garantir la tranquillité du voisinage.","options":["Dans le but de","Grâce à","À cause de","Afin de"]},
          answer: 'Dans le but de',
          explanation: 'Purpose is expressed with "dans le but de".',
        },
      ],
    },
  ],
}

export const items = {
  'changement-climatique': {
    id: 'changement-climatique',
    type: 'vocabulary',
    word: 'changement climatique',
    meaning: 'climate change',
    partOfSpeech: 'noun (m.)',
    level: 'B1',
    topic: "L'environnement",
    example: 'Le changement climatique menace les côtes.',
    related: ['réchauffement climatique'],
  },
  pollution: {
    id: 'pollution',
    type: 'vocabulary',
    word: 'pollution',
    meaning: 'pollution',
    partOfSpeech: 'noun (f.)',
    level: 'B1',
    topic: "L'environnement",
    example: "La pollution de l'air est un problème grave.",
    related: ['émission'],
  },
  'energie-renouvelable': {
    id: 'energie-renouvelable',
    type: 'vocabulary',
    word: 'énergie renouvelable',
    meaning: 'renewable energy',
    partOfSpeech: 'noun (f.)',
    level: 'B1',
    topic: "L'environnement",
    example: 'Les énergies renouvelables se développent.',
    related: ['solaire', 'éolien'],
  },
  recyclage: {
    id: 'recyclage',
    type: 'vocabulary',
    word: 'recyclage',
    meaning: 'recycling',
    partOfSpeech: 'noun (m.)',
    level: 'B1',
    topic: "L'environnement",
    example: 'Le recyclage réduit les déchets.',
    related: ['tri sélectif'],
  },
  dechets: {
    id: 'dechets',
    type: 'vocabulary',
    word: 'déchets',
    meaning: 'waste',
    partOfSpeech: 'noun (m., plural)',
    level: 'B1',
    topic: "L'environnement",
    example: 'Nous produisons trop de déchets.',
    related: ['ordures'],
  },

  'il-vaut-mieux': {
    id: 'il-vaut-mieux',
    type: 'phrase',
    phrase: 'Il vaut mieux',
    meaning: "It's better to",
    function: 'Advice',
    level: 'B1',
    topic: "L'environnement",
    tefUsage: 'Expression orale / écrite — conseil',
    example: 'Il vaut mieux prendre le train que la voiture.',
    related: ['Il est préférable de'],
  },
  'grace-a': {
    id: 'grace-a',
    type: 'phrase',
    phrase: 'Grâce à',
    meaning: 'Thanks to',
    function: 'Explaining a positive cause',
    level: 'B1',
    topic: "L'environnement",
    tefUsage: 'Expression orale / écrite — expliquer une cause',
    example: 'Grâce au recyclage, nous produisons moins de déchets.',
    related: ['À cause de'],
  },
  'dans-le-but-de': {
    id: 'dans-le-but-de',
    type: 'phrase',
    phrase: 'Dans le but de',
    meaning: 'In order to',
    function: 'Stating a purpose',
    level: 'B1',
    topic: "L'environnement",
    tefUsage: 'Expression orale / écrite — exprimer un but',
    example: 'Dans le but de réduire la pollution, la ville a fermé le centre aux voitures.',
    related: ['Afin de'],
  },

  'il-faut': {
    id: 'il-faut',
    type: 'grammar',
    title: 'Il faut + infinitive (obligation)',
    level: 'B1',
    explanation:
      '"Il faut" + infinitive expresses necessity — a classic way to state environmental priorities. It never conjugates for a person: il faut, il faudra, il a fallu.',
    examples: ["Il faut réduire la consommation d'énergie.", 'Il faut protéger les océans.', 'Il faut trier ses déchets.'],
    counterexamples: ['Il faut protégeons les océans. (incorrect — "il faut" takes an infinitive: "il faut protéger")'],
  },
}