// Hand-authored TEF theme unit (spec §3.2.1) — "La famille" (Family). Part of the full TEF theme
// coverage in the Learn path. Exports the same { unit, items } shape as generated units
// (spec §3.2.6). All exercises are tap-only (spec §3.2.2).

export const unit = {
  id: 'famille',
  title: 'La famille',
  description: 'Talk about family life, relationships, and shared responsibilities.',
  lessons: [
    {
      id: 'famille-vocabulaire',
      title: 'Vocabulaire de la famille',
      learningItemIds: ['proches', 'enfance', 'relation', 'retraite'],
      exercises: [
        {
          id: 'fam-1',
          learningItemId: 'proches',
          type: 'multiple_choice',
          stage: 'recognition',
          prompt: 'What does "mes proches" mean?',
          content: { options: ['my close relatives', 'my rivals', 'my coworkers', 'my neighbors'] },
          answer: 'my close relatives',
          explanation: '"Mes proches" are "my close relatives."',
        },
        {
          id: 'fam-2',
          learningItemId: 'retraite',
          type: 'multiple_choice',
          stage: 'recognition',
          prompt: 'What does "la retraite" mean?',
          content: { options: ['retirement', 'a retreat', 'a return', 'a reunion'] },
          answer: 'retirement',
          explanation: '"La retraite" is "retirement."',
        },
        {
          id: 'fam-3',
          learningItemId: 'enfance',
          type: 'translation',
          stage: 'recall',
          prompt: 'Translate: childhood',
          content: { direction: 'en_to_fr', options: ['enfance', 'enfantine', 'enfants', 'année'] },
          answer: 'enfance',
          explanation: '"Childhood" translates to "l\u2019enfance."',
        },
        {
          id: 'fam-4',
          learningItemId: 'relation',
          type: 'translation',
          stage: 'recall',
          prompt: 'Translate: relationship',
          content: { direction: 'en_to_fr', options: ['relation', 'réaction', 'réflexion', 'regret'] },
          answer: 'relation',
          explanation: '"Relationship" translates to "la relation."',
        },
        {
          id: 'fam-5',
          learningItemId: 'proches',
          type: 'fill_blank',
          stage: 'context',
          prompt: 'Complete the sentence',
          content: {
            sentence: 'Je passe le week-end avec mes ______.',
            options: ['proches', 'voisins', 'collègues', 'étrangers'],
          },
          answer: 'proches',
          explanation: '"Mes proches" — the family and friends closest to you.',
        },
        {
          id: 'fam-6',
          learningItemId: 'retraite',
          type: 'fill_blank',
          stage: 'context',
          prompt: 'Complete the sentence',
          content: {
            sentence: 'Mes grands-parents profitent de leur ______.',
            options: ['retraite', 'rentrée', 'vue', 'santé'],
          },
          answer: 'retraite',
          explanation: '"Profiter de sa retraite" = "to enjoy retirement."',
        },
      
        {
          id: 'fam-32',
          learningItemId: 'enfance',
          type: 'multiple_choice',
          stage: 'recognition',
          prompt: 'Which phrase best matches the meaning of "enfance"?',
          content: {"options":["childhood","adulthood","seniority","retirement"]},
          answer: 'childhood',
          explanation: '"Enfance" means "childhood."',
        },
        {
          id: 'fam-33',
          learningItemId: 'enfance',
          type: 'fill_blank',
          stage: 'recall',
          prompt: 'Complete the sentence: "Mon ________ était plein de découvertes."',
          content: {"sentence":"Mon ________ était plein de découvertes.","options":["enfance","relation","proches","retraite"]},
          answer: 'enfance',
          explanation: 'The sentence refers to a period of life, so "enfance" (childhood) is correct.',
        },
        {
          id: 'fam-34',
          learningItemId: 'proches',
          type: 'multiple_choice',
          stage: 'recall',
          prompt: 'What does "mes proches" refer to?',
          content: {"options":["my neighbors","my close relatives","my coworkers","my rivals"]},
          answer: 'my close relatives',
          explanation: '"Mes proches" means "my close relatives."',
        },
        {
          id: 'fam-35',
          learningItemId: 'proches',
          type: 'fill_blank',
          stage: 'completion',
          prompt: 'Complete: "Les ________ de la famille se réunissent chaque Noël."',
          content: {"sentence":"Les ________ de la famille se réunissent chaque Noël.","options":["proches","enfance","relation","retraite"]},
          answer: 'proches',
          explanation: 'It refers to close relatives who gather.',
        },
        {
          id: 'fam-36',
          learningItemId: 'retraite',
          type: 'pronunciation',
          stage: 'production',
          prompt: 'Say the following phrase correctly:',
          content: {"sentence":"Ma retraite est enfin arrivée."},
          answer: 'Ma retraite est enfin arrivée.',
          explanation: 'This sentence uses "retraite" (retirement).',
        },
        {
          id: 'fam-37',
          learningItemId: 'enfance',
          type: 'translation',
          stage: 'context',
          prompt: 'Translate to French: "She cherishes the memories of her childhood in the countryside."',
          content: {"options":["Elle chérit les souvenirs de son enfance à la campagne.","Elle chérit les souvenirs de son retraite à la campagne.","Elle chérit les souvenirs de ses proches à la campagne.","Elle chérit les souvenirs de sa relation à la campagne."]},
          answer: 'Elle chérit les souvenirs de son enfance à la campagne.',
          explanation: 'The correct translation uses "enfance."',
        },
        {
          id: 'fam-38',
          learningItemId: 'retraite',
          type: 'multiple_choice',
          stage: 'recall',
          prompt: 'Which word means "retirement" in French?',
          content: {"options":["retraite","relation","proches","enfance"]},
          answer: 'retraite',
          explanation: '"Retraite" is the French word for "retirement."',
        },
        {
          id: 'fam-39',
          learningItemId: 'proches',
          type: 'fill_blank',
          stage: 'recall',
          prompt: 'Complete: "Les ________ des parents sont souvent très impliqués dans l’éducation des enfants."',
          content: {"sentence":"Les ________ des parents sont souvent très impliqués dans l’éducation des enfants.","options":["proches","enfance","relation","retraite"]},
          answer: 'proches',
          explanation: 'It refers to close relatives involved in childrearing.',
        },
      ],
    },
    {
      id: 'famille-idees',
      title: 'Construire des idées',
      learningItemIds: ['pronoms-cod-coi', 's-occuper-de', 'menage'],
      exercises: [
        {
          id: 'fam-7',
          learningItemId: 'pronoms-cod-coi',
          type: 'multiple_choice',
          stage: 'recognition',
          prompt: 'Which sentence replaces the object correctly?',
          content: { options: ['Je vois ma mère. → Je la vois.', 'Je vois ma mère. → Je lui vois.'] },
          answer: 'Je vois ma mère. → Je la vois.',
          explanation: '"Voir" takes a direct object, so the pronoun is "la," not "lui."',
        },
        {
          id: 'fam-8',
          learningItemId: 'pronoms-cod-coi',
          type: 'fill_blank',
          stage: 'transformation',
          prompt: 'Complete the sentence',
          content: {
            sentence: 'Il téléphone à ses enfants. → Il ______ téléphone souvent.',
            options: ['leur', 'les', 'lui', 'le'],
          },
          answer: 'leur',
          explanation: '"Téléphoner à quelqu\u2019un" takes an indirect object → "leur."',
        },
        {
          id: 'fam-9',
          learningItemId: 's-occuper-de',
          type: 'fill_blank',
          stage: 'context',
          prompt: 'Complete the sentence',
          content: {
            sentence: 'Chacun ______ des tâches ménagères.',
            options: ["s'occupe", 'occupe', "s'occupait", 'occupé'],
          },
          answer: "s'occupe",
          explanation: '"S\u2019occuper de" → "chacun s\u2019occupe" (reflexive third-person singular).',
        },
        {
          id: 'fam-10',
          learningItemId: 's-occuper-de',
          type: 'multiple_choice',
          stage: 'recognition',
          prompt: 'What does "S\u2019occuper de" mean?',
          content: { options: ['To take care of / deal with', 'To wonder about', 'To get rid of', 'To worry about'] },
          answer: 'To take care of / deal with',
          explanation: '"S\u2019occuper de" means "to take care of / deal with."',
        },
        {
          id: 'fam-11',
          learningItemId: 'menage',
          type: 'translation',
          stage: 'recall',
          prompt: 'Translate: household',
          content: { direction: 'en_to_fr', options: ['ménage', 'mer', 'moyenne', 'main'] },
          answer: 'ménage',
          explanation: '"Ménage" can mean both "household" and "housework" ("tâches ménagères").',
        },
        {
          id: 'fam-12',
          learningItemId: 'menage',
          type: 'fill_blank',
          stage: 'context',
          prompt: 'Complete the sentence',
          content: {
            sentence: "Les tâches ______ partagées, c'est plus juste.",
            options: ['ménagères', 'ménagers', 'ménager', 'ménagère'],
          },
          answer: 'ménagères',
          explanation: '"Tâches" is feminine plural, so the adjective is "ménagères."',
        },
      
        {
          id: 'fam-19',
          learningItemId: 'pronoms-cod-coi',
          type: 'multiple_choice',
          stage: 'recognition',
          prompt: 'Which sentence correctly replaces the object in the first person singular?',
          content: {"options":["Je donne le livre à mon frère. → Je le donne à mon frère.","Je donne le livre à mon frère. → Je lui donne le livre.","Je donne le livre à mon frère. → Je leur donne le livre.","Je donne le livre à mon frère. → Je le livre donne à mon frère."]},
          answer: 'Je donne le livre à mon frère. → Je le donne à mon frère.',
          explanation: '"Donner" takes a direct object; the pronoun is "le".',
        },
        {
          id: 'fam-20',
          learningItemId: 'pronoms-cod-coi',
          type: 'fill_blank',
          stage: 'transformation',
          prompt: 'Transform the sentence using the appropriate pronoun (first person plural).',
          content: {"sentence":"Nous envoyons les invitations aux amis. → Nous ______ envoyons aux amis.","options":["leur","les","lui","le"]},
          answer: 'leur',
          explanation: '"Envoyer à quelqu’un" requires an indirect object pronoun: "leur".',
        },
        {
          id: 'fam-21',
          learningItemId: 'pronoms-cod-coi',
          type: 'multiple_choice',
          stage: 'context',
          prompt: 'Choose the correct pronoun to complete the sentence (second person singular).',
          content: {"options":["Je te vois. → Je ______ vois. (direct)","Je t’appelle. → Je ______ appelle. (indirect)","Je te vois. → Je ______ vois. (indirect)","Je t’appelle. → Je ______ appelle. (direct)"]},
          answer: 'Je t’appelle. → Je te appelle. (indirect)',
          explanation: '"Appeler à quelqu’un" uses an indirect object pronoun; "te" is correct.',
        },
        {
          id: 'fam-22',
          learningItemId: 'pronoms-cod-coi',
          type: 'translation',
          stage: 'recall',
          prompt: 'Translate into French, using pronouns where appropriate.',
          content: {"options":["She calls her mother every night.","They give the books to the children.","He sees the dog.","We call them tomorrow."]},
          answer: 'Elle l’appelle chaque soir.',
          explanation: '"Appeler" takes an indirect object; "elle" is subject, "l’appelle" replaces "elle appelle la mère".',
        },
        {
          id: 'fam-23',
          learningItemId: 's-occuper-de',
          type: 'pronunciation',
          stage: 'production',
          prompt: 'Pronounce the full sentence correctly.',
          content: {"sentence":"S'occuper de la maison est important pour la famille."},
          answer: 'S\'occuper de la maison est important pour la famille.',
          explanation: 'Focus on the liaison between "de" and "la" and the nasal sound in "famille."',
        },
        {
          id: 'fam-24',
          learningItemId: 's-occuper-de',
          type: 'multiple_choice',
          stage: 'context',
          prompt: 'What does the phrase "s’occuper de" mean?',
          content: {"options":["To eat","To take care of","To forget","To move"]},
          answer: 'To take care of',
          explanation: 'The phrase literally means "to take care of" or "to deal with."',
        },
        {
          id: 'fam-25',
          learningItemId: 'menage',
          type: 'translation',
          stage: 'recall',
          prompt: 'Translate into French, using "ménage" correctly.',
          content: {"options":["The household chores are shared.","The house is clean.","They have a big house.","The family lives in a small apartment."]},
          answer: 'Les tâches ménagères sont partagées.',
          explanation: 'Use "tâches ménagères" for household chores; "partagées" agrees with "tâches."',
        },
        {
          id: 'fam-26',
          learningItemId: 'pronoms-cod-coi',
          type: 'fill_blank',
          stage: 'transformation',
          prompt: 'Replace the noun with the correct pronoun (third person plural).',
          content: {"sentence":"Ils nettoient le salon. → Ils ______ nettoient le salon.","options":["le","les","lui","leur"]},
          answer: 'les',
          explanation: 'Direct object pronoun for plural masculine or mixed: "les."',
        },
      ],
    },
    {
      id: 'famille-argumenter',
      title: 'Argumenter sur la famille',
      learningItemIds: ['avoir-l-habitude-de', 'c-etait-mieux-avant', 'relation'],
      exercises: [
        {
          id: 'fam-13',
          learningItemId: 'avoir-l-habitude-de',
          type: 'multiple_choice',
          stage: 'recognition',
          prompt: 'What does "Avoir l\u2019habitude de" mean?',
          content: { options: ['To be used to', 'To be allowed to', 'To be willing to', 'To be curious to'] },
          answer: 'To be used to',
          explanation: '"Avoir l\u2019habitude de" = "to be used to / in the habit of."',
        },
        {
          id: 'fam-14',
          learningItemId: 'avoir-l-habitude-de',
          type: 'fill_blank',
          stage: 'context',
          prompt: 'Complete the sentence',
          content: {
            sentence: "On a l'______ de dîner ensemble le dimanche.",
            options: ['habitude', 'habitat', 'amour', 'envie'],
          },
          answer: 'habitude',
          explanation: 'The expression is "avoir l\u2019habitude de" + infinitive.',
        },
        {
          id: 'fam-15',
          learningItemId: 'c-etait-mieux-avant',
          type: 'multiple_choice',
          stage: 'recognition',
          prompt: 'What does "C\u2019était mieux avant" express?',
          content: { options: ['Nostalgia — things were better before', 'A plan for the future', 'A surprise', 'An order'] },
          answer: 'Nostalgia — things were better before',
          explanation: '"C\u2019était mieux avant" is the classic phrase for nostalgia about the past.',
        },
        {
          id: 'fam-16',
          learningItemId: 'c-etait-mieux-avant',
          type: 'fill_blank',
          stage: 'context',
          prompt: 'Complete the sentence',
          content: {
            sentence: 'Mes parents pensent que ______ mieux avant.',
            options: ["c'était", "c'étais", 'cette', "s'était"],
          },
          answer: "c'était",
          explanation: 'The impersonal form is "c\u2019était mieux avant."',
        },
        {
          id: 'fam-17',
          learningItemId: 'pronoms-cod-coi',
          type: 'pronunciation',
          stage: 'production',
          prompt: 'Say the sentence aloud.',
          content: { sentence: 'Je la vois chaque week-end.' },
          answer: 'Je la vois chaque week-end.',
          explanation: 'Direct object pronoun "la" (for "ma mère") goes before the verb.',
        },
        {
          id: 'fam-18',
          learningItemId: 'c-etait-mieux-avant',
          type: 'pronunciation',
          stage: 'production',
          prompt: 'Say the sentence aloud.',
          content: { sentence: "C'était mieux avant." },
          answer: "C'était mieux avant.",
          explanation: '"C\u2019était mieux avant" — the nostalgia phrase, word for word.',
        },
      
        {
          id: 'fam-27',
          learningItemId: 'relation',
          type: 'pronunciation',
          stage: 'completion',
          prompt: 'Pronounce the phrase: "La relation entre parents et enfants est importante."',
          content: {"sentence":"La relation entre parents et enfants est importante."},
          answer: 'La relation entre parents et enfants est importante.',
          explanation: 'Practice saying the sentence with correct French pronunciation.',
        },
        {
          id: 'fam-28',
          learningItemId: 'relation',
          type: 'multiple_choice',
          stage: 'recognition',
          prompt: 'What is the meaning of "relation" in French?',
          content: {"options":["relationship","habit","opinion","friendship"]},
          answer: 'relationship',
          explanation: 'The noun "relation" translates to "relationship."',
        },
        {
          id: 'fam-29',
          learningItemId: 'relation',
          type: 'fill_blank',
          stage: 'recall',
          prompt: 'Choose the correct form: "Les ___ entre les générations sont complexes."',
          content: {"sentence":"Les ___ entre les générations sont complexes.","options":["relations","relation","relationn","relationsn"]},
          answer: 'relations',
          explanation: 'The plural form of "relation" is "relations."',
        },
        {
          id: 'fam-30',
          learningItemId: 'c-etait-mieux-avant',
          type: 'multiple_choice',
          stage: 'recall',
          prompt: 'Which phrase expresses nostalgia about the past?',
          content: {"options":["C'était mieux avant","Avoir l'habitude de","Relation","À l'époque"]},
          answer: 'C\'était mieux avant',
          explanation: 'The expression "c\'était mieux avant" means "it was better before."',
        },
        {
          id: 'fam-31',
          learningItemId: 'relation',
          type: 'pronunciation',
          stage: 'completion',
          prompt: 'Pronounce: "Les relations entre les familles se sont modifiées."',
          content: {"sentence":"Les relations entre les familles se sont modifiées."},
          answer: 'Les relations entre les familles se sont modifiées.',
          explanation: 'Practice the pronunciation of a sentence about changing family relationships.',
        },
      ],
    },
  ],
}

export const items = {
  proches: {
    id: 'proches',
    type: 'vocabulary',
    word: 'proches',
    meaning: 'close relatives',
    partOfSpeech: 'noun (m., plural)',
    level: 'B1',
    topic: 'La famille',
    example: 'Je passe le week-end avec mes proches.',
    related: ['famille', 'amis'],
  },
  enfance: {
    id: 'enfance',
    type: 'vocabulary',
    word: 'enfance',
    meaning: 'childhood',
    partOfSpeech: 'noun (f.)',
    level: 'B1',
    topic: 'La famille',
    example: 'Mon enfance en province reste un bon souvenir.',
    related: ['jeunesse'],
  },
  menage: {
    id: 'menage',
    type: 'vocabulary',
    word: 'ménage',
    meaning: 'household / housework',
    partOfSpeech: 'noun (m.)',
    level: 'B1',
    topic: 'La famille',
    example: "Les tâches ménagères partagées, c'est plus juste.",
    related: ['foyer'],
  },
  retraite: {
    id: 'retraite',
    type: 'vocabulary',
    word: 'retraite',
    meaning: 'retirement',
    partOfSpeech: 'noun (f.)',
    level: 'B1',
    topic: 'La famille',
    example: 'Mes grands-parents profitent de leur retraite.',
    related: ['pension'],
  },
  relation: {
    id: 'relation',
    type: 'vocabulary',
    word: 'relation',
    meaning: 'relationship',
    partOfSpeech: 'noun (f.)',
    level: 'B1',
    topic: 'La famille',
    example: 'Les relations entre générations ont changé.',
    related: ['lien'],
  },

  's-occuper-de': {
    id: 's-occuper-de',
    type: 'phrase',
    phrase: "S'occuper de",
    meaning: 'To take care of / deal with',
    function: 'Describing roles in the family',
    level: 'B1',
    topic: 'La famille',
    tefUsage: 'Expression orale — décrire son quotidien',
    example: "Chacun s'occupe des tâches ménagères.",
    related: ['Prendre soin de'],
    conjugation: {
      je: "Je m'occupe de",
      tu: "Tu t'occupes de",
      ilElle: "Il/Elle s'occupe de",
      nous: "Nous nous occupons de",
      vous: "Vous vous occupez de",
      ilsElles: "Ils/Elles s'occupent de",
    },
  },
  'avoir-l-habitude-de': {
    id: 'avoir-l-habitude-de',
    type: 'phrase',
    phrase: "Avoir l'habitude de",
    meaning: 'To be used to',
    function: 'Habit',
    level: 'B1',
    topic: 'La famille',
    tefUsage: 'Expression orale — décrire des habitudes',
    example: "On a l'habitude de dîner ensemble le dimanche.",
    related: ['Être habitué à'],
    conjugation: {
      je: "J'ai l'habitude de",
      tu: "Tu as l'habitude de",
      ilElle: "Il/Elle a l'habitude de",
      nous: "Nous avons l'habitude de",
      vous: "Vous avez l'habitude de",
      ilsElles: "Ils/Elles ont l'habitude de",
    },
  },
  'c-etait-mieux-avant': {
    id: 'c-etait-mieux-avant',
    type: 'phrase',
    phrase: "C'était mieux avant",
    meaning: 'It was better before',
    function: 'Expressing nostalgia / opinion',
    level: 'B1',
    topic: 'La famille',
    tefUsage: 'Expression orale — opinion',
    example: "Mes parents pensent que c'était mieux avant.",
    related: ["À l'époque"],
  },

  'pronoms-cod-coi': {
    id: 'pronoms-cod-coi',
    type: 'grammar',
    title: 'Object pronouns: le, la, les, lui, leur',
    level: 'B1',
    explanation:
      'Replace direct objects with le/la/les and indirect objects with lui/leur, always placed before the verb.',
    examples: [
      'Je vois ma mère chaque week-end → Je la vois chaque week-end.',
      'Il téléphone à ses enfants → Il leur téléphone.',
    ],
    counterexamples: ['Je lui vois chaque week-end. (incorrect — "voir" takes a direct object, so "je la vois")'],
  },
}