// Hand-authored TEF theme unit (spec §3.2.1) — "La famille" (Family). Part of the full TEF theme
// coverage in the Learn path. Exports the same { unit, items } shape as generated units
// (spec §3.2.6). All exercises are tap-only (spec §3.2.2).

export const unit = {
  id: 'famille',
  title: 'La famille',
  description: 'Talk about family life, relationships, and shared responsibilities.',
  lessons: [
    {
      id: 'famille-vocabulaire',
      title: 'Vocabulaire de la famille',
      learningItemIds: ['proches', 'enfance', 'relation', 'retraite'],
      exercises: [
        {
          id: 'fam-1',
          learningItemId: 'proches',
          type: 'multiple_choice',
          stage: 'recognition',
          prompt: 'What does "mes proches" mean?',
          content: { options: ['my close relatives', 'my rivals', 'my coworkers', 'my neighbors'] },
          answer: 'my close relatives',
          explanation: '"Mes proches" are "my close relatives."',
        },
        {
          id: 'fam-2',
          learningItemId: 'retraite',
          type: 'multiple_choice',
          stage: 'recognition',
          prompt: 'What does "la retraite" mean?',
          content: { options: ['retirement', 'a retreat', 'a return', 'a reunion'] },
          answer: 'retirement',
          explanation: '"La retraite" is "retirement."',
        },
        {
          id: 'fam-3',
          learningItemId: 'enfance',
          type: 'translation',
          stage: 'recall',
          prompt: 'Translate: childhood',
          content: { direction: 'en_to_fr', options: ['enfance', 'enfantine', 'enfants', 'année'] },
          answer: 'enfance',
          explanation: '"Childhood" translates to "l\u2019enfance."',
        },
        {
          id: 'fam-4',
          learningItemId: 'relation',
          type: 'translation',
          stage: 'recall',
          prompt: 'Translate: relationship',
          content: { direction: 'en_to_fr', options: ['relation', 'réaction', 'réflexion', 'regret'] },
          answer: 'relation',
          explanation: '"Relationship" translates to "la relation."',
        },
        {
          id: 'fam-5',
          learningItemId: 'proches',
          type: 'fill_blank',
          stage: 'context',
          prompt: 'Complete the sentence',
          content: {
            sentence: 'Je passe le week-end avec mes ______.',
            options: ['proches', 'voisins', 'collègues', 'étrangers'],
          },
          answer: 'proches',
          explanation: '"Mes proches" — the family and friends closest to you.',
        },
        {
          id: 'fam-6',
          learningItemId: 'retraite',
          type: 'fill_blank',
          stage: 'context',
          prompt: 'Complete the sentence',
          content: {
            sentence: 'Mes grands-parents profitent de leur ______.',
            options: ['retraite', 'rentrée', 'vue', 'santé'],
          },
          answer: 'retraite',
          explanation: '"Profiter de sa retraite" = "to enjoy retirement."',
        },
      ],
    },
    {
      id: 'famille-idees',
      title: 'Construire des idées',
      learningItemIds: ['pronoms-cod-coi', 's-occuper-de', 'menage'],
      exercises: [
        {
          id: 'fam-7',
          learningItemId: 'pronoms-cod-coi',
          type: 'multiple_choice',
          stage: 'recognition',
          prompt: 'Which sentence replaces the object correctly?',
          content: { options: ['Je vois ma mère. → Je la vois.', 'Je vois ma mère. → Je lui vois.'] },
          answer: 'Je vois ma mère. → Je la vois.',
          explanation: '"Voir" takes a direct object, so the pronoun is "la," not "lui."',
        },
        {
          id: 'fam-8',
          learningItemId: 'pronoms-cod-coi',
          type: 'fill_blank',
          stage: 'transformation',
          prompt: 'Complete the sentence',
          content: {
            sentence: 'Il téléphone à ses enfants. → Il ______ téléphone souvent.',
            options: ['leur', 'les', 'lui', 'le'],
          },
          answer: 'leur',
          explanation: '"Téléphoner à quelqu\u2019un" takes an indirect object → "leur."',
        },
        {
          id: 'fam-9',
          learningItemId: 's-occuper-de',
          type: 'fill_blank',
          stage: 'context',
          prompt: 'Complete the sentence',
          content: {
            sentence: 'Chacun ______ des tâches ménagères.',
            options: ["s'occupe", 'occupe', "s'occupait", 'occupé'],
          },
          answer: "s'occupe",
          explanation: '"S\u2019occuper de" → "chacun s\u2019occupe" (reflexive third-person singular).',
        },
        {
          id: 'fam-10',
          learningItemId: 's-occuper-de',
          type: 'multiple_choice',
          stage: 'recognition',
          prompt: 'What does "S\u2019occuper de" mean?',
          content: { options: ['To take care of / deal with', 'To wonder about', 'To get rid of', 'To worry about'] },
          answer: 'To take care of / deal with',
          explanation: '"S\u2019occuper de" means "to take care of / deal with."',
        },
        {
          id: 'fam-11',
          learningItemId: 'menage',
          type: 'translation',
          stage: 'recall',
          prompt: 'Translate: household',
          content: { direction: 'en_to_fr', options: ['ménage', 'mer', 'moyenne', 'main'] },
          answer: 'ménage',
          explanation: '"Ménage" can mean both "household" and "housework" ("tâches ménagères").',
        },
        {
          id: 'fam-12',
          learningItemId: 'menage',
          type: 'fill_blank',
          stage: 'context',
          prompt: 'Complete the sentence',
          content: {
            sentence: "Les tâches ______ partagées, c'est plus juste.",
            options: ['ménagères', 'ménagers', 'ménager', 'ménagère'],
          },
          answer: 'ménagères',
          explanation: '"Tâches" is feminine plural, so the adjective is "ménagères."',
        },
      ],
    },
    {
      id: 'famille-argumenter',
      title: 'Argumenter sur la famille',
      learningItemIds: ['avoir-l-habitude-de', 'c-etait-mieux-avant', 'relation'],
      exercises: [
        {
          id: 'fam-13',
          learningItemId: 'avoir-l-habitude-de',
          type: 'multiple_choice',
          stage: 'recognition',
          prompt: 'What does "Avoir l\u2019habitude de" mean?',
          content: { options: ['To be used to', 'To be allowed to', 'To be willing to', 'To be curious to'] },
          answer: 'To be used to',
          explanation: '"Avoir l\u2019habitude de" = "to be used to / in the habit of."',
        },
        {
          id: 'fam-14',
          learningItemId: 'avoir-l-habitude-de',
          type: 'fill_blank',
          stage: 'context',
          prompt: 'Complete the sentence',
          content: {
            sentence: "On a l'______ de dîner ensemble le dimanche.",
            options: ['habitude', 'habitat', 'amour', 'envie'],
          },
          answer: 'habitude',
          explanation: 'The expression is "avoir l\u2019habitude de" + infinitive.',
        },
        {
          id: 'fam-15',
          learningItemId: 'c-etait-mieux-avant',
          type: 'multiple_choice',
          stage: 'recognition',
          prompt: 'What does "C\u2019était mieux avant" express?',
          content: { options: ['Nostalgia — things were better before', 'A plan for the future', 'A surprise', 'An order'] },
          answer: 'Nostalgia — things were better before',
          explanation: '"C\u2019était mieux avant" is the classic phrase for nostalgia about the past.',
        },
        {
          id: 'fam-16',
          learningItemId: 'c-etait-mieux-avant',
          type: 'fill_blank',
          stage: 'context',
          prompt: 'Complete the sentence',
          content: {
            sentence: 'Mes parents pensent que ______ mieux avant.',
            options: ["c'était", "c'étais", 'cette', "s'était"],
          },
          answer: "c'était",
          explanation: 'The impersonal form is "c\u2019était mieux avant."',
        },
        {
          id: 'fam-17',
          learningItemId: 'pronoms-cod-coi',
          type: 'production',
          stage: 'production',
          prompt: 'Build the sentence: "Je la vois chaque week-end."',
          content: { tiles: ['Je', 'la', 'vois', 'chaque', 'week-end.', 'lui', 'voient'] },
          answer: 'Je la vois chaque week-end.',
          explanation: 'Direct object pronoun "la" (for "ma mère") goes before the verb.',
        },
        {
          id: 'fam-18',
          learningItemId: 'c-etait-mieux-avant',
          type: 'production',
          stage: 'production',
          prompt: 'Build the sentence: "C\u2019était mieux avant."',
          content: { tiles: ["C'était", 'mieux', 'avant.', 'cette', 'meilleur'] },
          answer: "C'était mieux avant.",
          explanation: '"C\u2019était mieux avant" — the nostalgia phrase, word for word.',
        },
      ],
    },
  ],
}

export const items = {
  proches: {
    id: 'proches',
    type: 'vocabulary',
    word: 'proches',
    meaning: 'close relatives',
    partOfSpeech: 'noun (m., plural)',
    level: 'B1',
    topic: 'La famille',
    example: 'Je passe le week-end avec mes proches.',
    related: ['famille', 'amis'],
  },
  enfance: {
    id: 'enfance',
    type: 'vocabulary',
    word: 'enfance',
    meaning: 'childhood',
    partOfSpeech: 'noun (f.)',
    level: 'B1',
    topic: 'La famille',
    example: 'Mon enfance en province reste un bon souvenir.',
    related: ['jeunesse'],
  },
  menage: {
    id: 'menage',
    type: 'vocabulary',
    word: 'ménage',
    meaning: 'household / housework',
    partOfSpeech: 'noun (m.)',
    level: 'B1',
    topic: 'La famille',
    example: "Les tâches ménagères partagées, c'est plus juste.",
    related: ['foyer'],
  },
  retraite: {
    id: 'retraite',
    type: 'vocabulary',
    word: 'retraite',
    meaning: 'retirement',
    partOfSpeech: 'noun (f.)',
    level: 'B1',
    topic: 'La famille',
    example: 'Mes grands-parents profitent de leur retraite.',
    related: ['pension'],
  },
  relation: {
    id: 'relation',
    type: 'vocabulary',
    word: 'relation',
    meaning: 'relationship',
    partOfSpeech: 'noun (f.)',
    level: 'B1',
    topic: 'La famille',
    example: 'Les relations entre générations ont changé.',
    related: ['lien'],
  },

  's-occuper-de': {
    id: 's-occuper-de',
    type: 'phrase',
    phrase: "S'occuper de",
    meaning: 'To take care of / deal with',
    function: 'Describing roles in the family',
    level: 'B1',
    topic: 'La famille',
    tefUsage: 'Expression orale — décrire son quotidien',
    example: "Chacun s'occupe des tâches ménagères.",
    related: ['Prendre soin de'],
  },
  'avoir-l-habitude-de': {
    id: 'avoir-l-habitude-de',
    type: 'phrase',
    phrase: "Avoir l'habitude de",
    meaning: 'To be used to',
    function: 'Habit',
    level: 'B1',
    topic: 'La famille',
    tefUsage: 'Expression orale — décrire des habitudes',
    example: "On a l'habitude de dîner ensemble le dimanche.",
    related: ['Être habitué à'],
  },
  'c-etait-mieux-avant': {
    id: 'c-etait-mieux-avant',
    type: 'phrase',
    phrase: "C'était mieux avant",
    meaning: 'It was better before',
    function: 'Expressing nostalgia / opinion',
    level: 'B1',
    topic: 'La famille',
    tefUsage: 'Expression orale — opinion',
    example: "Mes parents pensent que c'était mieux avant.",
    related: ["À l'époque"],
  },

  'pronoms-cod-coi': {
    id: 'pronoms-cod-coi',
    type: 'grammar',
    title: 'Object pronouns: le, la, les, lui, leur',
    level: 'B1',
    explanation:
      'Replace direct objects with le/la/les and indirect objects with lui/leur, always placed before the verb.',
    examples: [
      'Je vois ma mère chaque week-end → Je la vois chaque week-end.',
      'Il téléphone à ses enfants → Il leur téléphone.',
    ],
    counterexamples: ['Je lui vois chaque week-end. (incorrect — "voir" takes a direct object, so "je la vois")'],
  },
}