// Hand-authored TEF theme unit (spec §3.2.1) — "Les médias" (Media). Part of the full TEF theme
// coverage in the Learn path. Exports the same { unit, items } shape as generated units
// (spec §3.2.6). All exercises are tap-only (spec §3.2.2).

export const unit = {
  id: 'medias',
  title: 'Les médias',
  description: 'Report, react to, and evaluate news and media in French.',
  lessons: [
    {
      id: 'medias-vocabulaire',
      title: 'Vocabulaire des médias',
      learningItemIds: ['presse', 'information', 'actualite', 'publicite'],
      exercises: [
        {
          id: 'med-1',
          learningItemId: 'presse',
          type: 'multiple_choice',
          stage: 'recognition',
          prompt: 'What does "la presse" mean?',
          content: { options: ['the press (newspapers)', 'a printer', 'a parade', 'a pressure cooker'] },
          answer: 'the press (newspapers)',
          explanation: '"La presse" is "the press" — newspapers and journalism.',
        },
        {
          id: 'med-2',
          learningItemId: 'publicite',
          type: 'multiple_choice',
          stage: 'recognition',
          prompt: 'What does "la publicité" mean?',
          content: { options: ['advertising', 'a publicity stunt', 'public space', 'publishing'] },
          answer: 'advertising',
          explanation: '"La publicité" is "advertising."',
        },
        {
          id: 'med-3',
          learningItemId: 'actualite',
          type: 'translation',
          stage: 'recall',
          prompt: 'Translate: current events',
          content: { direction: 'en_to_fr', options: ['actualité', 'actualisation', 'actuariat', 'action'] },
          answer: 'actualité',
          explanation: '"Current events" translates to "l\u2019actualité."',
        },
        {
          id: 'med-4',
          learningItemId: 'info-journaliste',
          type: 'translation',
          stage: 'recall',
          prompt: 'Translate: journalist',
          content: { direction: 'en_to_fr', options: ['journaliste', 'touriste', 'juriste', 'journal'] },
          answer: 'journaliste',
          explanation: '"Journalist" translates to "journaliste."',
        },
        {
          id: 'med-5',
          learningItemId: 'actualite',
          type: 'fill_blank',
          stage: 'context',
          prompt: 'Complete the sentence',
          content: {
            sentence: "Je suis l'______ chaque matin.",
            options: ['actualité', 'activité', 'océan', 'occasion'],
          },
          answer: 'actualité',
          explanation: '"Suivre l\u2019actualité" means "to follow the news."',
        },
        {
          id: 'med-6',
          learningItemId: 'publicite',
          type: 'fill_blank',
          stage: 'context',
          prompt: 'Complete the sentence',
          content: {
            sentence: 'La ______ influence nos choix.',
            options: ['publicité', 'politique', 'peinture', 'pauvreté'],
          },
          answer: 'publicité',
          explanation: '"La publicité" — advertising — influences our choices.',
        },
      
        {
          id: 'med-23',
          learningItemId: 'presse',
          type: 'fill_blank',
          stage: 'recall',
          prompt: 'Complete the sentence: La ____ joue un rôle essentiel en démocratie.',
          content: {"sentence":"La ____ joue un rôle essentiel en démocratie.","options":["presse","information","actualité","publicité"]},
          answer: 'presse',
          explanation: 'The blank should be filled with "presse" (the press).',
        },
        {
          id: 'med-24',
          learningItemId: 'information',
          type: 'multiple_choice',
          stage: 'context',
          prompt: 'Which sentence uses "information" correctly?',
          content: {"options":["Je lis l'information chaque matin.","Je regarde la presse chaque soir.","Je écoute la publicité sur la radio.","Je visite l'actualité de mon village."]},
          answer: 'Je lis l\'information chaque matin.',
          explanation: '"Information" refers to news or data, so the correct sentence is "Je lis l\'information chaque matin."',
        },
        {
          id: 'med-25',
          learningItemId: 'publicite',
          type: 'pronunciation',
          stage: 'production',
          prompt: 'Say this phrase aloud:',
          content: {"sentence":"La publicité influence nos choix."},
          answer: 'La publicité influence nos choix.',
          explanation: 'Practice the pronunciation of the full sentence.',
        },
        {
          id: 'med-26',
          learningItemId: 'presse',
          type: 'multiple_choice',
          stage: 'recall',
          prompt: 'What does "la presse" refer to?',
          content: {"options":["the printing press","the press (newspapers)","the press conference","the pressurized container"]},
          answer: 'the press (newspapers)',
          explanation: '"La presse" means newspapers and journalism.',
        },
        {
          id: 'med-27',
          learningItemId: 'information',
          type: 'fill_blank',
          stage: 'completion',
          prompt: 'Complete: Les nouvelles de la ____ sont souvent vérifiées.',
          content: {"sentence":"Les nouvelles de la ____ sont souvent vérifiées.","options":["presse","information","actualité","publicité"]},
          answer: 'information',
          explanation: 'The phrase "les nouvelles de l\'information" means news that is often verified.',
        },
        {
          id: 'med-28',
          learningItemId: 'publicite',
          type: 'translation',
          stage: 'recall',
          prompt: 'Translate to French: "Advertising"',
          content: {"options":["la presse","l'information","l'actualité","la publicité"]},
          answer: 'la publicité',
          explanation: 'The French word for "advertising" is "publicité."',
        },
        {
          id: 'med-29',
          learningItemId: 'presse',
          type: 'multiple_choice',
          stage: 'context',
          prompt: 'Choose the correct meaning of "la presse":',
          content: {"options":["the press (newspapers)","the printing machine","the press conference","the pressurized tank"]},
          answer: 'the press (newspapers)',
          explanation: '"La presse" refers to newspapers and journalism.',
        },
        {
          id: 'med-30',
          learningItemId: 'publicite',
          type: 'fill_blank',
          stage: 'completion',
          prompt: 'Complete: La ____ influence nos décisions d\'achat.',
          content: {"sentence":"La ____ influence nos décisions d'achat.","options":["presse","information","actualité","publicité"]},
          answer: 'publicité',
          explanation: 'The blank should be "publicité" (advertising).',
        },
      ],
    },
    {
      id: 'medias-idees',
      title: 'Construire des idées',
      learningItemIds: ['discours-indirect', 'd-apres', 'source'],
      exercises: [
        {
          id: 'med-7',
          learningItemId: 'discours-indirect',
          type: 'multiple_choice',
          stage: 'recognition',
          prompt: 'Which sentence correctly reports what was said?',
          content: {
            options: [
              'Le ministre a annoncé que les inscriptions augmentent.',
              'Le ministre a annoncé que les inscriptions augmentera.',
            ],
          },
          answer: 'Le ministre a annoncé que les inscriptions augmentent.',
          explanation: 'A "que" clause needs a correctly-conjugated verb in its own tense.',
        },
        {
          id: 'med-8',
          learningItemId: 'discours-indirect',
          type: 'fill_blank',
          stage: 'context',
          prompt: 'Complete the sentence',
          content: {
            sentence: 'Le ministre a ______ que les inscriptions augmentent.',
            options: ['annoncé', 'annoncée', 'annoncer', 'annonce'],
          },
          answer: 'annoncé',
          explanation: 'The participle of "annoncer" is "annoncé" (invariable with avoir).',
        },
        {
          id: 'med-9',
          learningItemId: 'd-apres',
          type: 'multiple_choice',
          stage: 'recognition',
          prompt: 'What does "D\u2019après" mean?',
          content: { options: ['According to', 'In spite of', 'In front of', 'Beyond'] },
          answer: 'According to',
          explanation: '"D\u2019après" means "according to" — standard when citing a source.',
        },
        {
          id: 'med-10',
          learningItemId: 'd-apres',
          type: 'fill_blank',
          stage: 'context',
          prompt: 'Complete the sentence',
          content: {
            sentence: "______ cette étude, les jeunes passent plus de temps en ligne.",
            options: ["D'après", 'Depuis', 'Dehors', "D'avance"],
          },
          answer: "D'après",
          explanation: '"D\u2019après cette étude" — according to this study.',
        },
        {
          id: 'med-11',
          learningItemId: 'd-apres',
          type: 'translation',
          stage: 'recall',
          prompt: 'Translate: according to',
          content: { direction: 'en_to_fr', options: ["d'après", 'à part', 'après', 'dès que'] },
          answer: "d'après",
          explanation: '"According to" translates to "d\u2019après" / "selon."',
        },
        {
          id: 'med-12',
          learningItemId: 'source',
          type: 'fill_blank',
          stage: 'context',
          prompt: 'Complete the sentence',
          content: {
            sentence: 'Le journaliste doit vérifier ses ______.',
            options: ['sources', 'sous', 'soupe', 'sauces'],
          },
          answer: 'sources',
          explanation: '"Vérifier ses sources" — a journalist must check sources.',
        },
      
        {
          id: 'med-19',
          learningItemId: 'd-apres',
          type: 'translation',
          stage: 'recall',
          prompt: 'Translate into French: "According to the report, the economy will improve."',
          content: {"options":["D'après le rapport, l'économie va s'améliorer.","Selon le rapport, l'économie va s'améliorer.","D'après le rapport, l'économie s'améliorera.","Selon le rapport, l'économie s'améliorera."]},
          answer: 'D\'après le rapport, l\'économie s\'améliorera.',
          explanation: 'Both D\'après and Selon can be used; here we choose D\'après.',
        },
        {
          id: 'med-20',
          learningItemId: 'source',
          type: 'multiple_choice',
          stage: 'context',
          prompt: 'Select the correct translation of "source" in a media context.',
          content: {"options":["référence","origine","source","information"]},
          answer: 'source',
          explanation: 'In media, "source" refers to the origin of information.',
        },
        {
          id: 'med-21',
          learningItemId: 'd-apres',
          type: 'pronunciation',
          stage: 'production',
          prompt: 'Pronounce the phrase correctly.',
          content: {"sentence":"D'après cette source, les chiffres sont fiables."},
          answer: 'D\'après cette source, les chiffres sont fiables.',
          explanation: 'Listen for the liaison between D\'après and cette.',
        },
        {
          id: 'med-22',
          learningItemId: 'source',
          type: 'multiple_choice',
          stage: 'transformation',
          prompt: 'Rewrite the sentence using "source" instead of "d\'après": "D\'après la presse, la réunion est reportée."',
          content: {"options":["La source de la presse indique que la réunion est reportée.","Selon la presse, la réunion est reportée.","D'après la presse, la réunion est reportée.","La presse source indique que la réunion est reportée."]},
          answer: 'D\'après la presse, la réunion est reportée.',
          explanation: 'The phrase remains the same; "source" is a noun, not a preposition.',
        },
      ],
    },
    {
      id: 'medias-argumenter',
      title: 'Argumenter sur les médias',
      learningItemIds: ['il-s-agit-de', 'a-la-une'],
      exercises: [
        {
          id: 'med-13',
          learningItemId: 'il-s-agit-de',
          type: 'multiple_choice',
          stage: 'recognition',
          prompt: 'What does "Il s\u2019agit de" mean?',
          content: { options: ["It's about / it concerns", "It's important to", "It happens that", "It depends on"] },
          answer: "It's about / it concerns",
          explanation: '"Il s\u2019agit de" means "it\u2019s about / it concerns."',
        },
        {
          id: 'med-14',
          learningItemId: 'il-s-agit-de',
          type: 'fill_blank',
          stage: 'context',
          prompt: 'Complete the sentence',
          content: {
            sentence: "Il ______ d'un sujet complexe.",
            options: ["s'agit", 'agis', 'sait', 'fait'],
          },
          answer: "s'agit",
          explanation: 'The fixed form is "il s\u2019agit de."',
        },
        {
          id: 'med-15',
          learningItemId: 'a-la-une',
          type: 'multiple_choice',
          stage: 'recognition',
          prompt: 'What does "Faire la une" mean?',
          content: { options: ['To make the headlines', 'To be first in line', 'To move up one rank', 'To make a fuss'] },
          answer: 'To make the headlines',
          explanation: '"Faire la une" = "to make the headlines."',
        },
        {
          id: 'med-16',
          learningItemId: 'a-la-une',
          type: 'fill_blank',
          stage: 'context',
          prompt: 'Complete the sentence',
          content: {
            sentence: 'Cette affaire fait la ______ des journaux.',
            options: ['une', 'un', 'heure', 'marche'],
          },
          answer: 'une',
          explanation: '"La une" is the front page — "faire la une" means to be the headline.',
        },
        {
          id: 'med-17',
          learningItemId: 'info-journaliste',
          type: 'pronunciation',
          stage: 'production',
          prompt: 'Say the sentence aloud.',
          content: { sentence: "L'information doit être vérifiée." },
          answer: "L'information doit être vérifiée.",
          explanation: '"L\u2019information" + "devoir être" + past participle.',
        },
        {
          id: 'med-18',
          learningItemId: 'a-la-une',
          type: 'pronunciation',
          stage: 'production',
          prompt: 'Say the sentence aloud.',
          content: { sentence: 'Cette affaire fait la une des journaux.' },
          answer: 'Cette affaire fait la une des journaux.',
          explanation: '"Faire la une" — subject + "fait la une des journaux."',
        },
      
        {
          id: 'med-31',
          learningItemId: 'il-s-agit-de',
          type: 'multiple_choice',
          stage: 'recognition',
          prompt: 'Which phrase means "to be about" in French?',
          content: {"options":["Il s’agit de","Il fait la une","Il est question de","Il est important de"]},
          answer: 'Il s’agit de',
          explanation: '"Il s’agit de" means "to be about" or "it concerns."',
        },
        {
          id: 'med-32',
          learningItemId: 'il-s-agit-de',
          type: 'fill_blank',
          stage: 'recall',
          prompt: 'Translate into French: "It is about the new policy."',
          content: {"sentence":"Il ______ la nouvelle politique.","options":["s’agit de","fait la une","est question de","est important de"]},
          answer: 's’agit de',
          explanation: 'The correct expression is "Il s’agit de la nouvelle politique."',
        },
        {
          id: 'med-33',
          learningItemId: 'a-la-une',
          type: 'translation',
          stage: 'context',
          prompt: 'Translate: "This issue makes the headlines in the newspapers."',
          content: {"options":["Cette affaire fait la une des journaux.","Cette affaire est la une des journaux.","Cette affaire est dans la une des journaux.","Cette affaire fait la une dans les journaux."]},
          answer: 'Cette affaire fait la une des journaux.',
          explanation: 'The correct translation uses "fait la une."',
        },
        {
          id: 'med-34',
          learningItemId: 'il-s-agit-de',
          type: 'pronunciation',
          stage: 'recall',
          prompt: 'Pronounce the following sentence correctly:',
          content: {"sentence":"Il s’agit de la nouvelle réforme."},
          answer: 'Il s’agit de la nouvelle réforme.',
          explanation: 'Practice the correct pronunciation of "Il s’agit de."',
        },
        {
          id: 'med-35',
          learningItemId: 'il-s-agit-de',
          type: 'multiple_choice',
          stage: 'context',
          prompt: 'Choose the correct form to complete: "Il s’_____ de la crise économique."',
          content: {"options":["agisse","agit","s'agis","s'agit"]},
          answer: 's\'agit',
          explanation: 'The fixed expression is "Il s’agit de."',
        },
        {
          id: 'med-36',
          learningItemId: 'a-la-une',
          type: 'fill_blank',
          stage: 'recall',
          prompt: 'Complete the sentence: "Cette affaire ___ la une des journaux."',
          content: {"sentence":"Cette affaire ______ la une des journaux.","options":["fait","fait la une","est la une","fait la une des"]},
          answer: 'fait',
          explanation: 'The correct verb is "fait."',
        },
        {
          id: 'med-37',
          learningItemId: 'il-s-agit-de',
          type: 'translation',
          stage: 'recall',
          prompt: 'Translate: "It is about the new election."',
          content: {"options":["Il s’agit de la nouvelle élection.","Il fait la une de la nouvelle élection.","Il est question de la nouvelle élection.","Il est important de la nouvelle élection."]},
          answer: 'Il s’agit de la nouvelle élection.',
          explanation: 'Use "Il s’agit de."',
        },
        {
          id: 'med-38',
          learningItemId: 'a-la-une',
          type: 'multiple_choice',
          stage: 'recall',
          prompt: 'Which sentence uses "faire la une" correctly?',
          content: {"options":["Le journal fait la une du président.","Le président fait la une du journal.","Le journal fait la une des journaux.","Le président fait la une des journaux."]},
          answer: 'Le journal fait la une des journaux.',
          explanation: 'The headline is made by the newspaper.',
        },
        {
          id: 'med-39',
          learningItemId: 'il-s-agit-de',
          type: 'pronunciation',
          stage: 'recall',
          prompt: 'Say the following phrase:',
          content: {"sentence":"Il s’agit d’un sujet complexe."},
          answer: 'Il s’agit d’un sujet complexe.',
          explanation: 'Practice the pronunciation of "Il s’agit d’un sujet complexe."',
        },
        {
          id: 'med-40',
          learningItemId: 'a-la-une',
          type: 'fill_blank',
          stage: 'recall',
          prompt: 'Complete: "Le reportage ___ la une du soir."',
          content: {"sentence":"Le reportage ______ la une du soir.","options":["fait","fait la une","est la une","fait la une du"]},
          answer: 'fait la une',
          explanation: 'The correct expression is "fait la une."',
        },
      ],
    },
  ],
}

export const items = {
  presse: {
    id: 'presse',
    type: 'vocabulary',
    word: 'presse',
    meaning: 'press / newspapers',
    partOfSpeech: 'noun (f.)',
    level: 'B1',
    topic: 'Les médias',
    example: 'La presse joue un rôle essentiel en démocratie.',
    related: ['journaux', 'médias'],
  },
  actualite: {
    id: 'actualite',
    type: 'vocabulary',
    word: 'actualité',
    meaning: 'current events / news',
    partOfSpeech: 'noun (f.)',
    level: 'B1',
    topic: 'Les médias',
    example: "Je suis l'actualité chaque matin.",
    related: ['nouvelles'],
  },
  information: {
    id: 'information',
    type: 'vocabulary',
    word: 'information',
    meaning: 'information / news report',
    partOfSpeech: 'noun (f.)',
    level: 'B1',
    topic: 'Les médias',
    example: "L'information doit être vérifiée.",
    related: ['nouvelle'],
  },
  'info-journaliste': {
    id: 'info-journaliste',
    type: 'vocabulary',
    word: 'journaliste',
    meaning: 'journalist',
    partOfSpeech: 'noun (m./f.)',
    level: 'B1',
    topic: 'Les médias',
    example: 'Le journaliste doit vérifier ses sources.',
    related: ['reporteur'],
  },
  publicite: {
    id: 'publicite',
    type: 'vocabulary',
    word: 'publicité',
    meaning: 'advertising',
    partOfSpeech: 'noun (f.)',
    level: 'B1',
    topic: 'Les médias',
    example: 'La publicité influence nos choix.',
    related: ['pub', 'annonce'],
  },
  source: {
    id: 'source',
    type: 'vocabulary',
    word: 'source',
    meaning: 'source',
    partOfSpeech: 'noun (f.)',
    level: 'B1',
    topic: 'Les médias',
    example: 'Le journaliste doit vérifier ses sources.',
    related: ['référence'],
  },

  'd-apres': {
    id: 'd-apres',
    type: 'phrase',
    phrase: "D'après",
    meaning: 'According to',
    function: 'Citing a source',
    level: 'B1',
    topic: 'Les médias',
    tefUsage: 'Expression orale / écrite — citer une source',
    example: "D'après cette étude, les jeunes passent plus de temps en ligne.",
    related: ['Selon'],
  },
  'il-s-agit-de': {
    id: 'il-s-agit-de',
    type: 'phrase',
    phrase: "Il s'agit de",
    meaning: "It's about / it concerns",
    function: 'Describing the subject',
    level: 'B1',
    topic: 'Les médias',
    tefUsage: 'Expression orale — présenter un sujet',
    example: "Il s'agit d'un sujet complexe.",
    related: ['Il est question de'],
  },
  'a-la-une': {
    id: 'a-la-une',
    type: 'phrase',
    phrase: 'Faire la une',
    meaning: 'To make the headlines',
    function: 'Headlines',
    level: 'B1',
    topic: 'Les médias',
    tefUsage: 'Expression orale — commenter l\u2019actualité',
    example: 'Cette affaire fait la une des journaux.',
    related: ['Faire les gros titres'],
    conjugation: {
      je: 'fais la une',
      tu: 'fais la une',
      ilElle: 'fait la une',
      nous: 'faisons la une',
      vous: 'faites la une',
      ilsElles: 'font la une',
    },
  },

  'discours-indirect': {
    id: 'discours-indirect',
    type: 'grammar',
    title: 'Reported speech: il a dit que…',
    level: 'B1',
    explanation:
      'Report what someone said with il a dit que / elle a annoncé que + a clause using its own correctly-conjugated verb.',
    examples: [
      'Le ministre a annoncé que les inscriptions augmentent.',
      "Les journalistes ont dit que l'enquête continue.",
    ],
    counterexamples: [
      'Le ministre a annoncé que les inscriptions augmentera. (incorrect — the que-clause needs a correctly-conjugated verb: "augmenteront")',
    ],
  },
}