// Hand-authored TEF theme unit (spec §3.2.1) — "Les médias" (Media). Part of the full TEF theme
// coverage in the Learn path. Exports the same { unit, items } shape as generated units
// (spec §3.2.6). All exercises are tap-only (spec §3.2.2).

export const unit = {
  id: 'medias',
  title: 'Les médias',
  description: 'Report, react to, and evaluate news and media in French.',
  lessons: [
    {
      id: 'medias-vocabulaire',
      title: 'Vocabulaire des médias',
      learningItemIds: ['presse', 'information', 'actualite', 'publicite'],
      exercises: [
        {
          id: 'med-1',
          learningItemId: 'presse',
          type: 'multiple_choice',
          stage: 'recognition',
          prompt: 'What does "la presse" mean?',
          content: { options: ['the press (newspapers)', 'a printer', 'a parade', 'a pressure cooker'] },
          answer: 'the press (newspapers)',
          explanation: '"La presse" is "the press" — newspapers and journalism.',
        },
        {
          id: 'med-2',
          learningItemId: 'publicite',
          type: 'multiple_choice',
          stage: 'recognition',
          prompt: 'What does "la publicité" mean?',
          content: { options: ['advertising', 'a publicity stunt', 'public space', 'publishing'] },
          answer: 'advertising',
          explanation: '"La publicité" is "advertising."',
        },
        {
          id: 'med-3',
          learningItemId: 'actualite',
          type: 'translation',
          stage: 'recall',
          prompt: 'Translate: current events',
          content: { direction: 'en_to_fr', options: ['actualité', 'actualisation', 'actuariat', 'action'] },
          answer: 'actualité',
          explanation: '"Current events" translates to "l\u2019actualité."',
        },
        {
          id: 'med-4',
          learningItemId: 'info-journaliste',
          type: 'translation',
          stage: 'recall',
          prompt: 'Translate: journalist',
          content: { direction: 'en_to_fr', options: ['journaliste', 'touriste', 'juriste', 'journal'] },
          answer: 'journaliste',
          explanation: '"Journalist" translates to "journaliste."',
        },
        {
          id: 'med-5',
          learningItemId: 'actualite',
          type: 'fill_blank',
          stage: 'context',
          prompt: 'Complete the sentence',
          content: {
            sentence: "Je suis l'______ chaque matin.",
            options: ['actualité', 'activité', 'océan', 'occasion'],
          },
          answer: 'actualité',
          explanation: '"Suivre l\u2019actualité" means "to follow the news."',
        },
        {
          id: 'med-6',
          learningItemId: 'publicite',
          type: 'fill_blank',
          stage: 'context',
          prompt: 'Complete the sentence',
          content: {
            sentence: 'La ______ influence nos choix.',
            options: ['publicité', 'politique', 'peinture', 'pauvreté'],
          },
          answer: 'publicité',
          explanation: '"La publicité" — advertising — influences our choices.',
        },
      ],
    },
    {
      id: 'medias-idees',
      title: 'Construire des idées',
      learningItemIds: ['discours-indirect', 'd-apres', 'source'],
      exercises: [
        {
          id: 'med-7',
          learningItemId: 'discours-indirect',
          type: 'multiple_choice',
          stage: 'recognition',
          prompt: 'Which sentence correctly reports what was said?',
          content: {
            options: [
              'Le ministre a annoncé que les inscriptions augmentent.',
              'Le ministre a annoncé que les inscriptions augmentera.',
            ],
          },
          answer: 'Le ministre a annoncé que les inscriptions augmentent.',
          explanation: 'A "que" clause needs a correctly-conjugated verb in its own tense.',
        },
        {
          id: 'med-8',
          learningItemId: 'discours-indirect',
          type: 'fill_blank',
          stage: 'context',
          prompt: 'Complete the sentence',
          content: {
            sentence: 'Le ministre a ______ que les inscriptions augmentent.',
            options: ['annoncé', 'annoncée', 'annoncer', 'annonce'],
          },
          answer: 'annoncé',
          explanation: 'The participle of "annoncer" is "annoncé" (invariable with avoir).',
        },
        {
          id: 'med-9',
          learningItemId: 'd-apres',
          type: 'multiple_choice',
          stage: 'recognition',
          prompt: 'What does "D\u2019après" mean?',
          content: { options: ['According to', 'In spite of', 'In front of', 'Beyond'] },
          answer: 'According to',
          explanation: '"D\u2019après" means "according to" — standard when citing a source.',
        },
        {
          id: 'med-10',
          learningItemId: 'd-apres',
          type: 'fill_blank',
          stage: 'context',
          prompt: 'Complete the sentence',
          content: {
            sentence: "______ cette étude, les jeunes passent plus de temps en ligne.",
            options: ["D'après", 'Depuis', 'Dehors', "D'avance"],
          },
          answer: "D'après",
          explanation: '"D\u2019après cette étude" — according to this study.',
        },
        {
          id: 'med-11',
          learningItemId: 'd-apres',
          type: 'translation',
          stage: 'recall',
          prompt: 'Translate: according to',
          content: { direction: 'en_to_fr', options: ["d'après", 'à part', 'après', 'dès que'] },
          answer: "d'après",
          explanation: '"According to" translates to "d\u2019après" / "selon."',
        },
        {
          id: 'med-12',
          learningItemId: 'source',
          type: 'fill_blank',
          stage: 'context',
          prompt: 'Complete the sentence',
          content: {
            sentence: 'Le journaliste doit vérifier ses ______.',
            options: ['sources', 'sous', 'soupe', 'sauces'],
          },
          answer: 'sources',
          explanation: '"Vérifier ses sources" — a journalist must check sources.',
        },
      ],
    },
    {
      id: 'medias-argumenter',
      title: 'Argumenter sur les médias',
      learningItemIds: ['il-s-agit-de', 'a-la-une'],
      exercises: [
        {
          id: 'med-13',
          learningItemId: 'il-s-agit-de',
          type: 'multiple_choice',
          stage: 'recognition',
          prompt: 'What does "Il s\u2019agit de" mean?',
          content: { options: ["It's about / it concerns", "It's important to", "It happens that", "It depends on"] },
          answer: "It's about / it concerns",
          explanation: '"Il s\u2019agit de" means "it\u2019s about / it concerns."',
        },
        {
          id: 'med-14',
          learningItemId: 'il-s-agit-de',
          type: 'fill_blank',
          stage: 'context',
          prompt: 'Complete the sentence',
          content: {
            sentence: "Il ______ d'un sujet complexe.",
            options: ["s'agit", 'agis', 'sait', 'fait'],
          },
          answer: "s'agit",
          explanation: 'The fixed form is "il s\u2019agit de."',
        },
        {
          id: 'med-15',
          learningItemId: 'a-la-une',
          type: 'multiple_choice',
          stage: 'recognition',
          prompt: 'What does "Faire la une" mean?',
          content: { options: ['To make the headlines', 'To be first in line', 'To move up one rank', 'To make a fuss'] },
          answer: 'To make the headlines',
          explanation: '"Faire la une" = "to make the headlines."',
        },
        {
          id: 'med-16',
          learningItemId: 'a-la-une',
          type: 'fill_blank',
          stage: 'context',
          prompt: 'Complete the sentence',
          content: {
            sentence: 'Cette affaire fait la ______ des journaux.',
            options: ['une', 'un', 'heure', 'marche'],
          },
          answer: 'une',
          explanation: '"La une" is the front page — "faire la une" means to be the headline.',
        },
        {
          id: 'med-17',
          learningItemId: 'info-journaliste',
          type: 'production',
          stage: 'production',
          prompt: 'Build the sentence: "L\u2019information doit être vérifiée."',
          content: { tiles: ["L'information", 'doit', 'être', 'vérifiée.', 'est', 'incertaine'] },
          answer: "L'information doit être vérifiée.",
          explanation: '"L\u2019information" + "devoir être" + past participle.',
        },
        {
          id: 'med-18',
          learningItemId: 'a-la-une',
          type: 'production',
          stage: 'production',
          prompt: 'Build the sentence: "Cette affaire fait la une des journaux."',
          content: { tiles: ['Cette', 'affaire', 'fait', 'la', 'une', 'des', 'journaux.', 'est', 'presse'] },
          answer: 'Cette affaire fait la une des journaux.',
          explanation: '"Faire la une" — subject + "fait la une des journaux."',
        },
      ],
    },
  ],
}

export const items = {
  presse: {
    id: 'presse',
    type: 'vocabulary',
    word: 'presse',
    meaning: 'press / newspapers',
    partOfSpeech: 'noun (f.)',
    level: 'B1',
    topic: 'Les médias',
    example: 'La presse joue un rôle essentiel en démocratie.',
    related: ['journaux', 'médias'],
  },
  actualite: {
    id: 'actualite',
    type: 'vocabulary',
    word: 'actualité',
    meaning: 'current events / news',
    partOfSpeech: 'noun (f.)',
    level: 'B1',
    topic: 'Les médias',
    example: "Je suis l'actualité chaque matin.",
    related: ['nouvelles'],
  },
  information: {
    id: 'information',
    type: 'vocabulary',
    word: 'information',
    meaning: 'information / news report',
    partOfSpeech: 'noun (f.)',
    level: 'B1',
    topic: 'Les médias',
    example: "L'information doit être vérifiée.",
    related: ['nouvelle'],
  },
  'info-journaliste': {
    id: 'info-journaliste',
    type: 'vocabulary',
    word: 'journaliste',
    meaning: 'journalist',
    partOfSpeech: 'noun (m./f.)',
    level: 'B1',
    topic: 'Les médias',
    example: 'Le journaliste doit vérifier ses sources.',
    related: ['reporteur'],
  },
  publicite: {
    id: 'publicite',
    type: 'vocabulary',
    word: 'publicité',
    meaning: 'advertising',
    partOfSpeech: 'noun (f.)',
    level: 'B1',
    topic: 'Les médias',
    example: 'La publicité influence nos choix.',
    related: ['pub', 'annonce'],
  },
  source: {
    id: 'source',
    type: 'vocabulary',
    word: 'source',
    meaning: 'source',
    partOfSpeech: 'noun (f.)',
    level: 'B1',
    topic: 'Les médias',
    example: 'Le journaliste doit vérifier ses sources.',
    related: ['référence'],
  },

  'd-apres': {
    id: 'd-apres',
    type: 'phrase',
    phrase: "D'après",
    meaning: 'According to',
    function: 'Citing a source',
    level: 'B1',
    topic: 'Les médias',
    tefUsage: 'Expression orale / écrite — citer une source',
    example: "D'après cette étude, les jeunes passent plus de temps en ligne.",
    related: ['Selon'],
  },
  'il-s-agit-de': {
    id: 'il-s-agit-de',
    type: 'phrase',
    phrase: "Il s'agit de",
    meaning: "It's about / it concerns",
    function: 'Describing the subject',
    level: 'B1',
    topic: 'Les médias',
    tefUsage: 'Expression orale — présenter un sujet',
    example: "Il s'agit d'un sujet complexe.",
    related: ['Il est question de'],
  },
  'a-la-une': {
    id: 'a-la-une',
    type: 'phrase',
    phrase: 'Faire la une',
    meaning: 'To make the headlines',
    function: 'Headlines',
    level: 'B1',
    topic: 'Les médias',
    tefUsage: 'Expression orale — commenter l\u2019actualité',
    example: 'Cette affaire fait la une des journaux.',
    related: ['Faire les gros titres'],
  },

  'discours-indirect': {
    id: 'discours-indirect',
    type: 'grammar',
    title: 'Reported speech: il a dit que…',
    level: 'B1',
    explanation:
      'Report what someone said with il a dit que / elle a annoncé que + a clause using its own correctly-conjugated verb.',
    examples: [
      'Le ministre a annoncé que les inscriptions augmentent.',
      "Les journalistes ont dit que l'enquête continue.",
    ],
    counterexamples: [
      'Le ministre a annoncé que les inscriptions augmentera. (incorrect — the que-clause needs a correctly-conjugated verb: "augmenteront")',
    ],
  },
}