// Hand-authored seed unit: "Expressing Opinions" — the foundation unit of Learn & Practice
// (spec §3.2). It stays first in the path because it teaches the argumentation toolkit
// (opinion phrases, reasons, examples, contrast) that every other theme unit reuses. Exports the
// same { unit, items } shape `api/tutor.js`'s `type: "generateUnit"` returns, so hand-authored
// and AI-generated curriculum are structurally identical (spec §3.2.6).

export const unit = {
  id: 'opinions',
  title: 'Expressing Opinions',
  description: 'State an opinion clearly and back it up — the core of TEF Task B.',
  lessons: [
    {
      id: 'opinion-expressions',
      title: 'Opinion Expressions',
      learningItemIds: ['a-mon-avis', 'selon-moi', 'essentiel'],
      exercises: [
        {
          id: 'oe-1',
          learningItemId: 'a-mon-avis',
          type: 'multiple_choice',
          stage: 'recognition',
          prompt: 'What does "À mon avis" mean?',
          content: { options: ['In my opinion', 'On the other hand', 'For example', 'Even so'] },
          answer: 'In my opinion',
          explanation: '"À mon avis" introduces a personal opinion — "in my opinion."',
        },
        {
          id: 'oe-2',
          learningItemId: 'essentiel',
          type: 'multiple_choice',
          stage: 'recognition',
          prompt: 'What does "essentiel" mean?',
          content: { options: ['optional', 'difficult', 'essential', 'expensive'] },
          answer: 'essential',
          explanation: '"Essentiel" means "essential" — necessary or very important.',
        },
        {
          id: 'oe-3',
          learningItemId: 'essentiel',
          type: 'translation',
          stage: 'recall',
          prompt: 'Translate: essential',
          content: { direction: 'en_to_fr', options: ['essentiel', 'important', 'difficile', 'cher'] },
          answer: 'essentiel',
          explanation: '"Essential" translates to "essentiel" (masculine singular).',
        },
        {
          id: 'oe-4',
          learningItemId: 'essentiel',
          type: 'fill_blank',
          stage: 'context',
          prompt: 'Complete the sentence',
          content: {
            sentence: 'Cette question est ________.',
            options: ['essentielle', 'essentiel', 'essentiels', 'essentielles'],
          },
          answer: 'essentielle',
          explanation: '"Question" is feminine, so the adjective agrees: "essentielle."',
        },
        {
          id: 'oe-5',
          learningItemId: 'selon-moi',
          type: 'fill_blank',
          stage: 'context',
          prompt: 'Complete the sentence',
          content: {
            sentence: '________, cette solution est efficace.',
            options: ['Selon moi', 'En revanche', 'Par exemple', 'De plus'],
          },
          answer: 'Selon moi',
          explanation: '"Selon moi" ("in my opinion") fits naturally at the start of a sentence.',
        },
        {
          id: 'oe-6',
          learningItemId: 'a-mon-avis',
          type: 'pronunciation',
          stage: 'production',
          prompt: 'Say the sentence aloud.',
          content: { sentence: 'À mon avis, le télétravail présente plusieurs avantages.' },
          answer: 'À mon avis, le télétravail présente plusieurs avantages.',
          explanation: '"À mon avis" opens the opinion, then subject + verb + object in order.',
        },
      
        {
          id: 'oe-7',
          learningItemId: 'a-mon-avis',
          type: 'fill_blank',
          stage: 'recognition',
          prompt: 'Complete the sentence: ________, le télétravail peut réduire le stress.',
          content: {"sentence":"________, le télétravail peut réduire le stress.","options":["À mon avis","Selon moi","Je pense que","En général"]},
          answer: 'À mon avis',
          explanation: 'The phrase "À mon avis" introduces a personal opinion.',
        },
        {
          id: 'oe-8',
          learningItemId: 'a-mon-avis',
          type: 'translation',
          stage: 'recall',
          prompt: 'Translate into French: "In my opinion, the project should start next month."',
          content: {"options":["Selon moi, le projet devrait commencer le mois prochain.","À mon avis, le projet devrait commencer le mois prochain.","Je pense que le projet devrait commencer le mois prochain.","En général, le projet devrait commencer le mois prochain."]},
          answer: 'À mon avis, le projet devrait commencer le mois prochain.',
          explanation: '"À mon avis" means "In my opinion".',
        },
        {
          id: 'oe-9',
          learningItemId: 'selon-moi',
          type: 'multiple_choice',
          stage: 'recognition',
          prompt: 'Which of the following sentences uses "Selon moi" correctly?',
          content: {"options":["Selon moi, le climat change rapidement.","À mon avis, le climat change rapidement.","En général, le climat change rapidement.","Je pense que le climat change rapidement."]},
          answer: 'Selon moi, le climat change rapidement.',
          explanation: '"Selon moi" is used to express a personal opinion.',
        },
        {
          id: 'oe-10',
          learningItemId: 'selon-moi',
          type: 'pronunciation',
          stage: 'production',
          prompt: 'Pronounce the following sentence in French.',
          content: {"sentence":"Selon moi, il faut investir davantage dans l'éducation."},
          answer: 'Selon moi, il faut investir davantage dans l\'éducation.',
          explanation: 'Practice the correct French pronunciation of the phrase.',
        },
        {
          id: 'oe-11',
          learningItemId: 'essentiel',
          type: 'multiple_choice',
          stage: 'context',
          prompt: 'Choose the correct agreement for "essentiel" in the sentence: Les ressources ________ sont nécessaires.',
          content: {"options":["essentiel","essentielle","essentiels","essentielles"]},
          answer: 'essentielles',
          explanation: 'The adjective agrees with the plural feminine noun "ressources".',
        },
        {
          id: 'oe-12',
          learningItemId: 'essentiel',
          type: 'fill_blank',
          stage: 'completion',
          prompt: 'Fill in the blank with the correct form of "essentiel": Le plan d\'action est ________ pour la réussite.',
          content: {"sentence":"Le plan d'action est ________ pour la réussite.","options":["essentiel","essentielle","essentiels","essentielles"]},
          answer: 'essentiel',
          explanation: 'The adjective modifies the singular masculine noun "plan".',
        },
        {
          id: 'oe-13',
          learningItemId: 'a-mon-avis',
          type: 'multiple_choice',
          stage: 'recall',
          prompt: 'What is another expression that means "À mon avis"?',
          content: {"options":["Je pense que","Selon vous","En général","Par contre"]},
          answer: 'Je pense que',
          explanation: '"Je pense que" is a synonym for "À mon avis".',
        },
        {
          id: 'oe-14',
          learningItemId: 'selon-moi',
          type: 'fill_blank',
          stage: 'transformation',
          prompt: 'Transform the sentence: "Je pense que la réunion est utile." into a sentence using "Selon moi".',
          content: {"sentence":"______ que la réunion est utile.","options":["Je pense","Selon moi","En général","À mon avis"]},
          answer: 'Selon moi',
          explanation: '"Selon moi" replaces "Je pense" to express opinion.',
        },
      ],
    },
    {
      id: 'giving-reasons',
      title: 'Giving Reasons',
      learningItemIds: ['avantage', 'inconvenient', 'subject-verb-agreement'],
      exercises: [
        {
          id: 'gr-1',
          learningItemId: 'subject-verb-agreement',
          type: 'multiple_choice',
          stage: 'recognition',
          prompt: 'Which sentence is correct?',
          content: {
            options: ['Les étudiants peut travailler.', 'Les étudiants peuvent travailler.'],
          },
          answer: 'Les étudiants peuvent travailler.',
          explanation: '"Les étudiants" is plural, so "pouvoir" becomes "peuvent."',
          hints: ['Look at the subject.', '"Les étudiants" is plural — the verb must be plural too.'],
        },
        {
          id: 'gr-2',
          learningItemId: 'subject-verb-agreement',
          type: 'fill_blank',
          stage: 'completion',
          prompt: 'Complete the sentence',
          content: {
            sentence: 'Les étudiants ______ travailler le week-end.',
            options: ['peuvent', 'peut', 'pouvons', 'pouvez'],
          },
          answer: 'peuvent',
          explanation: 'Plural subject "les étudiants" requires the plural verb form "peuvent."',
        },
        {
          id: 'gr-3',
          learningItemId: 'subject-verb-agreement',
          type: 'fill_blank',
          stage: 'transformation',
          prompt: 'Change to plural: "Il peut travailler." → "Ils ______ travailler."',
          content: { sentence: 'Ils ______ travailler.', options: ['peuvent', 'peut', 'peux', 'pouvait'] },
          answer: 'peuvent',
          explanation: 'Singular "il peut" becomes plural "ils peuvent."',
        },
        {
          id: 'gr-4',
          learningItemId: 'avantage',
          type: 'translation',
          stage: 'recall',
          prompt: 'Translate: advantage',
          content: { direction: 'en_to_fr', options: ['avantage', 'inconvénient', 'solution', 'exemple'] },
          answer: 'avantage',
          explanation: '"Advantage" translates to "avantage" (masculine noun).',
        },
        {
          id: 'gr-5',
          learningItemId: 'inconvenient',
          type: 'translation',
          stage: 'recall',
          prompt: 'Translate: drawback',
          content: { direction: 'en_to_fr', options: ['inconvénient', 'avantage', 'bénéfice', 'solution'] },
          answer: 'inconvénient',
          explanation: '"Drawback" translates to "inconvénient" (masculine noun).',
        },
        {
          id: 'gr-6',
          learningItemId: 'avantage',
          type: 'pronunciation',
          stage: 'production',
          prompt: 'Say the sentence aloud.',
          content: { sentence: 'Ils peuvent travailler le week-end.' },
          answer: 'Ils peuvent travailler le week-end.',
          explanation: 'Plural subject "Ils" takes the plural verb form "peuvent."',
        },
      
        {
          id: 'oe-15',
          learningItemId: 'subject-verb-agreement',
          type: 'multiple_choice',
          stage: 'recognition',
          prompt: 'Quel est le bon accord du verbe pour "Elle ________ l’idée de partir ?"',
          content: {"options":["aime","aimes","aimons","aimez"]},
          answer: 'aime',
          explanation: 'Singular feminine subject "elle" uses singular verb form "aime".',
        },
        {
          id: 'oe-16',
          learningItemId: 'subject-verb-agreement',
          type: 'fill_blank',
          stage: 'completion',
          prompt: 'Complétez la phrase',
          content: {"sentence":"Nous ________ un projet commun.","options":["avons","as","ont","avez"]},
          answer: 'avons',
          explanation: 'First person plural subject "nous" requires "avons".',
        },
        {
          id: 'oe-17',
          learningItemId: 'inconvenient',
          type: 'multiple_choice',
          stage: 'recognition',
          prompt: 'Quel mot est le plus approprié pour exprimer un inconvénient ?',
          content: {"options":["bénéfice","désavantage","atout","avantage"]},
          answer: 'désavantage',
          explanation: '"désavantage" means drawback.',
        },
      ],
    },
    {
      id: 'adding-examples',
      title: 'Adding Examples & Contrast',
      learningItemIds: ['de-plus', 'par-exemple', 'en-revanche', 'benefique', 'solution', 'adjective-agreement'],
      exercises: [
        {
          id: 'ae-1',
          learningItemId: 'en-revanche',
          type: 'multiple_choice',
          stage: 'recognition',
          prompt: 'What does "En revanche" express?',
          content: { options: ['An example', 'A contrast', 'A conclusion', 'A cause'] },
          answer: 'A contrast',
          explanation: '"En revanche" means "on the other hand" — it introduces a contrast.',
        },
        {
          id: 'ae-2',
          learningItemId: 'adjective-agreement',
          type: 'multiple_choice',
          stage: 'recognition',
          prompt: 'Which sentence is correct?',
          content: { options: ['Une solution important.', 'Une solution importante.'] },
          answer: 'Une solution importante.',
          explanation: '"Solution" is feminine, so the adjective takes the feminine ending: "importante."',
        },
        {
          id: 'ae-3',
          learningItemId: 'benefique',
          type: 'fill_blank',
          stage: 'context',
          prompt: 'Complete the sentence',
          content: {
            sentence: 'Le télétravail est ________ pour beaucoup de salariés.',
            options: ['bénéfique', 'inconvénient', 'essentiel', 'difficile'],
          },
          answer: 'bénéfique',
          explanation: '"Bénéfique" ("beneficial") describes "le télétravail" here.',
        },
        {
          id: 'ae-4',
          learningItemId: 'par-exemple',
          type: 'fill_blank',
          stage: 'context',
          prompt: 'Complete the sentence',
          content: {
            sentence: '________, on peut travailler de chez soi deux jours par semaine.',
            options: ['Par exemple', 'En revanche', 'De plus', 'Selon moi'],
          },
          answer: 'Par exemple',
          explanation: '"Par exemple" introduces a concrete example.',
        },
        {
          id: 'ae-5',
          learningItemId: 'de-plus',
          type: 'translation',
          stage: 'recall',
          prompt: 'Translate: furthermore',
          content: { direction: 'en_to_fr', options: ['de plus', 'en revanche', 'par exemple', 'à mon avis'] },
          answer: 'de plus',
          explanation: '"Furthermore" translates to "de plus."',
        },
        {
          id: 'ae-6',
          learningItemId: 'en-revanche',
          type: 'pronunciation',
          stage: 'production',
          prompt: 'Say the sentence aloud.',
          content: { sentence: 'En revanche, il peut être difficile de se concentrer.' },
          answer: 'En revanche, il peut être difficile de se concentrer.',
          explanation: '"En revanche" opens the contrast, then the rest follows normal word order.',
        },
      
        {
          id: 'oe-18',
          learningItemId: 'de-plus',
          type: 'translation',
          stage: 'recall',
          prompt: 'Translate: "De plus, ce projet est très bénéfique pour l’entreprise."',
          content: {"options":["Furthermore, this project is very beneficial for the company.","In addition, this project is very beneficial for the company.","Moreover, this project is very beneficial for the company.","Also, this project is very beneficial for the company."]},
          answer: 'In addition, this project is very beneficial for the company.',
          explanation: 'The French phrase "De plus" is best translated as "In addition" in this context.',
        },
        {
          id: 'oe-19',
          learningItemId: 'par-exemple',
          type: 'fill_blank',
          stage: 'completion',
          prompt: 'Par exemple, on peut ____ travailler à distance trois jours par semaine.',
          content: {"sentence":"Par exemple, on peut ___ travailler à distance trois jours par semaine.","options":["continuer","commencer","finir","débuter"]},
          answer: 'continuer',
          explanation: 'The phrase "Par exemple" introduces an example; "continuer" fits the context of continuing to work remotely.',
        },
        {
          id: 'oe-20',
          learningItemId: 'en-revanche',
          type: 'multiple_choice',
          stage: 'recognition',
          prompt: 'Which sentence correctly uses "En revanche"?',
          content: {"options":["Je préfère le café. En revanche, je n’aime pas le thé.","Je préfère le thé. En revanche, je n’aime pas le café.","Je préfère le café. En revanche, je n’aime pas le café.","Je préfère le thé. En revanche, je n’aime pas le thé."]},
          answer: 'Je préfère le café. En revanche, je n’aime pas le thé.',
          explanation: '"En revanche" introduces a contrast between two statements.',
        },
        {
          id: 'oe-21',
          learningItemId: 'benefique',
          type: 'pronunciation',
          stage: 'production',
          prompt: 'Pronounce the following sentence correctly:',
          content: {"sentence":"Le télétravail est bénéfique, mais il peut être difficile de séparer vie privée et vie professionnelle."},
          answer: 'Le télétravail est bénéfique, mais il peut être difficile de séparer vie privée et vie professionnelle.',
          explanation: 'Focus on the correct intonation of "bénéfique" and the contrast introduced by "mais".',
        },
        {
          id: 'oe-22',
          learningItemId: 'par-exemple',
          type: 'multiple_choice',
          stage: 'recognition',
          prompt: 'What is the primary function of "Par exemple"?',
          content: {"options":["To add a conclusion","To give an example","To introduce a contrast","To summarize"]},
          answer: 'To give an example',
          explanation: '"Par exemple" means "for example" and is used to illustrate a point.',
        },
        {
          id: 'oe-23',
          learningItemId: 'en-revanche',
          type: 'translation',
          stage: 'recall',
          prompt: 'Translate: "En revanche, il est difficile de mesurer l’impact."',
          content: {"options":["On the other hand, it is difficult to measure the impact.","In addition, it is difficult to measure the impact.","Moreover, it is difficult to measure the impact.","Also, it is difficult to measure the impact."]},
          answer: 'On the other hand, it is difficult to measure the impact.',
          explanation: '"En revanche" is best rendered as "On the other hand" in this sentence.',
        },
      ],
    },
  ],
}

export const items = {
  essentiel: {
    id: 'essentiel',
    type: 'vocabulary',
    word: 'essentiel',
    meaning: 'essential',
    partOfSpeech: 'adjective',
    level: 'B1',
    topic: 'Opinion',
    example: 'Cette question est essentielle.',
    related: ['important', 'indispensable', 'primordial'],
      agreement: {"masculineSingular":"essentiel","feminineSingular":"essentielle","masculinePlural":"essentiels","femininePlural":"essentielles"},
  },
  benefique: {
    id: 'benefique',
    type: 'vocabulary',
    word: 'bénéfique',
    meaning: 'beneficial',
    partOfSpeech: 'adjective',
    level: 'B1',
    topic: 'Opinion',
    example: 'Le télétravail est bénéfique pour beaucoup de salariés.',
    related: ['avantageux', 'positif'],
    agreement: {
      masculineSingular: 'bénéfique',
      feminineSingular: 'bénéfique',
      masculinePlural: 'bénéfiques',
      femininePlural: 'bénéfiques',
    },
  },
  avantage: {
    id: 'avantage',
    type: 'vocabulary',
    word: 'avantage',
    meaning: 'advantage',
    partOfSpeech: 'noun (m.)',
    level: 'B1',
    topic: 'Opinion',
    example: 'Le principal avantage, c’est la flexibilité.',
    related: ['bénéfice', 'atout'],
  },
  inconvenient: {
    id: 'inconvenient',
    type: 'vocabulary',
    word: 'inconvénient',
    meaning: 'drawback',
    partOfSpeech: 'noun (m.)',
    level: 'B1',
    topic: 'Opinion',
    example: 'Le principal inconvénient, c’est l’isolement.',
    related: ['désavantage'],
  },
  solution: {
    id: 'solution',
    type: 'vocabulary',
    word: 'solution',
    meaning: 'solution',
    partOfSpeech: 'noun (f.)',
    level: 'B1',
    topic: 'Opinion',
    example: 'Cette solution me semble efficace.',
    related: ['réponse'],
  },

  'a-mon-avis': {
    id: 'a-mon-avis',
    type: 'phrase',
    phrase: 'À mon avis',
    meaning: 'In my opinion',
    function: 'Opinion',
    level: 'B1',
    topic: 'Opinion',
    tefUsage: 'Expression orale / écrite',
    example: 'À mon avis, le télétravail présente plusieurs avantages.',
    related: ['Selon moi', 'Je pense que'],
  },
  'selon-moi': {
    id: 'selon-moi',
    type: 'phrase',
    phrase: 'Selon moi',
    meaning: 'In my opinion / According to me',
    function: 'Opinion',
    level: 'B1',
    topic: 'Opinion',
    tefUsage: 'Expression orale / écrite',
    example: 'Selon moi, cette solution est efficace.',
    related: ['À mon avis'],
  },
  'en-revanche': {
    id: 'en-revanche',
    type: 'phrase',
    phrase: 'En revanche',
    meaning: 'On the other hand',
    function: 'Contrast',
    level: 'B1',
    topic: 'Opinion',
    tefUsage: 'Expression orale / écrite — argumentation',
    example:
      'Le télétravail est pratique. En revanche, il peut être difficile de séparer vie privée et vie professionnelle.',
    related: ['Cependant', 'Toutefois'],
  },
  'de-plus': {
    id: 'de-plus',
    type: 'phrase',
    phrase: 'De plus',
    meaning: 'Furthermore / In addition',
    function: 'Adding an argument',
    level: 'B1',
    topic: 'Opinion',
    tefUsage: 'Expression écrite — structurer un argument',
    example: 'De plus, cette solution coûte moins cher.',
    related: ['En outre', 'Par ailleurs'],
  },
  'par-exemple': {
    id: 'par-exemple',
    type: 'phrase',
    phrase: 'Par exemple',
    meaning: 'For example',
    function: 'Giving an example',
    level: 'B1',
    topic: 'Opinion',
    tefUsage: 'Expression orale / écrite',
    example: 'Par exemple, on peut travailler de chez soi deux jours par semaine.',
    related: ['Prenons le cas de'],
  },

  'subject-verb-agreement': {
    id: 'subject-verb-agreement',
    type: 'grammar',
    title: 'Subject-verb agreement',
    level: 'B1',
    explanation: 'The verb must agree in number with its subject — a plural subject needs a plural verb form.',
    examples: ['Il peut travailler.', 'Ils peuvent travailler.'],
    counterexamples: ['Ils peut travailler. (incorrect — plural subject, singular verb)'],
  },
  'adjective-agreement': {
    id: 'adjective-agreement',
    type: 'grammar',
    title: 'Adjective agreement',
    level: 'B1',
    explanation:
      'An adjective must agree in gender and number with the noun it describes — add -e for feminine, -s for plural.',
    examples: ['Un avantage important.', 'Une solution importante.', 'Des solutions importantes.'],
    counterexamples: ['Une solution important. (incorrect — feminine noun, masculine adjective)'],
  },
}