// Hand-authored TEF theme unit (spec §3.2.1) — "La politique" (Politics). Part of the full TEF
// theme coverage in the Learn path. Exports the same { unit, items } shape as generated units
// (spec §3.2.6). All exercises are tap-only (spec §3.2.2).

export const unit = {
  id: 'politique',
  title: 'La politique',
  description: 'Discuss civic life, local issues, and the news of society.',
  lessons: [
    {
      id: 'politique-vocabulaire',
      title: 'Vocabulaire de la politique',
      learningItemIds: ['citoyen', 'vote', 'loi', 'gouvernement'],
      exercises: [
        {
          id: 'pol-1',
          learningItemId: 'citoyen',
          type: 'multiple_choice',
          stage: 'recognition',
          prompt: 'What does "un citoyen" mean?',
          content: { options: ['a citizen', 'a mayor', 'a minister', 'a lawyer'] },
          answer: 'a citizen',
          explanation: '"Un citoyen" is a "citizen."',
        },
        {
          id: 'pol-2',
          learningItemId: 'vote',
          type: 'multiple_choice',
          stage: 'recognition',
          prompt: 'What does "un vote" mean?',
          content: { options: ['a vote', 'a debate', 'a law', 'a protest'] },
          answer: 'a vote',
          explanation: '"Un vote" is a "vote."',
        },
        {
          id: 'pol-3',
          learningItemId: 'loi',
          type: 'translation',
          stage: 'recall',
          prompt: 'Translate: law',
          content: { direction: 'en_to_fr', options: ['loi', 'louis', 'loir', 'haie'] },
          answer: 'loi',
          explanation: '"Law" translates to "la loi."',
        },
        {
          id: 'pol-4',
          learningItemId: 'gouvernement',
          type: 'translation',
          stage: 'recall',
          prompt: 'Translate: government',
          content: { direction: 'en_to_fr', options: ['gouvernement', 'gouvernante', 'goûter', 'garantie'] },
          answer: 'gouvernement',
          explanation: '"Government" translates to "le gouvernement."',
        },
        {
          id: 'pol-5',
          learningItemId: 'citoyen',
          type: 'fill_blank',
          stage: 'context',
          prompt: 'Complete the sentence',
          content: {
            sentence: 'Chaque ______ peut voter pour exprimer son avis.',
            options: ['citoyen', 'civil', 'citron', 'soldat'],
          },
          answer: 'citoyen',
          explanation: '"Chaque citoyen" — every citizen.',
        },
        {
          id: 'pol-6',
          learningItemId: 'vote',
          type: 'fill_blank',
          stage: 'context',
          prompt: 'Complete the sentence',
          content: {
            sentence: 'Le ______ est un droit fondamental.',
            options: ['vote', 'voile', 'voix', 'vol'],
          },
          answer: 'vote',
          explanation: '"Le vote est un droit" — voting is a right.',
        },
      
        {
          id: 'pol-19',
          learningItemId: 'loi',
          type: 'multiple_choice',
          stage: 'recall',
          prompt: 'Which word means "law" in French?',
          content: {"options":["citoyen","vote","loi","gouvernement"]},
          answer: 'loi',
          explanation: '"Loi" is the French word for "law."',
        },
        {
          id: 'pol-20',
          learningItemId: 'gouvernement',
          type: 'fill_blank',
          stage: 'context',
          prompt: 'Le _______ a adopté une nouvelle réglementation.',
          content: {"sentence":"Le _______ a adopté une nouvelle réglementation.","options":["citoyen","vote","loi","gouvernement"]},
          answer: 'gouvernement',
          explanation: 'The government adopted a new regulation.',
        },
        {
          id: 'pol-21',
          learningItemId: 'vote',
          type: 'pronunciation',
          stage: 'production',
          prompt: 'Pronounce the phrase: "Un vote est un droit fondamental."',
          content: {"sentence":"Un vote est un droit fondamental."},
          answer: 'Un vote est un droit fondamental.',
          explanation: 'Practice the correct French pronunciation.',
        },
        {
          id: 'pol-22',
          learningItemId: 'vote',
          type: 'multiple_choice',
          stage: 'recall',
          prompt: 'Which term refers to the act of voting?',
          content: {"options":["citoyen","vote","loi","gouvernement"]},
          answer: 'vote',
          explanation: 'The act of voting is called "vote."',
        },
        {
          id: 'pol-23',
          learningItemId: 'vote',
          type: 'fill_blank',
          stage: 'completion',
          prompt: 'Lors de l\'____, les citoyens expriment leur choix.',
          content: {"sentence":"Lors de l'____, les citoyens expriment leur choix.","options":["citoyen","vote","loi","gouvernement"]},
          answer: 'vote',
          explanation: 'During the vote, citizens express their choice.',
        },
        {
          id: 'pol-24',
          learningItemId: 'citoyen',
          type: 'pronunciation',
          stage: 'production',
          prompt: 'Pronounce: "Chaque citoyen a le droit de voter."',
          content: {"sentence":"Chaque citoyen a le droit de voter."},
          answer: 'Chaque citoyen a le droit de voter.',
          explanation: 'Practice French pronunciation of the sentence.',
        },
        {
          id: 'pol-25',
          learningItemId: 'loi',
          type: 'multiple_choice',
          stage: 'recognition',
          prompt: 'What does "la loi" mean?',
          content: {"options":["the citizen","the vote","the law","the government"]},
          answer: 'the law',
          explanation: '"La loi" translates to "the law."',
        },
      ],
    },
    {
      id: 'politique-idees',
      title: 'Construire des idées',
      learningItemIds: ['si-imparfait-conditionnel', 'prendre-part', 'debat'],
      exercises: [
        {
          id: 'pol-7',
          learningItemId: 'si-imparfait-conditionnel',
          type: 'multiple_choice',
          stage: 'recognition',
          prompt: 'Complete the sentence: "Si j\u2019étais ministre, je ______ la loi."',
          content: { options: ['changerais', 'change', 'changé', 'changer'] },
          answer: 'changerais',
          explanation: 'After "si + imparfait", use the conditionnel: "je changerais."',
        },
        {
          id: 'pol-8',
          learningItemId: 'si-imparfait-conditionnel',
          type: 'fill_blank',
          stage: 'transformation',
          prompt: 'Complete the sentence',
          content: {
            sentence: 'Si nous ______ plus de voix, nous gagnerions.',
            options: ['avions', 'aurons', 'avons', 'aurions'],
          },
          answer: 'avions',
          explanation: '"Si + imparfait" (avions) + conditionnel (gagnerions).',
        },
        {
          id: 'pol-9',
          learningItemId: 'prendre-part',
          type: 'multiple_choice',
          stage: 'recognition',
          prompt: 'What does "Prendre part à" mean?',
          content: { options: ['To take part in', 'To take a stand', 'To take over', 'To take notes'] },
          answer: 'To take part in',
          explanation: '"Prendre part à" = "to take part in."',
        },
        {
          id: 'pol-10',
          learningItemId: 'prendre-part',
          type: 'fill_blank',
          stage: 'context',
          prompt: 'Complete the sentence',
          content: {
            sentence: 'On peut ______ part au débat public.',
            options: ['prendre', 'prends', 'prendrait', 'prenant'],
          },
          answer: 'prendre',
          explanation: 'After the modal "on peut": infinitive "prendre part."',
        },
        {
          id: 'pol-11',
          learningItemId: 'debat',
          type: 'translation',
          stage: 'recall',
          prompt: 'Translate: debate',
          content: { direction: 'en_to_fr', options: ['débat', 'détail', 'débardeur', 'début'] },
          answer: 'débat',
          explanation: '"Debate" translates to "le débat."',
        },
        {
          id: 'pol-12',
          learningItemId: 'debat',
          type: 'fill_blank',
          stage: 'context',
          prompt: 'Complete the sentence',
          content: {
            sentence: 'Le ______ sur l\u2019environnement est très animé.',
            options: ['débat', 'début', 'départ', 'degré'],
          },
          answer: 'débat',
          explanation: '"Le débat est animé" — the debate is lively.',
        },
      
        {
          id: 'pol-35',
          learningItemId: 'si-imparfait-conditionnel',
          type: 'multiple_choice',
          stage: 'recall',
          prompt: 'Which form completes the sentence: "Si vous _______ le problème, vous le résoudriez."',
          content: {"options":["saisissiez","saisissez","saisiriez","saisis"]},
          answer: 'saisissiez',
          explanation: 'Use si + imparfait (saisissiez) and conditionnel (résoudriez).',
        },
        {
          id: 'pol-36',
          learningItemId: 'si-imparfait-conditionnel',
          type: 'fill_blank',
          stage: 'context',
          prompt: 'Complete the sentence: "Si elle _______ plus d’opportunités, elle _______ son rêve."',
          content: {"sentence":"Si elle _______ plus d’opportunités, elle _______ son rêve.","options":["avait","aurait","a","avons"]},
          answer: 'avait',
          explanation: 'If-clause uses imparfait; result uses conditionnel.',
        },
        {
          id: 'pol-37',
          learningItemId: 'si-imparfait-conditionnel',
          type: 'translation',
          stage: 'recognition',
          prompt: 'Translate: "Si nous avions le temps, nous participerions au débat public."',
          content: {"options":["Si nous avons le temps, nous participerons au débat public.","Si nous avions le temps, nous participerions au débat public.","Si nous avons le temps, nous participerions au débat public.","Si nous avions le temps, nous participerons au débat public."]},
          answer: 'Si nous avions le temps, nous participerions au débat public.',
          explanation: 'Correct use of si + imparfait and conditionnel.',
        },
        {
          id: 'pol-38',
          learningItemId: 'prendre-part',
          type: 'pronunciation',
          stage: 'production',
          prompt: 'Pronounce the following sentence:',
          content: {"sentence":"Si je pouvais choisir, je prendrais part à la réunion."},
          answer: 'Si je pouvais choisir, je prendrais part à la réunion.',
          explanation: 'Practice pronunciation of "si + imparfait" and "prendrais part".',
        },
        {
          id: 'pol-39',
          learningItemId: 'si-imparfait-conditionnel',
          type: 'multiple_choice',
          stage: 'recall',
          prompt: 'Choose the correct form: "Si tu _______ riche, tu _______ de l’aide aux sans-abri."',
          content: {"options":["étais","aurais","es","était"]},
          answer: 'étais',
          explanation: 'Use si + imparfait (étais) and conditionnel (aiderais).',
        },
        {
          id: 'pol-40',
          learningItemId: 'debat',
          type: 'pronunciation',
          stage: 'production',
          prompt: 'Say this sentence out loud:',
          content: {"sentence":"Un débat public est un espace où les citoyens peuvent exprimer leurs opinions."},
          answer: 'Un débat public est un espace où les citoyens peuvent exprimer leurs opinions.',
          explanation: 'Focus on the rhythm of "débat public".',
        },
      ],
    },
    {
      id: 'politique-argumenter',
      title: 'Argumenter sur la politique',
      learningItemIds: ['faire-entendre-sa-voix', 'etre-pour-contre'],
      exercises: [
        {
          id: 'pol-13',
          learningItemId: 'faire-entendre-sa-voix',
          type: 'multiple_choice',
          stage: 'recognition',
          prompt: 'What does "Faire entendre sa voix" mean?',
          content: { options: ['To make your voice heard', 'To raise the volume', 'To speak quietly', 'To lose a vote'] },
          answer: 'To make your voice heard',
          explanation: '"Faire entendre sa voix" = to make your voice heard.',
        },
        {
          id: 'pol-14',
          learningItemId: 'faire-entendre-sa-voix',
          type: 'fill_blank',
          stage: 'context',
          prompt: 'Complete the sentence',
          content: {
            sentence: 'Voter permet de faire ______ sa voix.',
            options: ['entendre', 'entends', 'entendu', 'entendant'],
          },
          answer: 'entendre',
          explanation: 'The set expression is "faire entendre sa voix" (infinitive).',
        },
        {
          id: 'pol-15',
          learningItemId: 'etre-pour-contre',
          type: 'multiple_choice',
          stage: 'recognition',
          prompt: 'What does "Être pour ou contre" mean?',
          content: { options: ['To be for or against', 'To be undecided', 'To vote on something', 'To change your mind'] },
          answer: 'To be for or against',
          explanation: '"Être pour ou contre" = to be for or against.',
        },
        {
          id: 'pol-16',
          learningItemId: 'etre-pour-contre',
          type: 'fill_blank',
          stage: 'context',
          prompt: 'Complete the sentence',
          content: {
            sentence: 'Moi, je suis ______ cette réforme.',
            options: ['pour', 'par', 'peur', 'pourquoi'],
          },
          answer: 'pour',
          explanation: '"Être pour" — to be in favor of.',
        },
        {
          id: 'pol-17',
          learningItemId: 'faire-entendre-sa-voix',
          type: 'pronunciation',
          stage: 'production',
          prompt: 'Say the sentence aloud.',
          content: { sentence: 'Chaque citoyen peut faire entendre sa voix.' },
          answer: 'Chaque citoyen peut faire entendre sa voix.',
          explanation: 'A strong civic sentence you can reuse in the oral exam.',
        },
        {
          id: 'pol-18',
          learningItemId: 'si-imparfait-conditionnel',
          type: 'pronunciation',
          stage: 'production',
          prompt: 'Say the sentence aloud.',
          content: { sentence: 'Si j\u2019étais maire, je créerais plus d\u2019espaces verts.' },
          answer: 'Si j\u2019étais maire, je créerais plus d\u2019espaces verts.',
          explanation: '"Si + imparfait" + conditionnel — the classic hypothetical for the debate.',
        },
      
        {
          id: 'pol-26',
          learningItemId: 'faire-entendre-sa-voix',
          type: 'multiple_choice',
          stage: 'recall',
          prompt: 'Choose the correct translation for "Faire entendre sa voix".',
          content: {"options":["To make your voice heard","To be silent","To speak loudly","To lose a vote"]},
          answer: 'To make your voice heard',
          explanation: '"Faire entendre sa voix" means to make your voice heard.',
        },
        {
          id: 'pol-27',
          learningItemId: 'faire-entendre-sa-voix',
          type: 'fill_blank',
          stage: 'context',
          prompt: 'Complete the sentence',
          content: {"sentence":"Les manifestants veulent que le gouvernement _______ leurs revendications.","options":["entende","entend","entendu","entendant"]},
          answer: 'entende',
          explanation: 'The expression is "faire entendre"; here we use the subjunctive "entende".',
        },
        {
          id: 'pol-28',
          learningItemId: 'faire-entendre-sa-voix',
          type: 'translation',
          stage: 'recall',
          prompt: 'Translate: "Nous devons faire entendre notre voix dans le débat public."',
          content: {"options":["We must make our voice heard in the public debate.","We must keep our voice quiet in the public debate.","We must lose our voice in the public debate.","We must speak loudly in the public debate."]},
          answer: 'We must make our voice heard in the public debate.',
          explanation: 'Direct translation of the French sentence.',
        },
        {
          id: 'pol-29',
          learningItemId: 'faire-entendre-sa-voix',
          type: 'pronunciation',
          stage: 'production',
          prompt: 'Pronounce the full phrase',
          content: {"sentence":"Faire entendre sa voix"},
          answer: 'Faire entendre sa voix',
          explanation: 'Audio exercise to practice pronunciation.',
        },
        {
          id: 'pol-30',
          learningItemId: 'etre-pour-contre',
          type: 'multiple_choice',
          stage: 'recognition',
          prompt: 'What does "Être pour ou contre" mean?',
          content: {"options":["To be in favor or against","To be neutral","To be confused","To be silent"]},
          answer: 'To be in favor or against',
          explanation: 'The expression means to be for or against.',
        },
        {
          id: 'pol-31',
          learningItemId: 'etre-pour-contre',
          type: 'fill_blank',
          stage: 'context',
          prompt: 'Complete the sentence',
          content: {"sentence":"Je suis _______ cette proposition.","options":["pour","contre","à","en"]},
          answer: 'pour',
          explanation: 'Use "pour" to express support.',
        },
        {
          id: 'pol-32',
          learningItemId: 'etre-pour-contre',
          type: 'translation',
          stage: 'recall',
          prompt: 'Translate: "Il est contre la réforme."',
          content: {"options":["He is for the reform.","He is against the reform.","He is neutral about the reform.","He is confused about the reform."]},
          answer: 'He is against the reform.',
          explanation: 'Direct translation.',
        },
        {
          id: 'pol-33',
          learningItemId: 'etre-pour-contre',
          type: 'pronunciation',
          stage: 'production',
          prompt: 'Pronounce the phrase',
          content: {"sentence":"Être pour ou contre"},
          answer: 'Être pour ou contre',
          explanation: 'Audio exercise to practice pronunciation.',
        },
        {
          id: 'pol-34',
          learningItemId: 'etre-pour-contre',
          type: 'multiple_choice',
          stage: 'recall',
          prompt: 'Choose the correct form to express opposition.',
          content: {"options":["Je suis contre la décision.","Je suis pour la décision.","Je suis neutral la décision.","Je suis confus la décision."]},
          answer: 'Je suis contre la décision.',
          explanation: 'Use "contre" to express opposition.',
        },
      ],
    },
  ],
}

export const items = {
  citoyen: {
    id: 'citoyen',
    type: 'vocabulary',
    word: 'citoyen',
    meaning: 'citizen',
    partOfSpeech: 'noun (m.)',
    level: 'B1',
    topic: 'La politique',
    example: 'Chaque citoyen peut voter pour exprimer son avis.',
    related: ['habitant', 'électeur'],
  },
  vote: {
    id: 'vote',
    type: 'vocabulary',
    word: 'vote',
    meaning: 'vote',
    partOfSpeech: 'noun (m.)',
    level: 'B1',
    topic: 'La politique',
    example: 'Le vote est un droit fondamental.',
    related: ['élection', 'scrutin'],
  },
  loi: {
    id: 'loi',
    type: 'vocabulary',
    word: 'loi',
    meaning: 'law',
    partOfSpeech: 'noun (f.)',
    level: 'B1',
    topic: 'La politique',
    example: 'Une nouvelle loi va protéger les consommateurs.',
    related: ['règle', 'texte'],
  },
  gouvernement: {
    id: 'gouvernement',
    type: 'vocabulary',
    word: 'gouvernement',
    meaning: 'government',
    partOfSpeech: 'noun (m.)',
    level: 'B1',
    topic: 'La politique',
    example: 'Le gouvernement prépare une réforme des transports.',
    related: ['État', 'administration'],
  },

  'si-imparfait-conditionnel': {
    id: 'si-imparfait-conditionnel',
    type: 'grammar',
    title: 'Si + imparfait, conditionnel',
    level: 'B1',
    explanation:
      'Hypotheses use "si + imparfait" in the if-clause and the conditionnel in the result: si j\u2019avais le temps, je voterais.',
    examples: ['Si j\u2019étais maire, je créerais plus d\u2019espaces verts.', 'Si nous avions plus de voix, nous gagnerions.'],
    counterexamples: ['Si je serai riche, je donnerai. (incorrect — never "si + futur"; use imparfait + conditionnel)'],
  },

  'prendre-part': {
    id: 'prendre-part',
    type: 'phrase',
    phrase: 'Prendre part à',
    meaning: 'To take part in',
    function: 'Civic engagement',
    level: 'B1',
    topic: 'La politique',
    tefUsage: 'Expression orale — parler de son engagement',
    example: 'On peut prendre part au débat public.',
    related: ['Participer à', "S'impliquer dans"],
    conjugation: {
      je: 'prends part à',
      tu: 'prends part à',
      ilElle: 'prend part à',
      nous: 'prenons part à',
      vous: 'prenez part à',
      ilsElles: 'prennent part à',
    },
  },
  debat: {
    id: 'debat',
    type: 'phrase',
    phrase: 'Un débat public',
    meaning: 'A public debate',
    function: 'Civic life',
    level: 'B1',
    topic: 'La politique',
    tefUsage: 'Expression orale — commenter l\u2019actualité',
    example: 'Le débat sur l\u2019environnement est très animé.',
    related: ['La discussion', 'Le dialogue'],
  },
  'faire-entendre-sa-voix': {
    id: 'faire-entendre-sa-voix',
    type: 'phrase',
    phrase: 'Faire entendre sa voix',
    meaning: 'To make your voice heard',
    function: 'Civic engagement',
    level: 'B1',
    topic: 'La politique',
    tefUsage: 'Expression orale — défendre une opinion',
    example: 'Chaque citoyen peut faire entendre sa voix.',
    related: ["S'exprimer", 'Prendre la parole'],
    conjugation: {
      je: 'je fais entendre ma voix',
      tu: 'tu fais entendre ta voix',
      ilElle: 'il/elle fait entendre sa voix',
      nous: 'nous faisons entendre notre voix',
      vous: 'vous faites entendre votre voix',
      ilsElles: 'ils/elles font entendre leur voix',
    },
  },
  'etre-pour-contre': {
    id: 'etre-pour-contre',
    type: 'phrase',
    phrase: 'Être pour ou contre',
    meaning: 'To be for or against',
    function: 'Stating a position',
    level: 'B1',
    topic: 'La politique',
    tefUsage: 'Expression orale — donner son avis',
    example: 'Je suis pour cette réforme.',
    related: ['Être favorable à', 'S\u2019opposer à'],
    conjugation: {
      je: 'suis pour',
      tu: 'es pour',
      ilElle: 'est pour',
      nous: 'sommes pour',
      vous: 'êtes pour',
      ilsElles: 'sont pour',
    },
  },
}