// Hand-authored TEF theme unit (spec §3.2.1) — "La santé" (Health). Part of the full TEF theme
// coverage in the Learn path. Exports the same { unit, items } shape as generated units
// (spec §3.2.6). All exercises are tap-only (spec §3.2.2).

export const unit = {
  id: 'sante',
  title: 'La santé',
  description: 'Use the right vocabulary and advice for health and well-being conversations.',
  lessons: [
    {
      id: 'sante-vocabulaire',
      title: 'Vocabulaire de la santé',
      learningItemIds: ['symptome', 'traitement', 'rendez-vous', 'fatigue'],
      exercises: [
        {
          id: 's-1',
          learningItemId: 'symptome',
          type: 'multiple_choice',
          stage: 'recognition',
          prompt: 'What does "un symptôme" mean?',
          content: { options: ['a symptom', 'a remedy', 'a doctor', 'a hospital'] },
          answer: 'a symptom',
          explanation: '"Un symptôme" is a "symptom."',
        },
        {
          id: 's-2',
          learningItemId: 'traitement',
          type: 'multiple_choice',
          stage: 'recognition',
          prompt: 'What does "un traitement" mean?',
          content: { options: ['a treatment', 'a treatment plant', 'a farewell', 'a salary'] },
          answer: 'a treatment',
          explanation: '"Un traitement" in a health context is a "treatment."',
        },
        {
          id: 's-3',
          learningItemId: 'rendez-vous',
          type: 'translation',
          stage: 'recall',
          prompt: 'Translate: appointment (medical)',
          content: { direction: 'en_to_fr', options: ['rendez-vous', 'traitement', 'symptôme', 'ordonnance'] },
          answer: 'rendez-vous',
          explanation: 'A medical appointment is "un rendez-vous."',
        },
        {
          id: 's-4',
          learningItemId: 'fatigue',
          type: 'translation',
          stage: 'recall',
          prompt: 'Translate: tiredness',
          content: { direction: 'en_to_fr', options: ['fatigue', 'fièvre', 'faim', 'force'] },
          answer: 'fatigue',
          explanation: '"Tiredness" translates to "la fatigue."',
        },
        {
          id: 's-5',
          learningItemId: 'rendez-vous',
          type: 'fill_blank',
          stage: 'context',
          prompt: 'Complete the sentence',
          content: {
            sentence: 'Je vais prendre un ______ chez le médecin.',
            options: ['rendez-vous', 'rendez', 'rendu', 'médicament'],
          },
          answer: 'rendez-vous',
          explanation: 'The fixed noun is "un rendez-vous" (hyphenated).',
        },
        {
          id: 's-6',
          learningItemId: 'traitement',
          type: 'fill_blank',
          stage: 'context',
          prompt: 'Complete the sentence',
          content: {
            sentence: 'Ce ______ doit être suivi pendant deux semaines.',
            options: ['traitement', 'traiteur', 'transport', 'traitail'],
          },
          answer: 'traitement',
          explanation: '"Suivre un traitement" means "to be on a course of treatment."',
        },
      
        {
          id: 's-33',
          learningItemId: 'rendez-vous',
          type: 'multiple_choice',
          stage: 'recognition',
          prompt: 'Which of the following words means "appointment" in English?',
          content: {"options":["symptom","treatment","appointment","fatigue"]},
          answer: 'appointment',
          explanation: '"Rendez-vous" translates to "appointment."',
        },
        {
          id: 's-34',
          learningItemId: 'rendez-vous',
          type: 'fill_blank',
          stage: 'context',
          prompt: 'Je dois prendre un ________ chez le médecin.',
          content: {"sentence":"Je dois prendre un ________ chez le médecin.","options":["symptôme","traitement","rendez-vous","fatigue"]},
          answer: 'rendez-vous',
          explanation: 'The sentence means "I need to make an appointment with the doctor."',
        },
        {
          id: 's-35',
          learningItemId: 'traitement',
          type: 'translation',
          stage: 'recall',
          prompt: 'Translate to French: "The treatment lasted two weeks."',
          content: {"options":["Le traitement a duré deux semaines.","Le symptôme a duré deux semaines.","La fatigue a duré deux semaines.","Le rendez-vous a duré deux semaines."]},
          answer: 'Le traitement a duré deux semaines.',
          explanation: 'This is the correct translation of the sentence.',
        },
        {
          id: 's-36',
          learningItemId: 'fatigue',
          type: 'multiple_choice',
          stage: 'recall',
          prompt: 'What does "fatigue" mean in English?',
          content: {"options":["tiredness","symptom","appointment","treatment"]},
          answer: 'tiredness',
          explanation: '"Fatigue" means "tiredness."',
        },
        {
          id: 's-37',
          learningItemId: 'fatigue',
          type: 'fill_blank',
          stage: 'completion',
          prompt: 'Le patient ressent une ________ depuis trois jours.',
          content: {"sentence":"Le patient ressent une ________ depuis trois jours.","options":["symptôme","traitement","rendez-vous","fatigue"]},
          answer: 'fatigue',
          explanation: 'The patient feels tiredness for three days.',
        },
        {
          id: 's-38',
          learningItemId: 'traitement',
          type: 'multiple_choice',
          stage: 'context',
          prompt: 'Which word best fits: "Après le ________, il se sentait mieux."',
          content: {"options":["symptôme","traitement","rendez-vous","fatigue"]},
          answer: 'traitement',
          explanation: 'After the treatment, he felt better.',
        },
        {
          id: 's-39',
          learningItemId: 'rendez-vous',
          type: 'translation',
          stage: 'recall',
          prompt: 'Translate to French: "I have an appointment with the doctor."',
          content: {"options":["J'ai un rendez-vous chez le médecin.","J'ai un symptôme chez le médecin.","J'ai un traitement chez le médecin.","J'ai une fatigue chez le médecin."]},
          answer: 'J\'ai un rendez-vous chez le médecin.',
          explanation: 'Correct translation of the sentence.',
        },
      ],
    },
    {
      id: 'sante-idees',
      title: 'Construire des idées',
      learningItemIds: ['imperatif-conseils', 'prendre-soin-de', 'activite-physique'],
      exercises: [
        {
          id: 's-7',
          learningItemId: 'imperatif-conseils',
          type: 'multiple_choice',
          stage: 'recognition',
          prompt: 'Which sentence gives advice correctly?',
          content: { options: ['Mangez plus de légumes.', 'Vous mangez plus de légumes.'] },
          answer: 'Mangez plus de légumes.',
          explanation: 'Direct advice uses the imperative, without the subject "vous."',
        },
        {
          id: 's-8',
          learningItemId: 'imperatif-conseils',
          type: 'fill_blank',
          stage: 'context',
          prompt: 'Complete the sentence',
          content: {
            sentence: "Buvez beaucoup d'______.",
            options: ['eau', 'haut', 'ô', 'o'],
          },
          answer: 'eau',
          explanation: '"Boire beaucoup d\u2019eau" — water is "l\u2019eau."',
        },
        {
          id: 's-9',
          learningItemId: 'activite-physique',
          type: 'translation',
          stage: 'recall',
          prompt: 'Translate: physical activity',
          content: { direction: 'en_to_fr', options: ['activité physique', 'activité professionnelle', 'activité manuelle', 'énergie'] },
          answer: 'activité physique',
          explanation: '"Physical activity" translates to "l\u2019activité physique."',
        },
        {
          id: 's-10',
          learningItemId: 'prendre-soin-de',
          type: 'multiple_choice',
          stage: 'recognition',
          prompt: 'What does "Prendre soin de" mean?',
          content: { options: ['To take care of', 'To take over', 'To take apart', 'To take on'] },
          answer: 'To take care of',
          explanation: '"Prendre soin de" means "to take care of."',
        },
        {
          id: 's-11',
          learningItemId: 'prendre-soin-de',
          type: 'fill_blank',
          stage: 'context',
          prompt: 'Complete the sentence',
          content: {
            sentence: 'Il faut ______ soin de son sommeil.',
            options: ['prendre', 'prêter', 'penser', 'perdre'],
          },
          answer: 'prendre',
          explanation: 'The fixed expression is "prendre soin de."',
        },
        {
          id: 's-12',
          learningItemId: 'activite-physique',
          type: 'fill_blank',
          stage: 'context',
          prompt: 'Complete the sentence',
          content: {
            sentence: "Il faut faire de l'______ physique chaque semaine.",
            options: ['activité', 'activiste', 'attention', 'accueil'],
          },
          answer: 'activité',
          explanation: '"Faire de l\u2019activité physique" — regular exercise.',
        },
      
        {
          id: 's-19',
          learningItemId: 'imperatif-conseils',
          type: 'multiple_choice',
          stage: 'recognition',
          prompt: 'Which sentence gives advice correctly using the imperative?',
          content: {"options":["Prenez votre médicament chaque jour.","Vous prenez votre médicament chaque jour."]},
          answer: 'Prenez votre médicament chaque jour.',
          explanation: 'The imperative gives direct advice without the subject pronoun.',
        },
        {
          id: 's-20',
          learningItemId: 'prendre-soin-de',
          type: 'fill_blank',
          stage: 'context',
          prompt: 'Complete the sentence',
          content: {"sentence":"Il faut ____ de son sommeil.","options":["prendre soin","prendre soin de","prendre soin de son"]},
          answer: 'prendre soin de',
          explanation: 'The phrase "prendre soin de" means "to take care of".',
        },
        {
          id: 's-21',
          learningItemId: 'prendre-soin-de',
          type: 'pronunciation',
          stage: 'production',
          prompt: 'Pronounce the following sentence',
          content: {"sentence":"Prendre soin de son alimentation est important."},
          answer: 'Prendre soin de son alimentation est important.',
          explanation: '',
        },
        {
          id: 's-22',
          learningItemId: 'activite-physique',
          type: 'multiple_choice',
          stage: 'recall',
          prompt: 'Choose the correct plural form of "activité physique".',
          content: {"options":["activités physiques","activité physique","activités physique","activité physiques"]},
          answer: 'activités physiques',
          explanation: 'The noun is feminine; plural adds -s to both words.',
        },
        {
          id: 's-23',
          learningItemId: 'imperatif-conseils',
          type: 'multiple_choice',
          stage: 'transformation',
          prompt: 'Rewrite the advice for a group: "Mangez plus de légumes."',
          content: {"options":["Vous mangez plus de légumes.","Tu mangez plus de légumes.","Il mange plus de légumes.","Nous mangeons plus de légumes."]},
          answer: 'Vous mangez plus de légumes.',
          explanation: 'Second person plural uses "vous" with the imperative form.',
        },
        {
          id: 's-24',
          learningItemId: 'activite-physique',
          type: 'pronunciation',
          stage: 'production',
          prompt: 'Pronounce the following sentence',
          content: {"sentence":"L'activité physique régulière protège la santé."},
          answer: 'L\'activité physique régulière protège la santé.',
          explanation: '',
        },
      ],
    },
    {
      id: 'sante-argumenter',
      title: 'Argumenter sur la santé',
      learningItemIds: ['avoir-mal-a', 'on-devrait'],
      exercises: [
        {
          id: 's-13',
          learningItemId: 'avoir-mal-a',
          type: 'multiple_choice',
          stage: 'recognition',
          prompt: 'What does "J\u2019ai mal à la tête" mean?',
          content: { options: ["I have a headache", "I have a cold", "I'm dizzy", "I'm hungry"] },
          answer: 'I have a headache',
          explanation: '"Avoir mal à la tête" literally means to have a pain in the head.',
        },
        {
          id: 's-14',
          learningItemId: 'avoir-mal-a',
          type: 'fill_blank',
          stage: 'context',
          prompt: 'Complete the sentence',
          content: {
            sentence: "J'ai ______ à la tête depuis ce matin.",
            options: ['mal', 'maux', 'malle', 'ma'],
          },
          answer: 'mal',
          explanation: 'The expression is "avoir mal à" — singular "mal."',
        },
        {
          id: 's-15',
          learningItemId: 'on-devrait',
          type: 'multiple_choice',
          stage: 'recognition',
          prompt: 'What does "On devrait" express?',
          content: { options: ['A suggestion', 'A certainty', 'A refusal', 'A memory'] },
          answer: 'A suggestion',
          explanation: '"On devrait" = "we should" — a suggestion or gentle advice.',
        },
        {
          id: 's-16',
          learningItemId: 'on-devrait',
          type: 'fill_blank',
          stage: 'context',
          prompt: 'Complete the sentence',
          content: {
            sentence: "On ______ faire plus d'exercice.",
            options: ['devrait', 'devrais', 'dirait', 'devait'],
          },
          answer: 'devrait',
          explanation: '"On" takes the third-person singular conditional "devrait."',
        },
        {
          id: 's-17',
          learningItemId: 'prendre-soin-de',
          type: 'pronunciation',
          stage: 'production',
          prompt: 'Say the sentence aloud.',
          content: { sentence: 'Il faut prendre soin de son sommeil.' },
          answer: 'Il faut prendre soin de son sommeil.',
          explanation: '"Il faut" + "prendre soin de" + the thing cared for.',
        },
        {
          id: 's-18',
          learningItemId: 'on-devrait',
          type: 'pronunciation',
          stage: 'production',
          prompt: 'Say the sentence aloud.',
          content: { sentence: "On devrait faire plus d'exercice." },
          answer: "On devrait faire plus d'exercice.",
          explanation: '"On devrait" + infinitive — a climate of suggestion for advice.',
        },
      
        {
          id: 's-25',
          learningItemId: 'avoir-mal-a',
          type: 'multiple_choice',
          stage: 'recognition',
          prompt: 'Choose the correct translation of "Il a mal au dos."',
          content: {"options":["He has a sore back","He has a cold","He is tired","He is hungry"]},
          answer: 'He has a sore back',
          explanation: '"Il a mal au dos" means he has pain in his back.',
        },
        {
          id: 's-26',
          learningItemId: 'avoir-mal-a',
          type: 'fill_blank',
          stage: 'context',
          prompt: 'Complete the sentence',
          content: {"sentence":"Nous ________ à l'épaule depuis l'entraînement.","options":["mal","maux","malle","ma"]},
          answer: 'mal',
          explanation: 'The expression is "avoir mal à" — singular "mal."',
        },
        {
          id: 's-27',
          learningItemId: 'avoir-mal-a',
          type: 'pronunciation',
          stage: 'production',
          prompt: 'Pronounce the full sentence',
          content: {"sentence":"J’ai mal à la gorge."},
          answer: 'J’ai mal à la gorge.',
          explanation: 'Practice the pronunciation of "avoir mal à la gorge."',
        },
        {
          id: 's-28',
          learningItemId: 'on-devrait',
          type: 'multiple_choice',
          stage: 'recognition',
          prompt: 'What does "On devrait consulter un médecin" mean?',
          content: {"options":["We should see a doctor","We should ignore the pain","We should exercise more","We should eat healthy"]},
          answer: 'We should see a doctor',
          explanation: '"On devrait consulter un médecin" means we should see a doctor.',
        },
        {
          id: 's-29',
          learningItemId: 'on-devrait',
          type: 'fill_blank',
          stage: 'context',
          prompt: 'Complete the sentence',
          content: {"sentence":"On ________ un peu de repos.","options":["devrait","devait","devons","devrai"]},
          answer: 'devrait',
          explanation: 'The correct form is "devrait" for the impersonal "on."',
        },
        {
          id: 's-30',
          learningItemId: 'on-devrait',
          type: 'translation',
          stage: 'recall',
          prompt: 'Translate into French: "We should take a break."',
          content: {"options":["Nous devrions prendre une pause.","Nous devons prendre une pause.","Nous devions prendre une pause.","Nous devrons prendre une pause."]},
          answer: 'Nous devrions prendre une pause.',
          explanation: 'The appropriate construction is "nous devrions" for a suggestion.',
        },
        {
          id: 's-31',
          learningItemId: 'on-devrait',
          type: 'pronunciation',
          stage: 'production',
          prompt: 'Pronounce the full sentence',
          content: {"sentence":"On devrait rester hydraté."},
          answer: 'On devrait rester hydraté.',
          explanation: 'Practice the pronunciation of "on devrait rester hydraté."',
        },
        {
          id: 's-32',
          learningItemId: 'on-devrait',
          type: 'fill_blank',
          stage: 'completion',
          prompt: 'Complete the sentence',
          content: {"sentence":"On ________ faire plus de pauses quand on travaille longtemps.","options":["devrait","devait","devons","devrai"]},
          answer: 'devrait',
          explanation: 'The correct form is "devrait" for the impersonal "on."',
        },
      ],
    },
  ],
}

export const items = {
  'rendez-vous': {
    id: 'rendez-vous',
    type: 'vocabulary',
    word: 'rendez-vous',
    meaning: 'appointment',
    partOfSpeech: 'noun (m.)',
    level: 'B1',
    topic: 'La santé',
    example: 'Je vais prendre un rendez-vous chez le médecin.',
    related: ['consultation'],
  },
  symptome: {
    id: 'symptome',
    type: 'vocabulary',
    word: 'symptôme',
    meaning: 'symptom',
    partOfSpeech: 'noun (m.)',
    level: 'B1',
    topic: 'La santé',
    example: 'Les symptômes de la grippe sont bien connus.',
    related: ['signe'],
  },
  traitement: {
    id: 'traitement',
    type: 'vocabulary',
    word: 'traitement',
    meaning: 'treatment',
    partOfSpeech: 'noun (m.)',
    level: 'B1',
    topic: 'La santé',
    example: 'Ce traitement doit être suivi pendant deux semaines.',
    related: ['médicament'],
  },
  fatigue: {
    id: 'fatigue',
    type: 'vocabulary',
    word: 'fatigue',
    meaning: 'tiredness',
    partOfSpeech: 'noun (f.)',
    level: 'B1',
    topic: 'La santé',
    example: "La fatigue peut venir d'un manque de sommeil.",
    related: ['épuisement'],
  },
  'activite-physique': {
    id: 'activite-physique',
    type: 'vocabulary',
    word: 'activité physique',
    meaning: 'physical activity',
    partOfSpeech: 'noun (f.)',
    level: 'B1',
    topic: 'La santé',
    example: "L'activité physique régulière protège la santé.",
    related: ['sport', 'exercice'],
  },

  'avoir-mal-a': {
    id: 'avoir-mal-a',
    type: 'phrase',
    phrase: 'Avoir mal à',
    meaning: 'To have a pain in / be sore',
    function: 'Describing symptoms',
    level: 'B1',
    topic: 'La santé',
    tefUsage: 'Expression orale — décrire des symptômes',
    example: "J'ai mal à la tête depuis ce matin.",
    related: ['Avoir des courbatures'],
    conjugation: {
      je: "J'ai mal à",
      tu: "Tu as mal à",
      ilElle: "Il/Elle a mal à",
      nous: "Nous avons mal à",
      vous: "Vous avez mal à",
      ilsElles: "Ils/Elles ont mal à",
    },
  },
  'prendre-soin-de': {
    id: 'prendre-soin-de',
    type: 'phrase',
    phrase: 'Prendre soin de',
    meaning: 'To take care of',
    function: 'Advice / care',
    level: 'B1',
    topic: 'La santé',
    tefUsage: 'Expression orale / écrite — conseil',
    example: 'Il faut prendre soin de son sommeil.',
    related: ["S'occuper de"],
    conjugation: {
      je: 'prends soin de',
      tu: 'prends soin de',
      ilElle: 'prend soin de',
      nous: 'prenons soin de',
      vous: 'prenez soin de',
      ilsElles: 'prennent soin de',
    },
  },
  'on-devrait': {
    id: 'on-devrait',
    type: 'phrase',
    phrase: 'On devrait',
    meaning: 'We should',
    function: 'Suggestion / advice',
    level: 'B1',
    topic: 'La santé',
    tefUsage: 'Expression orale — donner un conseil',
    example: "On devrait faire plus d'exercice.",
    related: ['Il serait bon de'],
    conjugation: {
      je: 'devrais',
      tu: 'devrais',
      ilElle: 'devrait',
      nous: 'devrions',
      vous: 'devriez',
      ilsElles: 'devraient',
    },
    tense: 'conditional',
  },

  'imperatif-conseils': {
    id: 'imperatif-conseils',
    type: 'grammar',
    title: 'The imperative for advice',
    level: 'B1',
    explanation:
      'Give advice directly with the imperative: mangez, buvez, reposez-vous. The subject pronoun disappears.',
    examples: ['Mangez plus de légumes.', "Buvez beaucoup d'eau.", 'Reposez-vous ce week-end.'],
    counterexamples: ['Vous reposez-vous ce week-end ? (a question — the imperative drops the subject: "reposez-vous")'],
  },
}