// Hand-authored TEF theme unit (spec §3.2.1) — "La société" (Society). Part of the full TEF theme
// coverage in the Learn path. Exports the same { unit, items } shape as generated units
// (spec §3.2.6). All exercises are tap-only (spec §3.2.2).

export const unit = {
  id: 'societe',
  title: 'La société',
  description: 'Discuss citizenship, solidarity, and the values of the community.',
  lessons: [
    {
      id: 'societe-vocabulaire',
      title: 'Vocabulaire de la société',
      learningItemIds: ['benevolat', 'solidarite', 'association', 'integration'],
      exercises: [
        {
          id: 'soc-1',
          learningItemId: 'benevolat',
          type: 'multiple_choice',
          stage: 'recognition',
          prompt: 'What does "le bénévolat" mean?',
          content: { options: ['volunteering', 'a benefit', 'a bonus', 'a ballot'] },
          answer: 'volunteering',
          explanation: '"Le bénévolat" is "volunteering" — giving time without pay.',
        },
        {
          id: 'soc-2',
          learningItemId: 'solidarite',
          type: 'multiple_choice',
          stage: 'recognition',
          prompt: 'What does "la solidarité" mean?',
          content: { options: ['solidarity', 'solitude', 'solidity', 'salary'] },
          answer: 'solidarity',
          explanation: '"La solidarité" is "solidarity" — mutual support.',
        },
        {
          id: 'soc-3',
          learningItemId: 'integration',
          type: 'translation',
          stage: 'recall',
          prompt: 'Translate: integration',
          content: { direction: 'en_to_fr', options: ['intégration', 'intelligence', 'internet', 'installation'] },
          answer: 'intégration',
          explanation: '"Integration" translates to "l\u2019intégration."',
        },
        {
          id: 'soc-4',
          learningItemId: 'association',
          type: 'translation',
          stage: 'recall',
          prompt: 'Translate: charity / association',
          content: { direction: 'en_to_fr', options: ['association', 'assemblée', 'attention', 'accélération'] },
          answer: 'association',
          explanation: 'A charity is "une association."',
        },
        {
          id: 'soc-5',
          learningItemId: 'benevolat',
          type: 'fill_blank',
          stage: 'context',
          prompt: 'Complete the sentence',
          content: {
            sentence: 'Le ______ aide les personnes isolées.',
            options: ['bénévolat', 'bénéfice', 'bien-être', 'boulot'],
          },
          answer: 'bénévolat',
          explanation: '"Le bénévolat" — volunteering — helps isolated people.',
        },
        {
          id: 'soc-6',
          learningItemId: 'solidarite',
          type: 'fill_blank',
          stage: 'context',
          prompt: 'Complete the sentence',
          content: {
            sentence: 'La ______ entre voisins est forte dans les quartiers.',
            options: ['solidarité', 'solitude', 'sécurité', 'société'],
          },
          answer: 'solidarité',
          explanation: '"La solidarité entre voisins" — neighbors supporting each other.',
        },
      
        {
          id: 'soc-19',
          learningItemId: 'benevolat',
          type: 'translation',
          stage: 'recall',
          prompt: 'Translate "bénévolat" into English.',
          content: {"options":["volunteering","benefit","bonus","ballot"]},
          answer: 'volunteering',
          explanation: '"Bénévolat" means "volunteering".',
        },
        {
          id: 'soc-20',
          learningItemId: 'solidarite',
          type: 'multiple_choice',
          stage: 'context',
          prompt: 'Dans quel contexte utiliseriez‑vous le mot "solidarité" ?',
          content: {"options":["Lors d’un débat politique","Lors d’un dîner familial","Lors d’une réunion d’affaires","Lors d’une séance de sport"]},
          answer: 'Lors d’un débat politique',
          explanation: '"Solidarité" is used in political or social contexts.',
        },
        {
          id: 'soc-21',
          learningItemId: 'solidarite',
          type: 'pronunciation',
          stage: 'recall',
          prompt: 'Pronounce the word "solidarité" correctly.',
          content: {"sentence":"solidarité"},
          answer: 'solidarité',
          explanation: 'Listen for the stress on the third syllable.',
        },
        {
          id: 'soc-22',
          learningItemId: 'association',
          type: 'multiple_choice',
          stage: 'recognition',
          prompt: 'What does "association" mean in French?',
          content: {"options":["a sports club","a charity organization","a type of food","a legal document"]},
          answer: 'a charity organization',
          explanation: '"Association" refers to a charitable or non-profit group.',
        },
        {
          id: 'soc-23',
          learningItemId: 'association',
          type: 'fill_blank',
          stage: 'context',
          prompt: 'Elle travaille dans une ________ d\'aide alimentaire.',
          content: {"sentence":"Elle travaille dans une ________ d'aide alimentaire.","options":["association","organisation","entreprise","société"]},
          answer: 'association',
          explanation: 'The correct term is "association".',
        },
        {
          id: 'soc-24',
          learningItemId: 'integration',
          type: 'multiple_choice',
          stage: 'context',
          prompt: 'Which phrase best matches "intégration"?',
          content: {"options":["L’intégration des nouveaux arrivants","La séparation des nouveaux arrivants","La compétition des nouveaux arrivants","La création des nouveaux arrivants"]},
          answer: 'L’intégration des nouveaux arrivants',
          explanation: 'It refers to incorporating newcomers.',
        },
        {
          id: 'soc-25',
          learningItemId: 'solidarite',
          type: 'pronunciation',
          stage: 'recall',
          prompt: 'Pronounce "solidarité" with the correct stress.',
          content: {"sentence":"solidarité"},
          answer: 'solidarité',
          explanation: 'Stress on the third syllable.',
        },
        {
          id: 'soc-26',
          learningItemId: 'benevolat',
          type: 'multiple_choice',
          stage: 'recall',
          prompt: 'Which sentence uses "bénévolat" correctly?',
          content: {"options":["Il a un bénévolat à la maison.","Il a un bénévolat à l’école.","Il fait du bénévolat pour aider les autres.","Il a un bénévolat en cuisine."]},
          answer: 'Il fait du bénévolat pour aider les autres.',
          explanation: 'The noun is used with "faire du".',
        },
      ],
    },
    {
      id: 'societe-idees',
      title: 'Construire des idées',
      learningItemIds: ['subjonctif', 'il-est-important-que', 'egalite'],
      exercises: [
        {
          id: 'soc-7',
          learningItemId: 'subjonctif',
          type: 'multiple_choice',
          stage: 'recognition',
          prompt: 'Which sentence is correct?',
          content: {
            options: [
              "Il est important que chacun ait le droit de s'exprimer.",
              "Il est important que chacun a le droit de s'exprimer.",
            ],
          },
          answer: "Il est important que chacun ait le droit de s'exprimer.",
          explanation: '"Il est important que" triggers the subjunctive: "ait," not "a."',
        },
        {
          id: 'soc-8',
          learningItemId: 'subjonctif',
          type: 'fill_blank',
          stage: 'recognition',
          prompt: 'Complete the sentence',
          content: {
            sentence: "Il est important que chacun ______ le droit de s'exprimer.",
            options: ['ait', 'a', 'est', 'ai'],
          },
          answer: 'ait',
          explanation: 'The subjunctive of "avoir" after "que" is "ait."',
        },
        {
          id: 'soc-9',
          learningItemId: 'egalite',
          type: 'translation',
          stage: 'recall',
          prompt: 'Translate: equality',
          content: { direction: 'en_to_fr', options: ['égalité', 'équipe', 'écart', 'état'] },
          answer: 'égalité',
          explanation: '"Equality" translates to "l\u2019égalité."',
        },
        {
          id: 'soc-10',
          learningItemId: 'il-est-important-que',
          type: 'multiple_choice',
          stage: 'recognition',
          prompt: 'What does "Il est important que" require after it?',
          content: { options: ['The subjunctive', 'The infinitive', 'The future', 'The conditional'] },
          answer: 'The subjunctive',
          explanation: 'Expressions of importance ("il est important que") require the subjunctive.',
        },
        {
          id: 'soc-11',
          learningItemId: 'egalite',
          type: 'fill_blank',
          stage: 'context',
          prompt: 'Complete the sentence',
          content: {
            sentence: "L'______ entre les femmes et les hommes progresse.",
            options: ['égalité', 'écosystème', 'émigration', 'évaluation'],
          },
          answer: 'égalité',
          explanation: '"L\u2019égalité entre les femmes et les hommes" — gender equality.',
        },
        {
          id: 'soc-12',
          learningItemId: 'subjonctif',
          type: 'fill_blank',
          stage: 'context',
          prompt: 'Complete the sentence',
          content: {
            sentence: 'Il faut que les ______ participent.',
            options: ['citoyens', 'citoyen', 'cités', 'civils'],
          },
          answer: 'citoyens',
          explanation: '"Il faut que" also takes the subjunctive — here "participent."',
        },
      
        {
          id: 'soc-27',
          learningItemId: 'il-est-important-que',
          type: 'pronunciation',
          stage: 'production',
          prompt: 'Pronounce the following sentence aloud: "Il est important que les enfants jouent en plein air."',
          content: {"sentence":"Il est important que les enfants jouent en plein air."},
          answer: 'Il est important que les enfants jouent en plein air.',
          explanation: 'Practice the correct intonation for the subjunctive clause.',
        },
        {
          id: 'soc-28',
          learningItemId: 'egalite',
          type: 'pronunciation',
          stage: 'production',
          prompt: 'Say the sentence: "L\'égalité est la base de toute société juste."',
          content: {"sentence":"L'égalité est la base de toute société juste."},
          answer: 'L\'égalité est la base de toute société juste.',
          explanation: 'Focus on the pronunciation of "égalité" and "juste."',
        },
      ],
    },
    {
      id: 'societe-argumenter',
      title: 'Argumenter sur la société',
      learningItemIds: ['avoir-le-droit-de', 'mettre-en-place'],
      exercises: [
        {
          id: 'soc-13',
          learningItemId: 'avoir-le-droit-de',
          type: 'multiple_choice',
          stage: 'recognition',
          prompt: 'What does "Avoir le droit de" mean?',
          content: { options: ['To have the right to', 'To be forced to', 'To be curious to', 'To be late to'] },
          answer: 'To have the right to',
          explanation: '"Avoir le droit de" = "to have the right to."',
        },
        {
          id: 'soc-14',
          learningItemId: 'avoir-le-droit-de',
          type: 'fill_blank',
          stage: 'context',
          prompt: 'Complete the sentence',
          content: {
            sentence: 'Tout le monde a le ______ de voter.',
            options: ['droit', 'droite', 'droits', 'droitier'],
          },
          answer: 'droit',
          explanation: '"Le droit" (singular) is the legal entitlement — "le droit de voter."',
        },
        {
          id: 'soc-15',
          learningItemId: 'mettre-en-place',
          type: 'multiple_choice',
          stage: 'recognition',
          prompt: 'What does "Mettre en place" mean?',
          content: { options: ['To put in place / set up', 'To put away', 'To replace', 'To understand'] },
          answer: 'To put in place / set up',
          explanation: '"Mettre en place" = "to put in place / set up."',
        },
        {
          id: 'soc-16',
          learningItemId: 'mettre-en-place',
          type: 'fill_blank',
          stage: 'context',
          prompt: 'Complete the sentence',
          content: {
            sentence: 'La ville a ______ en place un service de médiation.',
            options: ['mis', 'mise', 'mets', 'mettre'],
          },
          answer: 'mis',
          explanation: 'The passé composé of "mettre" is "mis."',
        },
        {
          id: 'soc-17',
          learningItemId: 'avoir-le-droit-de',
          type: 'pronunciation',
          stage: 'production',
          prompt: 'Say the sentence aloud.',
          content: { sentence: 'Tout le monde a le droit de voter.' },
          answer: 'Tout le monde a le droit de voter.',
          explanation: '"Avoir le droit de" + infinitive.',
        },
        {
          id: 'soc-18',
          learningItemId: 'il-est-important-que',
          type: 'pronunciation',
          stage: 'production',
          prompt: 'Say the sentence aloud.',
          content: { sentence: "Il est important que chacun ait le droit de s'exprimer." },
          answer: "Il est important que chacun ait le droit de s'exprimer.",
          explanation: '"Il est important que" + subjunctive "ait."',
        },
      
        {
          id: 'soc-29',
          learningItemId: 'avoir-le-droit-de',
          type: 'multiple_choice',
          stage: 'recognition',
          prompt: 'Quel est le sens de "Avoir le droit de" ?',
          content: {"options":["To be allowed to","To be forced to","To have the right to","To be curious about"]},
          answer: 'To have the right to',
          explanation: '"Avoir le droit de" means "to have the right to."',
        },
        {
          id: 'soc-30',
          learningItemId: 'avoir-le-droit-de',
          type: 'fill_blank',
          stage: 'context',
          prompt: 'Complétez la phrase',
          content: {"sentence":"Les enfants ont le ______ de jouer dans le parc.","options":["droit","droite","droits","droitier"]},
          answer: 'droit',
          explanation: 'The correct form is "le droit" (singular) for a single right.',
        },
        {
          id: 'soc-31',
          learningItemId: 'avoir-le-droit-de',
          type: 'pronunciation',
          stage: 'completion',
          prompt: 'Prononcez la phrase suivante',
          content: {"sentence":"Il a le droit de participer à l’élection."},
          answer: 'Il a le droit de participer à l’élection.',
          explanation: 'Practice the correct liaison and nasalization.',
        },
        {
          id: 'soc-32',
          learningItemId: 'mettre-en-place',
          type: 'multiple_choice',
          stage: 'recognition',
          prompt: 'Que signifie "mettre en place" ?',
          content: {"options":["To put in place","To take off","To forget","To celebrate"]},
          answer: 'To put in place',
          explanation: '"Mettre en place" means to put something in place or set up.',
        },
        {
          id: 'soc-33',
          learningItemId: 'mettre-en-place',
          type: 'pronunciation',
          stage: 'completion',
          prompt: 'Prononcez la phrase suivante',
          content: {"sentence":"Ils ont mis en place un comité de suivi."},
          answer: 'Ils ont mis en place un comité de suivi.',
          explanation: 'Focus on the past participle agreement.',
        },
      ],
    },
  ],
}

export const items = {
  benevolat: {
    id: 'benevolat',
    type: 'vocabulary',
    word: 'bénévolat',
    meaning: 'volunteering',
    partOfSpeech: 'noun (m.)',
    level: 'B1',
    topic: 'La société',
    example: 'Le bénévolat aide les personnes isolées.',
    related: ['volontariat'],
  },
  egalite: {
    id: 'egalite',
    type: 'vocabulary',
    word: 'égalité',
    meaning: 'equality',
    partOfSpeech: 'noun (f.)',
    level: 'B1',
    topic: 'La société',
    example: "L'égalité entre les femmes et les hommes progresse.",
    related: ['équité'],
  },
  integration: {
    id: 'integration',
    type: 'vocabulary',
    word: 'intégration',
    meaning: 'integration',
    partOfSpeech: 'noun (f.)',
    level: 'B1',
    topic: 'La société',
    example: "L'intégration des nouveaux arrivants demande du temps.",
    related: ['insertion'],
  },
  solidarite: {
    id: 'solidarite',
    type: 'vocabulary',
    word: 'solidarité',
    meaning: 'solidarity',
    partOfSpeech: 'noun (f.)',
    level: 'B1',
    topic: 'La société',
    example: 'La solidarité entre voisins est forte dans les quartiers.',
    related: ['entraide'],
  },
  association: {
    id: 'association',
    type: 'vocabulary',
    word: 'association',
    meaning: 'charity / association',
    partOfSpeech: 'noun (f.)',
    level: 'B1',
    topic: 'La société',
    example: "Elle travaille dans une association d'aide alimentaire.",
    related: ['organisation'],
  },

  'il-est-important-que': {
    id: 'il-est-important-que',
    type: 'phrase',
    phrase: 'Il est important que',
    meaning: "It's important that",
    function: 'Emphasizing a value',
    level: 'B1',
    topic: 'La société',
    tefUsage: 'Expression orale / écrite — défendre une valeur',
    example: "Il est important que chacun ait le droit de s'exprimer.",
    related: ['Il est essentiel que'],
  },
  'avoir-le-droit-de': {
    id: 'avoir-le-droit-de',
    type: 'phrase',
    phrase: 'Avoir le droit de',
    meaning: 'To have the right to',
    function: 'Rights',
    level: 'B1',
    topic: 'La société',
    tefUsage: 'Expression orale — parler des droits',
    example: 'Tout le monde a le droit de voter.',
    related: ['Être autorisé à'],
    conjugation: {
      je: "J'ai le droit de",
      tu: "Tu as le droit de",
      ilElle: "Il/Elle a le droit de",
      nous: "Nous avons le droit de",
      vous: "Vous avez le droit de",
      ilsElles: "Ils/Elles ont le droit de",
    },
  },
  'mettre-en-place': {
    id: 'mettre-en-place',
    type: 'phrase',
    phrase: 'Mettre en place',
    meaning: 'To put in place / set up',
    function: 'Arranging something',
    level: 'B1',
    topic: 'La société',
    tefUsage: 'Expression orale / écrite — décrire une action publique',
    example: 'La ville a mis en place un service de médiation.',
    related: ['Organiser'],
    conjugation: {
      je: 'mets en place',
      tu: 'mets en place',
      ilElle: 'met en place',
      nous: 'mettons en place',
      vous: 'mettez en place',
      ilsElles: 'mettent en place',
    },
  },

  subjonctif: {
    id: 'subjonctif',
    type: 'grammar',
    title: 'The subjunctive after il est important que / il faut que',
    level: 'B1',
    explanation:
      'After expressions of importance or necessity (il est important que, il faut que, il est essentiel que), the verb goes into the subjunctive: que chacun ait, que les gens fassent.',
    examples: ["Il est important que chacun ait le droit de s'exprimer.", 'Il faut que les citoyens participent.'],
    counterexamples: [
      "Il est important que chacun a le droit de s'exprimer. (incorrect — \"que\" triggers the subjunctive \"ait\")",
    ],
  },
}