// Hand-authored TEF theme unit (spec §3.2.1) — "La société" (Society). Part of the full TEF theme
// coverage in the Learn path. Exports the same { unit, items } shape as generated units
// (spec §3.2.6). All exercises are tap-only (spec §3.2.2).

export const unit = {
  id: 'societe',
  title: 'La société',
  description: 'Discuss citizenship, solidarity, and the values of the community.',
  lessons: [
    {
      id: 'societe-vocabulaire',
      title: 'Vocabulaire de la société',
      learningItemIds: ['benevolat', 'solidarite', 'association', 'integration'],
      exercises: [
        {
          id: 'soc-1',
          learningItemId: 'benevolat',
          type: 'multiple_choice',
          stage: 'recognition',
          prompt: 'What does "le bénévolat" mean?',
          content: { options: ['volunteering', 'a benefit', 'a bonus', 'a ballot'] },
          answer: 'volunteering',
          explanation: '"Le bénévolat" is "volunteering" — giving time without pay.',
        },
        {
          id: 'soc-2',
          learningItemId: 'solidarite',
          type: 'multiple_choice',
          stage: 'recognition',
          prompt: 'What does "la solidarité" mean?',
          content: { options: ['solidarity', 'solitude', 'solidity', 'salary'] },
          answer: 'solidarity',
          explanation: '"La solidarité" is "solidarity" — mutual support.',
        },
        {
          id: 'soc-3',
          learningItemId: 'integration',
          type: 'translation',
          stage: 'recall',
          prompt: 'Translate: integration',
          content: { direction: 'en_to_fr', options: ['intégration', 'intelligence', 'internet', 'installation'] },
          answer: 'intégration',
          explanation: '"Integration" translates to "l\u2019intégration."',
        },
        {
          id: 'soc-4',
          learningItemId: 'association',
          type: 'translation',
          stage: 'recall',
          prompt: 'Translate: charity / association',
          content: { direction: 'en_to_fr', options: ['association', 'assemblée', 'attention', 'accélération'] },
          answer: 'association',
          explanation: 'A charity is "une association."',
        },
        {
          id: 'soc-5',
          learningItemId: 'benevolat',
          type: 'fill_blank',
          stage: 'context',
          prompt: 'Complete the sentence',
          content: {
            sentence: 'Le ______ aide les personnes isolées.',
            options: ['bénévolat', 'bénéfice', 'bien-être', 'boulot'],
          },
          answer: 'bénévolat',
          explanation: '"Le bénévolat" — volunteering — helps isolated people.',
        },
        {
          id: 'soc-6',
          learningItemId: 'solidarite',
          type: 'fill_blank',
          stage: 'context',
          prompt: 'Complete the sentence',
          content: {
            sentence: 'La ______ entre voisins est forte dans les quartiers.',
            options: ['solidarité', 'solitude', 'sécurité', 'société'],
          },
          answer: 'solidarité',
          explanation: '"La solidarité entre voisins" — neighbors supporting each other.',
        },
      ],
    },
    {
      id: 'societe-idees',
      title: 'Construire des idées',
      learningItemIds: ['subjonctif', 'il-est-important-que', 'egalite'],
      exercises: [
        {
          id: 'soc-7',
          learningItemId: 'subjonctif',
          type: 'multiple_choice',
          stage: 'recognition',
          prompt: 'Which sentence is correct?',
          content: {
            options: [
              "Il est important que chacun ait le droit de s'exprimer.",
              "Il est important que chacun a le droit de s'exprimer.",
            ],
          },
          answer: "Il est important que chacun ait le droit de s'exprimer.",
          explanation: '"Il est important que" triggers the subjunctive: "ait," not "a."',
        },
        {
          id: 'soc-8',
          learningItemId: 'subjonctif',
          type: 'fill_blank',
          stage: 'recognition',
          prompt: 'Complete the sentence',
          content: {
            sentence: "Il est important que chacun ______ le droit de s'exprimer.",
            options: ['ait', 'a', 'est', 'ai'],
          },
          answer: 'ait',
          explanation: 'The subjunctive of "avoir" after "que" is "ait."',
        },
        {
          id: 'soc-9',
          learningItemId: 'egalite',
          type: 'translation',
          stage: 'recall',
          prompt: 'Translate: equality',
          content: { direction: 'en_to_fr', options: ['égalité', 'équipe', 'écart', 'état'] },
          answer: 'égalité',
          explanation: '"Equality" translates to "l\u2019égalité."',
        },
        {
          id: 'soc-10',
          learningItemId: 'il-est-important-que',
          type: 'multiple_choice',
          stage: 'recognition',
          prompt: 'What does "Il est important que" require after it?',
          content: { options: ['The subjunctive', 'The infinitive', 'The future', 'The conditional'] },
          answer: 'The subjunctive',
          explanation: 'Expressions of importance ("il est important que") require the subjunctive.',
        },
        {
          id: 'soc-11',
          learningItemId: 'egalite',
          type: 'fill_blank',
          stage: 'context',
          prompt: 'Complete the sentence',
          content: {
            sentence: "L'______ entre les femmes et les hommes progresse.",
            options: ['égalité', 'écosystème', 'émigration', 'évaluation'],
          },
          answer: 'égalité',
          explanation: '"L\u2019égalité entre les femmes et les hommes" — gender equality.',
        },
        {
          id: 'soc-12',
          learningItemId: 'subjonctif',
          type: 'fill_blank',
          stage: 'context',
          prompt: 'Complete the sentence',
          content: {
            sentence: 'Il faut que les ______ participent.',
            options: ['citoyens', 'citoyen', 'cités', 'civils'],
          },
          answer: 'citoyens',
          explanation: '"Il faut que" also takes the subjunctive — here "participent."',
        },
      ],
    },
    {
      id: 'societe-argumenter',
      title: 'Argumenter sur la société',
      learningItemIds: ['avoir-le-droit-de', 'mettre-en-place'],
      exercises: [
        {
          id: 'soc-13',
          learningItemId: 'avoir-le-droit-de',
          type: 'multiple_choice',
          stage: 'recognition',
          prompt: 'What does "Avoir le droit de" mean?',
          content: { options: ['To have the right to', 'To be forced to', 'To be curious to', 'To be late to'] },
          answer: 'To have the right to',
          explanation: '"Avoir le droit de" = "to have the right to."',
        },
        {
          id: 'soc-14',
          learningItemId: 'avoir-le-droit-de',
          type: 'fill_blank',
          stage: 'context',
          prompt: 'Complete the sentence',
          content: {
            sentence: 'Tout le monde a le ______ de voter.',
            options: ['droit', 'droite', 'droits', 'droitier'],
          },
          answer: 'droit',
          explanation: '"Le droit" (singular) is the legal entitlement — "le droit de voter."',
        },
        {
          id: 'soc-15',
          learningItemId: 'mettre-en-place',
          type: 'multiple_choice',
          stage: 'recognition',
          prompt: 'What does "Mettre en place" mean?',
          content: { options: ['To put in place / set up', 'To put away', 'To replace', 'To understand'] },
          answer: 'To put in place / set up',
          explanation: '"Mettre en place" = "to put in place / set up."',
        },
        {
          id: 'soc-16',
          learningItemId: 'mettre-en-place',
          type: 'fill_blank',
          stage: 'context',
          prompt: 'Complete the sentence',
          content: {
            sentence: 'La ville a ______ en place un service de médiation.',
            options: ['mis', 'mise', 'mets', 'mettre'],
          },
          answer: 'mis',
          explanation: 'The passé composé of "mettre" is "mis."',
        },
        {
          id: 'soc-17',
          learningItemId: 'avoir-le-droit-de',
          type: 'production',
          stage: 'production',
          prompt: 'Build the sentence: "Tout le monde a le droit de voter."',
          content: { tiles: ['Tout', 'le', 'monde', 'a', 'le', 'droit', 'de', 'voter.', 'doit', 'vote'] },
          answer: 'Tout le monde a le droit de voter.',
          explanation: '"Avoir le droit de" + infinitive.',
        },
        {
          id: 'soc-18',
          learningItemId: 'il-est-important-que',
          type: 'production',
          stage: 'production',
          prompt: 'Build the sentence: "Il est important que chacun ait le droit de s\u2019exprimer."',
          content: {
            tiles: ['Il', 'est', 'important', 'que', 'chacun', 'ait', 'le', 'droit', 'de', "s'exprimer.", 'a', 'doit'],
          },
          answer: "Il est important que chacun ait le droit de s'exprimer.",
          explanation: '"Il est important que" + subjunctive "ait."',
        },
      ],
    },
  ],
}

export const items = {
  benevolat: {
    id: 'benevolat',
    type: 'vocabulary',
    word: 'bénévolat',
    meaning: 'volunteering',
    partOfSpeech: 'noun (m.)',
    level: 'B1',
    topic: 'La société',
    example: 'Le bénévolat aide les personnes isolées.',
    related: ['volontariat'],
  },
  egalite: {
    id: 'egalite',
    type: 'vocabulary',
    word: 'égalité',
    meaning: 'equality',
    partOfSpeech: 'noun (f.)',
    level: 'B1',
    topic: 'La société',
    example: "L'égalité entre les femmes et les hommes progresse.",
    related: ['équité'],
  },
  integration: {
    id: 'integration',
    type: 'vocabulary',
    word: 'intégration',
    meaning: 'integration',
    partOfSpeech: 'noun (f.)',
    level: 'B1',
    topic: 'La société',
    example: "L'intégration des nouveaux arrivants demande du temps.",
    related: ['insertion'],
  },
  solidarite: {
    id: 'solidarite',
    type: 'vocabulary',
    word: 'solidarité',
    meaning: 'solidarity',
    partOfSpeech: 'noun (f.)',
    level: 'B1',
    topic: 'La société',
    example: 'La solidarité entre voisins est forte dans les quartiers.',
    related: ['entraide'],
  },
  association: {
    id: 'association',
    type: 'vocabulary',
    word: 'association',
    meaning: 'charity / association',
    partOfSpeech: 'noun (f.)',
    level: 'B1',
    topic: 'La société',
    example: "Elle travaille dans une association d'aide alimentaire.",
    related: ['organisation'],
  },

  'il-est-important-que': {
    id: 'il-est-important-que',
    type: 'phrase',
    phrase: 'Il est important que',
    meaning: "It's important that",
    function: 'Emphasizing a value',
    level: 'B1',
    topic: 'La société',
    tefUsage: 'Expression orale / écrite — défendre une valeur',
    example: "Il est important que chacun ait le droit de s'exprimer.",
    related: ['Il est essentiel que'],
  },
  'avoir-le-droit-de': {
    id: 'avoir-le-droit-de',
    type: 'phrase',
    phrase: 'Avoir le droit de',
    meaning: 'To have the right to',
    function: 'Rights',
    level: 'B1',
    topic: 'La société',
    tefUsage: 'Expression orale — parler des droits',
    example: 'Tout le monde a le droit de voter.',
    related: ['Être autorisé à'],
  },
  'mettre-en-place': {
    id: 'mettre-en-place',
    type: 'phrase',
    phrase: 'Mettre en place',
    meaning: 'To put in place / set up',
    function: 'Arranging something',
    level: 'B1',
    topic: 'La société',
    tefUsage: 'Expression orale / écrite — décrire une action publique',
    example: 'La ville a mis en place un service de médiation.',
    related: ['Organiser'],
  },

  subjonctif: {
    id: 'subjonctif',
    type: 'grammar',
    title: 'The subjunctive after il est important que / il faut que',
    level: 'B1',
    explanation:
      'After expressions of importance or necessity (il est important que, il faut que, il est essentiel que), the verb goes into the subjunctive: que chacun ait, que les gens fassent.',
    examples: ["Il est important que chacun ait le droit de s'exprimer.", 'Il faut que les citoyens participent.'],
    counterexamples: [
      "Il est important que chacun a le droit de s'exprimer. (incorrect — \"que\" triggers the subjunctive \"ait\")",
    ],
  },
}