// Hand-authored TEF theme unit (spec §3.2.1) — "Le sport" (Sport). Part of the full TEF theme
// coverage in the Learn path. Exports the same { unit, items } shape as generated units
// (spec §3.2.6). All exercises are tap-only (spec §3.2.2).

export const unit = {
  id: 'sport',
  title: 'Le sport',
  description: 'Talk about sports, exercise, and staying active in French.',
  lessons: [
    {
      id: 'sport-vocabulaire',
      title: 'Vocabulaire du sport',
      learningItemIds: ['equipe', 'match', 'entrainement', 'competition'],
      exercises: [
        {
          id: 'spr-1',
          learningItemId: 'equipe',
          type: 'multiple_choice',
          stage: 'recognition',
          prompt: 'What does "une équipe" mean?',
          content: { options: ['a team', 'a crowd', 'a score', 'a coach'] },
          answer: 'a team',
          explanation: '"Une équipe" is a "team."',
        },
        {
          id: 'spr-2',
          learningItemId: 'match',
          type: 'multiple_choice',
          stage: 'recognition',
          prompt: 'What does "un match" mean?',
          content: { options: ['a match', 'a referee', 'a goal', 'a stadium'] },
          answer: 'a match',
          explanation: '"Un match" is a "match."',
        },
        {
          id: 'spr-3',
          learningItemId: 'entrainement',
          type: 'translation',
          stage: 'recall',
          prompt: 'Translate: training / practice',
          content: { direction: 'en_to_fr', options: ['entraînement', 'entrée', 'entretien', 'entrave'] },
          answer: 'entraînement',
          explanation: '"Training" translates to "l\u2019entraînement."',
        },
        {
          id: 'spr-4',
          learningItemId: 'competition',
          type: 'translation',
          stage: 'recall',
          prompt: 'Translate: competition',
          content: { direction: 'en_to_fr', options: ['compétition', 'compliment', 'compétence', 'compréhension'] },
          answer: 'compétition',
          explanation: '"Competition" translates to "la compétition."',
        },
        {
          id: 'spr-5',
          learningItemId: 'equipe',
          type: 'fill_blank',
          stage: 'context',
          prompt: 'Complete the sentence',
          content: {
            sentence: 'Notre ______ a gagné le match de samedi.',
            options: ['équipe', 'épée', 'étape', 'enquête'],
          },
          answer: 'équipe',
          explanation: '"Notre équipe a gagné" — our team won.',
        },
        {
          id: 'spr-6',
          learningItemId: 'match',
          type: 'fill_blank',
          stage: 'context',
          prompt: 'Complete the sentence',
          content: {
            sentence: 'Le ______ commence à 20 heures.',
            options: ['match', 'mage', 'marché', 'mer'],
          },
          answer: 'match',
          explanation: '"Le match commence" — the match starts.',
        },
      
        {
          id: 'spr-19',
          learningItemId: 'equipe',
          type: 'multiple_choice',
          stage: 'recall',
          prompt: 'Choose the correct French phrase for "team".',
          content: {"options":["une équipe","un match","un entraînement","une compétition"]},
          answer: 'une équipe',
          explanation: '"Team" translates to "une équipe".',
        },
        {
          id: 'spr-20',
          learningItemId: 'match',
          type: 'fill_blank',
          stage: 'context',
          prompt: 'Le ______ commence à 18 heures.',
          content: {"sentence":"Le ______ commence à 18 heures.","options":["match","entraînement","équipe","compétition"]},
          answer: 'match',
          explanation: 'The sentence refers to a game that starts at 18h.',
        },
        {
          id: 'spr-21',
          learningItemId: 'entrainement',
          type: 'multiple_choice',
          stage: 'recall',
          prompt: 'Which word means "training" in French?',
          content: {"options":["compétition","match","équipe","entraînement"]},
          answer: 'entraînement',
          explanation: '"Training" is "entraînement".',
        },
        {
          id: 'spr-22',
          learningItemId: 'competition',
          type: 'translation',
          stage: 'recognition',
          prompt: 'Translate "competition" into French.',
          content: {"options":["compétition","match","équipe","entraînement"]},
          answer: 'compétition',
          explanation: '"Competition" translates to "compétition".',
        },
        {
          id: 'spr-23',
          learningItemId: 'match',
          type: 'multiple_choice',
          stage: 'context',
          prompt: 'Quel mot désigne une rencontre sportive?',
          content: {"options":["compétition","entraînement","match","équipe"]},
          answer: 'match',
          explanation: 'A sports encounter is a "match".',
        },
        {
          id: 'spr-24',
          learningItemId: 'entrainement',
          type: 'fill_blank',
          stage: 'completion',
          prompt: 'Ils ont un ______ deux fois par semaine.',
          content: {"sentence":"Ils ont un ______ deux fois par semaine.","options":["match","compétition","entraînement","équipe"]},
          answer: 'entraînement',
          explanation: 'They have training twice a week.',
        },
        {
          id: 'spr-25',
          learningItemId: 'competition',
          type: 'multiple_choice',
          stage: 'recall',
          prompt: 'What is the feminine noun for "championnat"?',
          content: {"options":["compétition","match","équipe","entraînement"]},
          answer: 'compétition',
          explanation: 'The feminine noun for championship is "compétition".',
        },
        {
          id: 'spr-26',
          learningItemId: 'equipe',
          type: 'translation',
          stage: 'recall',
          prompt: 'Translate "team" into French.',
          content: {"options":["match","compétition","équipe","entraînement"]},
          answer: 'équipe',
          explanation: '"Team" translates to "équipe".',
        },
      ],
    },
    {
      id: 'sport-idees',
      title: 'Construire des idées',
      learningItemIds: ['faire-de-jouer-a', 'rester-en-forme', 'adversaire'],
      exercises: [
        {
          id: 'spr-7',
          learningItemId: 'faire-de-jouer-a',
          type: 'multiple_choice',
          stage: 'recognition',
          prompt: 'Which sentence is correct?',
          content: {
            options: ['Je joue au foot le samedi.', 'Je joue du foot le samedi.', 'Je fais au foot le samedi.'],
          },
          answer: 'Je joue au foot le samedi.',
          explanation: 'Ball/team sports take "jouer à": "jouer au foot."',
        },
        {
          id: 'spr-8',
          learningItemId: 'faire-de-jouer-a',
          type: 'fill_blank',
          stage: 'transformation',
          prompt: 'Complete the sentence',
          content: {
            sentence: 'Je fais ______ natation deux fois par semaine.',
            options: ['de la', 'du', 'des', 'de'],
          },
          answer: 'de la',
          explanation: 'Individual sports take "faire de": "faire de la natation."',
        },
        {
          id: 'spr-9',
          learningItemId: 'rester-en-forme',
          type: 'multiple_choice',
          stage: 'recognition',
          prompt: 'What does "Rester en forme" mean?',
          content: { options: ['To stay in shape', 'To lose weight', 'To rest completely', 'To retire'] },
          answer: 'To stay in shape',
          explanation: '"Rester en forme" means "to stay in shape."',
        },
        {
          id: 'spr-10',
          learningItemId: 'rester-en-forme',
          type: 'fill_blank',
          stage: 'context',
          prompt: 'Complete the sentence',
          content: {
            sentence: 'Faire du sport aide à ______ en forme.',
            options: ['rester', 'resterais', 'resté', 'resteront'],
          },
          answer: 'rester',
          explanation: 'After "aide à", the verb stays in the infinitive: "rester en forme."',
        },
        {
          id: 'spr-11',
          learningItemId: 'adversaire',
          type: 'translation',
          stage: 'recall',
          prompt: 'Translate: opponent',
          content: { direction: 'en_to_fr', options: ['adversaire', 'aventure', 'avantage', 'avertissement'] },
          answer: 'adversaire',
          explanation: '"Opponent" translates to "l\u2019adversaire."',
        },
        {
          id: 'spr-12',
          learningItemId: 'adversaire',
          type: 'fill_blank',
          stage: 'context',
          prompt: 'Complete the sentence',
          content: {
            sentence: 'Notre ______ était très fort, mais nous avons gagné.',
            options: ['adversaire', 'administrateur', 'attracteur', 'adaptateur'],
          },
          answer: 'adversaire',
          explanation: '"Notre adversaire" — our opponent.',
        },
      
        {
          id: 'spr-27',
          learningItemId: 'faire-de-jouer-a',
          type: 'multiple_choice',
          stage: 'recognition',
          prompt: 'Which sentence uses the correct verb for a team sport?',
          content: {"options":["Je fais du basket.","Je joue au basket.","Je fais au basket.","Je joue du basket."]},
          answer: 'Je joue au basket.',
          explanation: 'Team sports use "jouer à": "jouer au basket."',
        },
        {
          id: 'spr-28',
          learningItemId: 'faire-de-jouer-a',
          type: 'fill_blank',
          stage: 'transformation',
          prompt: 'Complete the sentence with the right form of "faire" for an individual sport.',
          content: {"sentence":"Il ______ du tennis deux fois par semaine.","options":["fait de","fait du","fait des","fait"]},
          answer: 'fait de',
          explanation: 'Individual sports use "faire de": "faire du tennis."',
        },
        {
          id: 'spr-29',
          learningItemId: 'faire-de-jouer-a',
          type: 'multiple_choice',
          stage: 'recall',
          prompt: 'Choose the correct form of "jouer" for a ball sport for the pronoun "nous".',
          content: {"options":["Nous jouons au volley.","Nous jouons du volley.","Nous faisons au volley.","Nous faisons du volley."]},
          answer: 'Nous jouons au volley.',
          explanation: 'Team sports use "jouer à": "jouer au volley."',
        },
        {
          id: 'spr-30',
          learningItemId: 'faire-de-jouer-a',
          type: 'translation',
          stage: 'context',
          prompt: 'Translate: "She plays handball every Sunday."',
          content: {"options":["Elle joue au handball chaque dimanche.","Elle joue du handball chaque dimanche.","Elle fait au handball chaque dimanche.","Elle fait du handball chaque dimanche."]},
          answer: 'Elle joue au handball chaque dimanche.',
          explanation: 'Ball sports use "jouer à".',
        },
        {
          id: 'spr-31',
          learningItemId: 'faire-de-jouer-a',
          type: 'pronunciation',
          stage: 'production',
          prompt: 'Pronounce the following sentence correctly.',
          content: {"sentence":"Ils jouent au rugby."},
          answer: 'Ils jouent au rugby.',
          explanation: 'Team sports use "jouer à".',
        },
        {
          id: 'spr-32',
          learningItemId: 'rester-en-forme',
          type: 'multiple_choice',
          stage: 'recognition',
          prompt: 'Which sentence expresses staying in shape?',
          content: {"options":["Je reste en forme en faisant du sport.","Je reste en forme en mangeant du pain.","Je reste en forme en dormant.","Je reste en forme en lisant."]},
          answer: 'Je reste en forme en faisant du sport.',
          explanation: 'The phrase means "to stay in shape".',
        },
        {
          id: 'spr-33',
          learningItemId: 'adversaire',
          type: 'multiple_choice',
          stage: 'recognition',
          prompt: 'Which sentence correctly uses "adversaire"?',
          content: {"options":["L'adversaire est prêt.","Le rival est prêt.","Le compétiteur est prêt.","L'ennemi est prêt."]},
          answer: 'L\'adversaire est prêt.',
          explanation: 'The phrase means "tough opponent."',
        },
        {
          id: 'spr-34',
          learningItemId: 'adversaire',
          type: 'fill_blank',
          stage: 'context',
          prompt: 'Complete the sentence about a game.',
          content: {"sentence":"Notre adversaire était très fort, mais nous _______.","options":["avons gagné","avons perdu","avons gagné.","avons perdu."]},
          answer: 'avons gagné',
          explanation: 'The phrase refers to the opponent.',
        },
        {
          id: 'spr-35',
          learningItemId: 'adversaire',
          type: 'translation',
          stage: 'recall',
          prompt: 'Translate: "The opponent was difficult to beat."',
          content: {"options":["L'adversaire était difficile à battre.","L'adversaire était facile à battre.","Le rival était difficile à battre.","Le rival était facile à battre."]},
          answer: 'L\'adversaire était difficile à battre.',
          explanation: 'Direct translation.',
        },
        {
          id: 'spr-36',
          learningItemId: 'adversaire',
          type: 'pronunciation',
          stage: 'production',
          prompt: 'Pronounce the following sentence correctly.',
          content: {"sentence":"Nous avons vaincu notre adversaire difficile."},
          answer: 'Nous avons vaincu notre adversaire difficile.',
          explanation: 'Pronounce with correct stress.',
        },
      ],
    },
    {
      id: 'sport-argumenter',
      title: 'Argumenter sur le sport',
      learningItemIds: ['avoir-la-niaque', 'esprit-dequipe', 'en-toute-securite'],
      exercises: [
        {
          id: 'spr-13',
          learningItemId: 'avoir-la-niaque',
          type: 'multiple_choice',
          stage: 'recognition',
          prompt: 'What does "Avoir la niaque" mean?',
          content: { options: ['To have fighting spirit / drive', 'To be very tired', 'To be injured', 'To be nervous'] },
          answer: 'To have fighting spirit / drive',
          explanation: '"Avoir la niaque" = to have real drive.',
        },
        {
          id: 'spr-14',
          learningItemId: 'avoir-la-niaque',
          type: 'fill_blank',
          stage: 'context',
          prompt: 'Complete the sentence',
          content: {
            sentence: 'Ce joueur a de la ______ sur le terrain.',
            options: ['niaque', 'nuque', 'pique', 'brique'],
          },
          answer: 'niaque',
          explanation: '"Avoir de la niaque" — a set expression for fighting spirit.',
        },
        {
          id: 'spr-15',
          learningItemId: 'esprit-dequipe',
          type: 'multiple_choice',
          stage: 'recognition',
          prompt: 'What does "Esprit d\u2019équipe" mean?',
          content: { options: ['Team spirit', 'Individual talent', 'Fierce rivalry', 'Home advantage'] },
          answer: 'Team spirit',
          explanation: '"Esprit d\u2019équipe" = "team spirit."',
        },
        {
          id: 'spr-16',
          learningItemId: 'esprit-dequipe',
          type: 'fill_blank',
          stage: 'context',
          prompt: 'Complete the sentence',
          content: {
            sentence: 'L\u2019______ d\u2019équipe est essentiel dans ce sport.',
            options: ['esprit', 'espoir', 'espèce', 'espace'],
          },
          answer: 'esprit',
          explanation: '"L\u2019esprit d\u2019équipe" — team spirit.',
        },
        {
          id: 'spr-17',
          learningItemId: 'esprit-dequipe',
          type: 'pronunciation',
          stage: 'production',
          prompt: 'Say the sentence aloud.',
          content: { sentence: 'Le sport développe l\u2019esprit d\u2019équipe.' },
          answer: 'Le sport développe l\u2019esprit d\u2019équipe.',
          explanation: 'A complete opinion sentence using "l\u2019esprit d\u2019équipe."',
        },
        {
          id: 'spr-18',
          learningItemId: 'en-toute-securite',
          type: 'pronunciation',
          stage: 'production',
          prompt: 'Say the sentence aloud.',
          content: { sentence: 'Il faut faire du sport en toute sécurité.' },
          answer: 'Il faut faire du sport en toute sécurité.',
          explanation: '"Il faut faire du sport" + "en toute sécurité" — a complete safety argument.',
        },
      
        {
          id: 'spr-37',
          learningItemId: 'esprit-dequipe',
          type: 'multiple_choice',
          stage: 'recognition',
          prompt: 'What does "L’esprit d’équipe" mean?',
          content: {"options":["Team spirit","Individual effort","Solo performance","Personal ambition"]},
          answer: 'Team spirit',
          explanation: '"L’esprit d’équipe" = team spirit.',
        },
        {
          id: 'spr-38',
          learningItemId: 'esprit-dequipe',
          type: 'translation',
          stage: 'recall',
          prompt: 'Translate: "Le sport développe l’esprit d’équipe."',
          content: {"options":["Sport develops teamwork.","Sport develops individual skill.","Sport develops personal ambition.","Sport develops solo performance."]},
          answer: 'Sport develops teamwork.',
          explanation: 'Translation of the sentence.',
        },
        {
          id: 'spr-39',
          learningItemId: 'en-toute-securite',
          type: 'fill_blank',
          stage: 'context',
          prompt: 'Complete the sentence',
          content: {"sentence":"Il faut faire du sport ________.","options":["en toute sécurité","en toute liberté","en toute urgence","en toute discrétion"]},
          answer: 'en toute sécurité',
          explanation: 'Correct phrase for safety.',
        },
        {
          id: 'spr-40',
          learningItemId: 'en-toute-securite',
          type: 'pronunciation',
          stage: 'production',
          prompt: 'Pronounce the expression',
          content: {"sentence":"En toute sécurité"},
          answer: 'En toute sécurité',
          explanation: 'Practice correct pronunciation.',
        },
        {
          id: 'spr-41',
          learningItemId: 'avoir-la-niaque',
          type: 'multiple_choice',
          stage: 'recall',
          prompt: 'Choose the correct form of the verb in the sentence: "Je ______ la niaque."',
          content: {"options":["ai","as","a","avons"]},
          answer: 'ai',
          explanation: 'First person singular of avoir.',
        },
        {
          id: 'spr-42',
          learningItemId: 'avoir-la-niaque',
          type: 'fill_blank',
          stage: 'context',
          prompt: 'Complete the sentence',
          content: {"sentence":"Nous ______ la niaque pour gagner.","options":["avons","avez","ont","a"]},
          answer: 'avons',
          explanation: 'First person plural of avoir.',
        },
        {
          id: 'spr-43',
          learningItemId: 'esprit-dequipe',
          type: 'translation',
          stage: 'context',
          prompt: 'Translate: "L’esprit d’équipe est essentiel pour la victoire."',
          content: {"options":["Team spirit is essential for victory.","Individual spirit is essential for victory.","Solo effort is essential for victory.","Personal ambition is essential for victory."]},
          answer: 'Team spirit is essential for victory.',
          explanation: 'Correct translation.',
        },
        {
          id: 'spr-44',
          learningItemId: 'en-toute-securite',
          type: 'multiple_choice',
          stage: 'recall',
          prompt: 'Which of these expresses the same idea as "en toute sécurité"?',
          content: {"options":["sans danger","à risque","en toute précaution","en toute hâte"]},
          answer: 'sans danger',
          explanation: 'Both mean without danger.',
        },
        {
          id: 'spr-45',
          learningItemId: 'avoir-la-niaque',
          type: 'fill_blank',
          stage: 'transformation',
          prompt: 'Transform the sentence to the negative form',
          content: {"sentence":"Il a la niaque.","options":["Il n'a pas la niaque.","Il a la niaque pas.","Il n'a la niaque.","Il n'a pas niaque."]},
          answer: 'Il n\'a pas la niaque.',
          explanation: 'Negative form of avoir.',
        },
        {
          id: 'spr-46',
          learningItemId: 'esprit-dequipe',
          type: 'pronunciation',
          stage: 'production',
          prompt: 'Pronounce the phrase',
          content: {"sentence":"L’esprit d’équipe"},
          answer: 'L’esprit d’équipe',
          explanation: 'Practice pronunciation.',
        },
      ],
    },
  ],
}

export const items = {
  equipe: {
    id: 'equipe',
    type: 'vocabulary',
    word: 'équipe',
    meaning: 'team',
    partOfSpeech: 'noun (f.)',
    level: 'A2',
    topic: 'Le sport',
    example: 'Notre équipe a gagné le match de samedi.',
    related: ['joueurs', 'sport collectif'],
  },
  match: {
    id: 'match',
    type: 'vocabulary',
    word: 'match',
    meaning: 'match',
    partOfSpeech: 'noun (m.)',
    level: 'A2',
    topic: 'Le sport',
    example: 'Le match commence à 20 heures.',
    related: ['rencontre', 'partie'],
  },
  entrainement: {
    id: 'entrainement',
    type: 'vocabulary',
    word: 'entraînement',
    meaning: 'training / practice',
    partOfSpeech: 'noun (m.)',
    level: 'A2',
    topic: 'Le sport',
    example: "L'entraînement a lieu deux fois par semaine.",
    related: ['séance', 'préparation'],
  },
  competition: {
    id: 'competition',
    type: 'vocabulary',
    word: 'compétition',
    meaning: 'competition',
    partOfSpeech: 'noun (f.)',
    level: 'A2',
    topic: 'Le sport',
    example: 'Elle participe à une compétition régionale ce week-end.',
    related: ['tournoi', 'championnat'],
  },

  'faire-de-jouer-a': {
    id: 'faire-de-jouer-a',
    type: 'grammar',
    title: 'Faire de / jouer à + sport',
    level: 'A2',
    explanation:
      'Individual sports take "faire de": faire de la natation, du vélo. Ball and team sports take "jouer à": jouer au foot, à la pétanque.',
    examples: ['Je joue au foot le samedi.', 'Je fais de la natation.'],
    counterexamples: ['Je joue du foot. (incorrect — a game is "au", the instrument is "du")'],
  },

  'rester-en-forme': {
    id: 'rester-en-forme',
    type: 'phrase',
    phrase: 'Rester en forme',
    meaning: 'To stay in shape',
    function: 'Health and fitness',
    level: 'A2',
    topic: 'Le sport',
    tefUsage: 'Expression orale — parler de son mode de vie',
    example: 'Faire du sport aide à rester en forme.',
    related: ['Être en bonne santé'],
    conjugation: {
      je: 'reste en forme',
      tu: 'restes en forme',
      ilElle: 'reste en forme',
      nous: 'restons en forme',
      vous: 'restez en forme',
      ilsElles: 'restent en forme',
    },
  },
  adversaire: {
    id: 'adversaire',
    type: 'phrase',
    phrase: 'Un adversaire difficile',
    meaning: 'A tough opponent',
    function: 'Competition',
    level: 'B1',
    topic: 'Le sport',
    tefUsage: 'Expression orale — raconter un match',
    example: 'Notre adversaire était très fort, mais nous avons gagné.',
    related: ['Rival'],
  },
  'avoir-la-niaque': {
    id: 'avoir-la-niaque',
    type: 'phrase',
    phrase: 'Avoir la niaque',
    meaning: 'To be full of fight',
    function: 'Describing a player',
    level: 'B1',
    topic: 'Le sport',
    tefUsage: 'Expression orale — décrire un sportif',
    example: 'Ce joueur a de la niaque sur le terrain.',
    related: ['Avoir du cran'],
    conjugation: {
      je: "J'ai la niaque",
      tu: "Tu as la niaque",
      ilElle: "Il/Elle a la niaque",
      nous: "Nous avons la niaque",
      vous: "Vous avez la niaque",
      ilsElles: "Ils/Elles ont la niaque",
    },
  },
  'esprit-dequipe': {
    id: 'esprit-dequipe',
    type: 'phrase',
    phrase: 'L\u2019esprit d\u2019équipe',
    meaning: 'Team spirit',
    function: 'Team values',
    level: 'A2',
    topic: 'Le sport',
    tefUsage: 'Expression orale — défendre une opinion sur le sport',
    example: 'Le sport développe l\u2019esprit d\u2019équipe.',
    related: ['La cohésion'],
  },
  'en-toute-securite': {
    id: 'en-toute-securite',
    type: 'phrase',
    phrase: 'En toute sécurité',
    meaning: 'In total safety',
    function: 'Safety',
    level: 'B1',
    topic: 'Le sport',
    tefUsage: 'Expression orale — donner un conseil',
    example: 'Il faut faire du sport en toute sécurité.',
    related: ['Prudemment'],
  },
}