// Hand-authored TEF theme unit (spec §3.2.1) — "Le sport" (Sport). Part of the full TEF theme
// coverage in the Learn path. Exports the same { unit, items } shape as generated units
// (spec §3.2.6). All exercises are tap-only (spec §3.2.2).

export const unit = {
  id: 'sport',
  title: 'Le sport',
  description: 'Talk about sports, exercise, and staying active in French.',
  lessons: [
    {
      id: 'sport-vocabulaire',
      title: 'Vocabulaire du sport',
      learningItemIds: ['equipe', 'match', 'entrainement', 'competition'],
      exercises: [
        {
          id: 'spr-1',
          learningItemId: 'equipe',
          type: 'multiple_choice',
          stage: 'recognition',
          prompt: 'What does "une équipe" mean?',
          content: { options: ['a team', 'a crowd', 'a score', 'a coach'] },
          answer: 'a team',
          explanation: '"Une équipe" is a "team."',
        },
        {
          id: 'spr-2',
          learningItemId: 'match',
          type: 'multiple_choice',
          stage: 'recognition',
          prompt: 'What does "un match" mean?',
          content: { options: ['a match', 'a referee', 'a goal', 'a stadium'] },
          answer: 'a match',
          explanation: '"Un match" is a "match."',
        },
        {
          id: 'spr-3',
          learningItemId: 'entrainement',
          type: 'translation',
          stage: 'recall',
          prompt: 'Translate: training / practice',
          content: { direction: 'en_to_fr', options: ['entraînement', 'entrée', 'entretien', 'entrave'] },
          answer: 'entraînement',
          explanation: '"Training" translates to "l\u2019entraînement."',
        },
        {
          id: 'spr-4',
          learningItemId: 'competition',
          type: 'translation',
          stage: 'recall',
          prompt: 'Translate: competition',
          content: { direction: 'en_to_fr', options: ['compétition', 'compliment', 'compétence', 'compréhension'] },
          answer: 'compétition',
          explanation: '"Competition" translates to "la compétition."',
        },
        {
          id: 'spr-5',
          learningItemId: 'equipe',
          type: 'fill_blank',
          stage: 'context',
          prompt: 'Complete the sentence',
          content: {
            sentence: 'Notre ______ a gagné le match de samedi.',
            options: ['équipe', 'épée', 'étape', 'enquête'],
          },
          answer: 'équipe',
          explanation: '"Notre équipe a gagné" — our team won.',
        },
        {
          id: 'spr-6',
          learningItemId: 'match',
          type: 'fill_blank',
          stage: 'context',
          prompt: 'Complete the sentence',
          content: {
            sentence: 'Le ______ commence à 20 heures.',
            options: ['match', 'mage', 'marché', 'mer'],
          },
          answer: 'match',
          explanation: '"Le match commence" — the match starts.',
        },
      ],
    },
    {
      id: 'sport-idees',
      title: 'Construire des idées',
      learningItemIds: ['faire-de-jouer-a', 'rester-en-forme', 'adversaire'],
      exercises: [
        {
          id: 'spr-7',
          learningItemId: 'faire-de-jouer-a',
          type: 'multiple_choice',
          stage: 'recognition',
          prompt: 'Which sentence is correct?',
          content: {
            options: ['Je joue au foot le samedi.', 'Je joue du foot le samedi.', 'Je fais au foot le samedi.'],
          },
          answer: 'Je joue au foot le samedi.',
          explanation: 'Ball/team sports take "jouer à": "jouer au foot."',
        },
        {
          id: 'spr-8',
          learningItemId: 'faire-de-jouer-a',
          type: 'fill_blank',
          stage: 'transformation',
          prompt: 'Complete the sentence',
          content: {
            sentence: 'Je fais ______ natation deux fois par semaine.',
            options: ['de la', 'du', 'des', 'de'],
          },
          answer: 'de la',
          explanation: 'Individual sports take "faire de": "faire de la natation."',
        },
        {
          id: 'spr-9',
          learningItemId: 'rester-en-forme',
          type: 'multiple_choice',
          stage: 'recognition',
          prompt: 'What does "Rester en forme" mean?',
          content: { options: ['To stay in shape', 'To lose weight', 'To rest completely', 'To retire'] },
          answer: 'To stay in shape',
          explanation: '"Rester en forme" means "to stay in shape."',
        },
        {
          id: 'spr-10',
          learningItemId: 'rester-en-forme',
          type: 'fill_blank',
          stage: 'context',
          prompt: 'Complete the sentence',
          content: {
            sentence: 'Faire du sport aide à ______ en forme.',
            options: ['rester', 'resterais', 'resté', 'resteront'],
          },
          answer: 'rester',
          explanation: 'After "aide à", the verb stays in the infinitive: "rester en forme."',
        },
        {
          id: 'spr-11',
          learningItemId: 'adversaire',
          type: 'translation',
          stage: 'recall',
          prompt: 'Translate: opponent',
          content: { direction: 'en_to_fr', options: ['adversaire', 'aventure', 'avantage', 'avertissement'] },
          answer: 'adversaire',
          explanation: '"Opponent" translates to "l\u2019adversaire."',
        },
        {
          id: 'spr-12',
          learningItemId: 'adversaire',
          type: 'fill_blank',
          stage: 'context',
          prompt: 'Complete the sentence',
          content: {
            sentence: 'Notre ______ était très fort, mais nous avons gagné.',
            options: ['adversaire', 'administrateur', 'attracteur', 'adaptateur'],
          },
          answer: 'adversaire',
          explanation: '"Notre adversaire" — our opponent.',
        },
      ],
    },
    {
      id: 'sport-argumenter',
      title: 'Argumenter sur le sport',
      learningItemIds: ['avoir-la-niaque', 'esprit-dequipe', 'en-toute-securite'],
      exercises: [
        {
          id: 'spr-13',
          learningItemId: 'avoir-la-niaque',
          type: 'multiple_choice',
          stage: 'recognition',
          prompt: 'What does "Avoir la niaque" mean?',
          content: { options: ['To have fighting spirit / drive', 'To be very tired', 'To be injured', 'To be nervous'] },
          answer: 'To have fighting spirit / drive',
          explanation: '"Avoir la niaque" = to have real drive.',
        },
        {
          id: 'spr-14',
          learningItemId: 'avoir-la-niaque',
          type: 'fill_blank',
          stage: 'context',
          prompt: 'Complete the sentence',
          content: {
            sentence: 'Ce joueur a de la ______ sur le terrain.',
            options: ['niaque', 'nuque', 'pique', 'brique'],
          },
          answer: 'niaque',
          explanation: '"Avoir de la niaque" — a set expression for fighting spirit.',
        },
        {
          id: 'spr-15',
          learningItemId: 'esprit-dequipe',
          type: 'multiple_choice',
          stage: 'recognition',
          prompt: 'What does "Esprit d\u2019équipe" mean?',
          content: { options: ['Team spirit', 'Individual talent', 'Fierce rivalry', 'Home advantage'] },
          answer: 'Team spirit',
          explanation: '"Esprit d\u2019équipe" = "team spirit."',
        },
        {
          id: 'spr-16',
          learningItemId: 'esprit-dequipe',
          type: 'fill_blank',
          stage: 'context',
          prompt: 'Complete the sentence',
          content: {
            sentence: 'L\u2019______ d\u2019équipe est essentiel dans ce sport.',
            options: ['esprit', 'espoir', 'espèce', 'espace'],
          },
          answer: 'esprit',
          explanation: '"L\u2019esprit d\u2019équipe" — team spirit.',
        },
        {
          id: 'spr-17',
          learningItemId: 'esprit-dequipe',
          type: 'production',
          stage: 'production',
          prompt: 'Build the sentence: "Le sport développe l\u2019esprit d\u2019équipe."',
          content: {
            tiles: ['Le', 'sport', 'développe', 'l\u2019esprit', 'd\u2019équipe.', 'developper', 'équipes'],
          },
          answer: 'Le sport développe l\u2019esprit d\u2019équipe.',
          explanation: 'A complete opinion sentence using "l\u2019esprit d\u2019équipe."',
        },
        {
          id: 'spr-18',
          learningItemId: 'en-toute-securite',
          type: 'production',
          stage: 'production',
          prompt: 'Build the sentence: "Il faut faire du sport en toute sécurité."',
          content: {
            tiles: ['Il', 'faut', 'faire', 'du', 'sport', 'en', 'toute', 'sécurité.', 'de', 'secure'],
          },
          answer: 'Il faut faire du sport en toute sécurité.',
          explanation: '"Il faut faire du sport" + "en toute sécurité" — a complete safety argument.',
        },
      ],
    },
  ],
}

export const items = {
  equipe: {
    id: 'equipe',
    type: 'vocabulary',
    word: 'équipe',
    meaning: 'team',
    partOfSpeech: 'noun (f.)',
    level: 'A2',
    topic: 'Le sport',
    example: 'Notre équipe a gagné le match de samedi.',
    related: ['joueurs', 'sport collectif'],
  },
  match: {
    id: 'match',
    type: 'vocabulary',
    word: 'match',
    meaning: 'match',
    partOfSpeech: 'noun (m.)',
    level: 'A2',
    topic: 'Le sport',
    example: 'Le match commence à 20 heures.',
    related: ['rencontre', 'partie'],
  },
  entrainement: {
    id: 'entrainement',
    type: 'vocabulary',
    word: 'entraînement',
    meaning: 'training / practice',
    partOfSpeech: 'noun (m.)',
    level: 'A2',
    topic: 'Le sport',
    example: "L'entraînement a lieu deux fois par semaine.",
    related: ['séance', 'préparation'],
  },
  competition: {
    id: 'competition',
    type: 'vocabulary',
    word: 'compétition',
    meaning: 'competition',
    partOfSpeech: 'noun (f.)',
    level: 'A2',
    topic: 'Le sport',
    example: 'Elle participe à une compétition régionale ce week-end.',
    related: ['tournoi', 'championnat'],
  },

  'faire-de-jouer-a': {
    id: 'faire-de-jouer-a',
    type: 'grammar',
    title: 'Faire de / jouer à + sport',
    level: 'A2',
    explanation:
      'Individual sports take "faire de": faire de la natation, du vélo. Ball and team sports take "jouer à": jouer au foot, à la pétanque.',
    examples: ['Je joue au foot le samedi.', 'Je fais de la natation.'],
    counterexamples: ['Je joue du foot. (incorrect — a game is "au", the instrument is "du")'],
  },

  'rester-en-forme': {
    id: 'rester-en-forme',
    type: 'phrase',
    phrase: 'Rester en forme',
    meaning: 'To stay in shape',
    function: 'Health and fitness',
    level: 'A2',
    topic: 'Le sport',
    tefUsage: 'Expression orale — parler de son mode de vie',
    example: 'Faire du sport aide à rester en forme.',
    related: ['Être en bonne santé'],
  },
  adversaire: {
    id: 'adversaire',
    type: 'phrase',
    phrase: 'Un adversaire difficile',
    meaning: 'A tough opponent',
    function: 'Competition',
    level: 'B1',
    topic: 'Le sport',
    tefUsage: 'Expression orale — raconter un match',
    example: 'Notre adversaire était très fort, mais nous avons gagné.',
    related: ['Rival'],
  },
  'avoir-la-niaque': {
    id: 'avoir-la-niaque',
    type: 'phrase',
    phrase: 'Avoir la niaque',
    meaning: 'To be full of fight',
    function: 'Describing a player',
    level: 'B1',
    topic: 'Le sport',
    tefUsage: 'Expression orale — décrire un sportif',
    example: 'Ce joueur a de la niaque sur le terrain.',
    related: ['Avoir du cran'],
  },
  'esprit-dequipe': {
    id: 'esprit-dequipe',
    type: 'phrase',
    phrase: 'L\u2019esprit d\u2019équipe',
    meaning: 'Team spirit',
    function: 'Team values',
    level: 'A2',
    topic: 'Le sport',
    tefUsage: 'Expression orale — défendre une opinion sur le sport',
    example: 'Le sport développe l\u2019esprit d\u2019équipe.',
    related: ['La cohésion'],
  },
  'en-toute-securite': {
    id: 'en-toute-securite',
    type: 'phrase',
    phrase: 'En toute sécurité',
    meaning: 'In total safety',
    function: 'Safety',
    level: 'B1',
    topic: 'Le sport',
    tefUsage: 'Expression orale — donner un conseil',
    example: 'Il faut faire du sport en toute sécurité.',
    related: ['Prudemment'],
  },
}