// Hand-authored TEF theme unit (spec §3.2.1) — "Les nouvelles technologies" (Technology). Part of
// the full TEF theme coverage in the Learn path. Exports the same { unit, items } shape as
// generated units (spec §3.2.6). All exercises are tap-only (spec §3.2.2).

export const unit = {
  id: 'technologies',
  title: 'Les nouvelles technologies',
  description: 'Navigate debates about screens, social media, and AI confidently.',
  lessons: [
    {
      id: 'technologies-vocabulaire',
      title: 'Vocabulaire des nouvelles technologies',
      learningItemIds: ['ecran', 'reseaux-sociaux', 'application', 'donnees'],
      exercises: [
        {
          id: 'tech-1',
          learningItemId: 'reseaux-sociaux',
          type: 'multiple_choice',
          stage: 'recognition',
          prompt: 'What does "les réseaux sociaux" mean?',
          content: { options: ['social media', 'social security', 'social workers', 'social sciences'] },
          answer: 'social media',
          explanation: '"Les réseaux sociaux" are "social media."',
        },
        {
          id: 'tech-2',
          learningItemId: 'application',
          type: 'multiple_choice',
          stage: 'recognition',
          prompt: 'What does "une application" mean?',
          content: { options: ['an app', 'an application form', 'an appointment', 'an applicant'] },
          answer: 'an app',
          explanation: 'In everyday French, "une application" is an "app."',
        },
        {
          id: 'tech-3',
          learningItemId: 'ecran',
          type: 'translation',
          stage: 'recall',
          prompt: 'Translate: screen',
          content: { direction: 'en_to_fr', options: ['écran', 'clavier', 'données', 'réseau'] },
          answer: 'écran',
          explanation: '"Screen" translates to "écran."',
        },
        {
          id: 'tech-4',
          learningItemId: 'donnees',
          type: 'translation',
          stage: 'recall',
          prompt: 'Translate: data',
          content: { direction: 'en_to_fr', options: ['données', 'donneurs', 'déjeuners', 'dessins'] },
          answer: 'données',
          explanation: '"Data" translates to "les données."',
        },
        {
          id: 'tech-5',
          learningItemId: 'ecran',
          type: 'fill_blank',
          stage: 'context',
          prompt: 'Complete the sentence',
          content: {
            sentence: "Il passe trop de temps devant l'______.",
            options: ['écran', 'appareil', 'écriture', 'emploi'],
          },
          answer: 'écran',
          explanation: '"L\u2019écran" (screen) takes the elided article "l\u2019."',
        },
        {
          id: 'tech-6',
          learningItemId: 'donnees',
          type: 'fill_blank',
          stage: 'context',
          prompt: 'Complete the sentence',
          content: {
            sentence: 'Nos ______ personnelles sont parfois mal protégées.',
            options: ['données', 'adresses', 'danses', 'dons'],
          },
          answer: 'données',
          explanation: '"Les données personnelles" are "personal data."',
        },
      
        {
          id: 'tech-19',
          learningItemId: 'ecran',
          type: 'multiple_choice',
          stage: 'recognition',
          prompt: 'Which word matches the French term "écran"?',
          content: {"options":["screen","keyboard","monitor","tablet"]},
          answer: 'screen',
          explanation: '"écran" translates to "screen."',
        },
        {
          id: 'tech-20',
          learningItemId: 'ecran',
          type: 'fill_blank',
          stage: 'recall',
          prompt: 'Complete the sentence: "Je regarde la vidéo sur le ______."',
          content: {"sentence":"Je regarde la vidéo sur le ______.","options":["téléphone","écran","ordinateur","smartphone"]},
          answer: 'écran',
          explanation: 'The blank should be "écran" (screen).',
        },
        {
          id: 'tech-21',
          learningItemId: 'reseaux-sociaux',
          type: 'translation',
          stage: 'context',
          prompt: 'Translate to French: "Social media platforms like Facebook and Instagram are widely used."',
          content: {"options":["Les plateformes de réseaux sociaux comme Facebook et Instagram sont largement utilisées.","Les plateformes de réseaux sociaux comme Facebook et Instagram sont rarement utilisées.","Les plateformes de réseaux sociaux comme Facebook et Instagram sont très dangereuses.","Les plateformes de réseaux sociaux comme Facebook et Instagram sont obsolètes."]},
          answer: 'Les plateformes de réseaux sociaux comme Facebook et Instagram sont largement utilisées.',
          explanation: 'This is the correct French translation.',
        },
        {
          id: 'tech-22',
          learningItemId: 'reseaux-sociaux',
          type: 'pronunciation',
          stage: 'production',
          prompt: 'Pronounce the following phrase correctly: "Les réseaux sociaux"',
          content: {"sentence":"Les réseaux sociaux"},
          answer: 'Les réseaux sociaux',
          explanation: 'Say the phrase with correct French intonation.',
        },
        {
          id: 'tech-23',
          learningItemId: 'application',
          type: 'multiple_choice',
          stage: 'recall',
          prompt: 'What is the French word for "app"?',
          content: {"options":["application","programme","logiciel","site"]},
          answer: 'application',
          explanation: '"App" is translated as "application."',
        },
        {
          id: 'tech-24',
          learningItemId: 'donnees',
          type: 'translation',
          stage: 'recognition',
          prompt: 'Translate to English: "Les données sont essentielles pour l\'analyse."',
          content: {"options":["Data is essential for analysis.","Data is useless for analysis.","Data is harmful for analysis.","Data is optional for analysis."]},
          answer: 'Data is essential for analysis.',
          explanation: 'Correct translation of the sentence.',
        },
        {
          id: 'tech-25',
          learningItemId: 'donnees',
          type: 'pronunciation',
          stage: 'recall',
          prompt: 'Pronounce: "Les données"',
          content: {"sentence":"Les données"},
          answer: 'Les données',
          explanation: 'Say the phrase with correct French pronunciation.',
        },
      ],
    },
    {
      id: 'technologies-idees',
      title: 'Construire des idées',
      learningItemIds: ['comparatif', 'au-courant', 'intelligence-artificielle'],
      exercises: [
        {
          id: 'tech-7',
          learningItemId: 'comparatif',
          type: 'multiple_choice',
          stage: 'recognition',
          prompt: 'Which sentence is correct?',
          content: { options: ["Ce logiciel est plus mieux que l'autre.", "Ce logiciel est mieux que l'autre."] },
          answer: "Ce logiciel est mieux que l'autre.",
          explanation: '"Mieux" already means "better" — never double it with "plus."',
        },
        {
          id: 'tech-8',
          learningItemId: 'comparatif',
          type: 'fill_blank',
          stage: 'context',
          prompt: 'Complete the sentence',
          content: {
            sentence: "Le téléphone est plus ______ qu'un ordinateur.",
            options: ['pratique', 'pratiquer', 'pratiquement', 'pratiques'],
          },
          answer: 'pratique',
          explanation: 'The comparative is "plus pratique qu\u2019" — adjective unchanged.',
        },
        {
          id: 'tech-9',
          learningItemId: 'intelligence-artificielle',
          type: 'translation',
          stage: 'recall',
          prompt: 'Translate: artificial intelligence',
          content: { direction: 'en_to_fr', options: ['intelligence artificielle', 'intelligence émotionnelle', 'science informatique', 'base de données'] },
          answer: 'intelligence artificielle',
          explanation: '"Artificial intelligence" translates to "l\u2019intelligence artificielle."',
        },
        {
          id: 'tech-10',
          learningItemId: 'au-courant',
          type: 'multiple_choice',
          stage: 'recognition',
          prompt: 'What does "Être au courant" mean?',
          content: { options: ['To be up to date', 'To be in charge', 'To be offline', 'To be surprised'] },
          answer: 'To be up to date',
          explanation: '"Être au courant" means "to be informed / up to date" about something.',
        },
        {
          id: 'tech-11',
          learningItemId: 'au-courant',
          type: 'fill_blank',
          stage: 'context',
          prompt: 'Complete the sentence',
          content: {
            sentence: 'Elle est au ______ des dernières applications.',
            options: ['courant', 'cours', 'courrier', 'coin'],
          },
          answer: 'courant',
          explanation: 'The expression is "être au courant de" — with "courant," not "cours."',
        },
        {
          id: 'tech-12',
          learningItemId: 'intelligence-artificielle',
          type: 'fill_blank',
          stage: 'context',
          prompt: 'Complete the sentence',
          content: {
            sentence: "L'intelligence ______ change beaucoup de métiers.",
            options: ['artificielle', 'artificiel', 'artistique', 'artisanale'],
          },
          answer: 'artificielle',
          explanation: '"Intelligence" is feminine, so the adjective is "artificielle."',
        },
      
        {
          id: 'tech-26',
          learningItemId: 'comparatif',
          type: 'fill_blank',
          stage: 'context',
          prompt: 'Complete the sentence',
          content: {"sentence":"Les tablettes sont ______ que les ordinateurs portables.","options":["plus rapides","plus rapid","plus rapidement","plus rapide"]},
          answer: 'plus rapides',
          explanation: 'Adjective agreement: plural masculine.',
        },
        {
          id: 'tech-27',
          learningItemId: 'au-courant',
          type: 'translation',
          stage: 'recall',
          prompt: 'Translate: "She is up to date with the latest apps."',
          content: {"options":["Elle est à jour avec les dernières applications.","Elle est au courant des dernières applications.","Elle est informée des dernières applications.","Elle est à l’heure des dernières applications."]},
          answer: 'Elle est au courant des dernières applications.',
          explanation: 'The idiomatic French expression is "être au courant".',
        },
        {
          id: 'tech-28',
          learningItemId: 'au-courant',
          type: 'pronunciation',
          stage: 'production',
          prompt: 'Pronounce the phrase',
          content: {"sentence":"Je suis au courant des nouvelles technologies."},
          answer: 'Je suis au courant des nouvelles technologies.',
          explanation: 'Focus on the liaison between "courant" and "des".',
        },
        {
          id: 'tech-29',
          learningItemId: 'intelligence-artificielle',
          type: 'multiple_choice',
          stage: 'recognition',
          prompt: 'Which sentence correctly uses the plural of "intelligence artificielle"?',
          content: {"options":["Les intelligences artificielles sont prometteuses.","Les intelligence artificielles sont prometteuses.","Les intelligences artificielle sont prometteuses.","Les intelligence artificielle sont prometteuses."]},
          answer: 'Les intelligences artificielles sont prometteuses.',
          explanation: 'Both noun and adjective are pluralized.',
        },
        {
          id: 'tech-30',
          learningItemId: 'au-courant',
          type: 'fill_blank',
          stage: 'recall',
          prompt: 'Complete the sentence',
          content: {"sentence":"Je ne suis pas ______ des nouvelles tendances.","options":["au courant","au courants","au courante","au courantes"]},
          answer: 'au courant',
          explanation: 'The expression is invariable.',
        },
      ],
    },
    {
      id: 'technologies-argumenter',
      title: 'Argumenter sur les technologies',
      learningItemIds: ['quant-a', 'il-suffit-de'],
      exercises: [
        {
          id: 'tech-13',
          learningItemId: 'quant-a',
          type: 'multiple_choice',
          stage: 'recognition',
          prompt: 'What does "Quant à" mean?',
          content: { options: ['As for', 'Thanks to', 'Despite', 'Meanwhile'] },
          answer: 'As for',
          explanation: '"Quant à" ("as for") introduces a specific point within a wider topic.',
        },
        {
          id: 'tech-14',
          learningItemId: 'quant-a',
          type: 'fill_blank',
          stage: 'context',
          prompt: 'Complete the sentence',
          content: {
            sentence: '______ aux réseaux sociaux, il faut les utiliser avec modération.',
            options: ['Quant', 'Quand', 'Quelle', 'Compte'],
          },
          answer: 'Quant',
          explanation: 'Use "quant à" (as for) — do not confuse it with "quand" (when).',
        },
        {
          id: 'tech-15',
          learningItemId: 'il-suffit-de',
          type: 'multiple_choice',
          stage: 'recognition',
          prompt: 'What does "Il suffit de" mean?',
          content: { options: ['You just have to', "It's forbidden to", "It's urgent to", "You're used to"] },
          answer: 'You just have to',
          explanation: '"Il suffit de" means "you just have to" — a simple condition.',
        },
        {
          id: 'tech-16',
          learningItemId: 'il-suffit-de',
          type: 'fill_blank',
          stage: 'context',
          prompt: 'Complete the sentence',
          content: {
            sentence: 'Il ______ de créer un compte pour commencer.',
            options: ['suffit', 'faut', 'vaut', 'dit'],
          },
          answer: 'suffit',
          explanation: '"Suffire" → "il suffit de" + infinitive.',
        },
        {
          id: 'tech-17',
          learningItemId: 'quant-a',
          type: 'pronunciation',
          stage: 'production',
          prompt: 'Say the sentence aloud.',
          content: { sentence: 'Quant aux réseaux sociaux, il faut les utiliser avec modération.' },
          answer: 'Quant aux réseaux sociaux, il faut les utiliser avec modération.',
          explanation: '"Quant à" + topic, then the recommendation.',
        },
        {
          id: 'tech-18',
          learningItemId: 'il-suffit-de',
          type: 'pronunciation',
          stage: 'production',
          prompt: 'Say the sentence aloud.',
          content: { sentence: 'Il suffit de créer un compte pour commencer.' },
          answer: 'Il suffit de créer un compte pour commencer.',
          explanation: '"Il suffit de" + infinitive, then the purpose with "pour."',
        },
      
        {
          id: 'tech-31',
          learningItemId: 'il-suffit-de',
          type: 'pronunciation',
          stage: 'production',
          prompt: 'Pronounce the following sentence correctly:',
          content: {"sentence":"Il suffit de télécharger l'application pour accéder à la plateforme."},
          answer: 'Il suffit de télécharger l\'application pour accéder à la plateforme.',
          explanation: 'Focus on the stress on "suffit" and the liaison with "de".',
        },
      ],
    },
  ],
}

export const items = {
  ecran: {
    id: 'ecran',
    type: 'vocabulary',
    word: 'écran',
    meaning: 'screen',
    partOfSpeech: 'noun (m.)',
    level: 'B1',
    topic: 'Les nouvelles technologies',
    example: "Il passe trop de temps devant l'écran.",
    related: ['ordinateur', 'téléphone'],
  },
  'reseaux-sociaux': {
    id: 'reseaux-sociaux',
    type: 'vocabulary',
    word: 'réseaux sociaux',
    meaning: 'social media',
    partOfSpeech: 'noun (m., plural)',
    level: 'B1',
    topic: 'Les nouvelles technologies',
    example: 'Les réseaux sociaux occupent une grande partie de notre temps.',
    related: ['Internet'],
  },
  donnees: {
    id: 'donnees',
    type: 'vocabulary',
    word: 'données',
    meaning: 'data',
    partOfSpeech: 'noun (f., plural)',
    level: 'B1',
    topic: 'Les nouvelles technologies',
    example: 'Nos données personnelles sont parfois mal protégées.',
    related: ['information'],
  },
  application: {
    id: 'application',
    type: 'vocabulary',
    word: 'application',
    meaning: 'app',
    partOfSpeech: 'noun (f.)',
    level: 'B1',
    topic: 'Les nouvelles technologies',
    example: 'Cette application facilite la vie quotidienne.',
    related: ['appli', 'logiciel'],
  },
  'intelligence-artificielle': {
    id: 'intelligence-artificielle',
    type: 'vocabulary',
    word: 'intelligence artificielle',
    meaning: 'artificial intelligence',
    partOfSpeech: 'noun (f.)',
    level: 'B1',
    topic: 'Les nouvelles technologies',
    example: "L'intelligence artificielle change beaucoup de métiers.",
    related: ['IA'],
  },

  'au-courant': {
    id: 'au-courant',
    type: 'phrase',
    phrase: 'Être au courant',
    meaning: 'To be up to date / aware',
    function: 'Being informed',
    level: 'B1',
    topic: 'Les nouvelles technologies',
    tefUsage: 'Expression orale — être informé',
    example: 'Elle est au courant des dernières applications.',
    related: ['Suivre', 'Être informé'],
    conjugation: {
      je: 'suis au courant',
      tu: 'es au courant',
      ilElle: 'est au courant',
      nous: 'sommes au courant',
      vous: 'êtes au courant',
      ilsElles: 'sont au courant',
    },
  },
  'quant-a': {
    id: 'quant-a',
    type: 'phrase',
    phrase: 'Quant à',
    meaning: 'As for',
    function: 'Introducing a different point',
    level: 'B1',
    topic: 'Les nouvelles technologies',
    tefUsage: 'Expression orale / écrite — structurer',
    example: 'Quant aux réseaux sociaux, il faut les utiliser avec modération.',
    related: ['En ce qui concerne'],
  },
  'il-suffit-de': {
    id: 'il-suffit-de',
    type: 'phrase',
    phrase: 'Il suffit de',
    meaning: 'You just have to',
    function: 'Stating a simple condition',
    level: 'B1',
    topic: 'Les nouvelles technologies',
    tefUsage: 'Expression orale — expliquer une procédure',
    example: 'Il suffit de créer un compte pour commencer.',
    related: ["Tout ce qu'il faut, c'est"],
  },

  comparatif: {
    id: 'comparatif',
    type: 'grammar',
    title: 'Comparatives with plus / moins / aussi',
    level: 'B1',
    explanation:
      'Compare two things with plus (more), moins (less), or aussi (as): plus pratique que, moins cher que, aussi utile que.',
    examples: ["Un smartphone est plus rapide qu'un vieil ordinateur.", "Cette application est aussi utile que l'autre."],
    counterexamples: [
      "Ce logiciel est plus mieux que l'autre. (incorrect — do not double the comparative: \"mieux\" already means \"better\")",
    ],
  },
}