// Hand-authored TEF theme unit (spec §3.2.1) — "Les transports" (Transport). Part of the full TEF
// theme coverage in the Learn path. Exports the same { unit, items } shape as generated units
// (spec §3.2.6). All exercises are tap-only (spec §3.2.2).

export const unit = {
  id: 'transports',
  title: 'Les transports',
  description: 'Talk about getting around, routes, and public transit in French.',
  lessons: [
    {
      id: 'transports-vocabulaire',
      title: 'Vocabulaire des transports',
      learningItemIds: ['voiture', 'billet', 'horaires', 'trafique'],
      exercises: [
        {
          id: 'trp-1',
          learningItemId: 'voiture',
          type: 'multiple_choice',
          stage: 'recognition',
          prompt: 'What does "une voiture" mean?',
          content: { options: ['a car', 'a plane', 'a boat', 'a bike'] },
          answer: 'a car',
          explanation: '"Une voiture" is a "car."',
        },
        {
          id: 'trp-2',
          learningItemId: 'billet',
          type: 'multiple_choice',
          stage: 'recognition',
          prompt: 'What does "un billet" mean?',
          content: { options: ['a ticket', 'a map', 'a station', 'a sign'] },
          answer: 'a ticket',
          explanation: '"Un billet" is a "ticket."',
        },
        {
          id: 'trp-3',
          learningItemId: 'horaires',
          type: 'translation',
          stage: 'recall',
          prompt: 'Translate: timetables / hours',
          content: { direction: 'en_to_fr', options: ['horaires', 'habitudes', 'honneur', 'heures'] },
          answer: 'horaires',
          explanation: '"Timetables" translates to "les horaires."',
        },
        {
          id: 'trp-4',
          learningItemId: 'trafique',
          type: 'translation',
          stage: 'recall',
          prompt: 'Translate: traffic',
          content: { direction: 'en_to_fr', options: ['trafic', 'tricot', 'tropique', 'trait'] },
          answer: 'trafic',
          explanation: '"Traffic" translates to "le trafic."',
        },
        {
          id: 'trp-5',
          learningItemId: 'voiture',
          type: 'fill_blank',
          stage: 'context',
          prompt: 'Complete the sentence',
          content: {
            sentence: 'Nous prenons la ______ pour aller au travail.',
            options: ['voiture', 'volette', 'visite', 'vitrine'],
          },
          answer: 'voiture',
          explanation: '"Prendre la voiture" — to take the car.',
        },
        {
          id: 'trp-6',
          learningItemId: 'billet',
          type: 'fill_blank',
          stage: 'context',
          prompt: 'Complete the sentence',
          content: {
            sentence: 'Je vais acheter un ______ de train.',
            options: ['billet', 'bijou', 'biscuit', 'bureau'],
          },
          answer: 'billet',
          explanation: '"Un billet de train" — a train ticket.',
        },
      
        {
          id: 'trp-37',
          learningItemId: 'voiture',
          type: 'translation',
          stage: 'recognition',
          prompt: 'Translate "une voiture est rouge."',
          content: {"options":["a car is red.","a train is red.","a bicycle is red.","a bus is red."]},
          answer: 'a car is red.',
          explanation: '"Une voiture est rouge." means "a car is red."',
        },
        {
          id: 'trp-38',
          learningItemId: 'billet',
          type: 'fill_blank',
          stage: 'recall',
          prompt: 'Je vais acheter ___ de bus.',
          content: {"sentence":"Je vais acheter ___ de bus.","options":["un billet","un ticket","une carte","un passe"]},
          answer: 'un billet',
          explanation: 'The correct phrase is "un billet" for a bus ticket.',
        },
        {
          id: 'trp-39',
          learningItemId: 'horaires',
          type: 'multiple_choice',
          stage: 'context',
          prompt: 'Which sentence uses "horaires" correctly?',
          content: {"options":["Les horaires sont sur le tableau.","Les horaires sont en train.","Les horaires sont à la maison.","Les horaires sont en cuisine."]},
          answer: 'Les horaires sont sur le tableau.',
          explanation: '"Horaires" refers to timetables, usually displayed on a board.',
        },
        {
          id: 'trp-40',
          learningItemId: 'voiture',
          type: 'multiple_choice',
          stage: 'recall',
          prompt: 'What is the masculine form of "voiture"?',
          content: {"options":["le voiture","le automobile","le véhicule","le chariot"]},
          answer: 'le automobile',
          explanation: 'The masculine counterpart of "voiture" is "automobile."',
        },
        {
          id: 'trp-41',
          learningItemId: 'horaires',
          type: 'multiple_choice',
          stage: 'recognition',
          prompt: 'Which word is synonymous with "horaires"?',
          content: {"options":["départ","arrivée","heure","minute"]},
          answer: 'heure',
          explanation: '"Horaires" refers to hours or times.',
        },
      ],
    },
    {
      id: 'transports-idees',
      title: 'Construire des idées',
      learningItemIds: ['pronoms-y', 'utiliser-les-transports', 'aller-retour'],
      exercises: [
        {
          id: 'trp-7',
          learningItemId: 'pronoms-y',
          type: 'multiple_choice',
          stage: 'recognition',
          prompt: 'Which sentence is correct?',
          content: { options: ['Je vais y en train.', 'J\u2019y vais en train.'] },
          answer: 'J\u2019y vais en train.',
          explanation: '"Y" replaces a place: it goes before the verb.',
        },
        {
          id: 'trp-8',
          learningItemId: 'pronoms-y',
          type: 'fill_blank',
          stage: 'transformation',
          prompt: 'Complete the sentence',
          content: {
            sentence: 'Nous allons au centre-ville. → Nous ______ allons à pied.',
            options: ['y', 'en', 'la', 'le'],
          },
          answer: 'y',
          explanation: '"Y" replaces "au centre-ville": "Nous y allons à pied."',
        },
        {
          id: 'trp-9',
          learningItemId: 'utiliser-les-transports',
          type: 'multiple_choice',
          stage: 'recognition',
          prompt: 'What does "Utiliser les transports" mean?',
          content: { options: ['To use public transit', 'To buy a car', 'To miss the train', 'To sell tickets'] },
          answer: 'To use public transit',
          explanation: '"Utiliser les transports" = "to use public transit."',
        },
        {
          id: 'trp-10',
          learningItemId: 'utiliser-les-transports',
          type: 'fill_blank',
          stage: 'context',
          prompt: 'Complete the sentence',
          content: {
            sentence: 'Pour polluer moins, on peut ______ les transports en commun.',
            options: ['utiliser', 'user', 'utilitaire', 'utile'],
          },
          answer: 'utiliser',
          explanation: '"Utiliser les transports en commun" — to use public transit.',
        },
        {
          id: 'trp-11',
          learningItemId: 'aller-retour',
          type: 'translation',
          stage: 'recall',
          prompt: 'Translate: a return ticket',
          content: { direction: 'en_to_fr', options: ['un aller-retour', 'un aller-retournement', 'un aller vers', 'un aller-retourner'] },
          answer: 'un aller-retour',
          explanation: '"A return ticket" is "un aller-retour."',
        },
        {
          id: 'trp-12',
          learningItemId: 'aller-retour',
          type: 'fill_blank',
          stage: 'context',
          prompt: 'Complete the sentence',
          content: {
            sentence: 'Un ticket aller simple ou ______ ?',
            options: ['aller-retour', 'aller-retourner', 'revient', 'revenir'],
          },
          answer: 'aller-retour',
          explanation: '"Un aller simple ou un aller-retour" — one-way or return.',
        },
      
        {
          id: 'trp-29',
          learningItemId: 'pronoms-y',
          type: 'multiple_choice',
          stage: 'recognition',
          prompt: 'Which sentence correctly uses "y"?',
          content: {"options":["Il y est en train de lire.","Il est en train de lire y."]},
          answer: 'Il y est en train de lire.',
          explanation: '"Y" must come before the verb: Il y est en train de lire.',
        },
        {
          id: 'trp-30',
          learningItemId: 'pronoms-y',
          type: 'fill_blank',
          stage: 'recall',
          prompt: 'Complete the sentence with the correct form of "y":',
          content: {"sentence":"Nous ______ sommes arrivés à la gare.","options":["y","en","le","la"]},
          answer: 'y',
          explanation: '"Y" replaces "à la gare": Nous y sommes arrivés.',
        },
        {
          id: 'trp-31',
          learningItemId: 'utiliser-les-transports',
          type: 'translation',
          stage: 'context',
          prompt: 'Translate into French: "I use the train to get to work."',
          content: {"options":["J’utilise le train pour me rendre au travail.","J’utilise le train pour me rendre à la maison.","J’utilise le train pour aller à l’école.","Je prends le train pour aller à l’école."]},
          answer: 'J’utilise le train pour me rendre au travail.',
          explanation: 'The phrase means "I use the train to get to work."',
        },
        {
          id: 'trp-32',
          learningItemId: 'utiliser-les-transports',
          type: 'pronunciation',
          stage: 'production',
          prompt: 'Pronounce the following sentence correctly:',
          content: {"sentence":"Pour réduire les émissions, nous utilisons les transports en commun."},
          answer: 'Pour réduire les émissions, nous utilisons les transports en commun.',
          explanation: 'Focus on the liaison and nasal sounds.',
        },
        {
          id: 'trp-33',
          learningItemId: 'aller-retour',
          type: 'multiple_choice',
          stage: 'recognition',
          prompt: 'Which sentence uses "un aller-retour" correctly?',
          content: {"options":["Je veux un aller-retour pour Lyon.","Je veux un aller-retour pour Lyon en train.","Je veux un aller-retour pour Lyon à pied.","Je veux un aller-retour pour Lyon en voiture."]},
          answer: 'Je veux un aller-retour pour Lyon.',
          explanation: '"Un aller-retour" is a round‑trip ticket, usually for public transport.',
        },
        {
          id: 'trp-34',
          learningItemId: 'aller-retour',
          type: 'fill_blank',
          stage: 'recall',
          prompt: 'Fill in the blank with the right form of "aller-retour":',
          content: {"sentence":"Elle a acheté ______ pour Paris.","options":["un aller simple","un aller-retour","une aller-retour","un aller en retour"]},
          answer: 'un aller-retour',
          explanation: 'The correct expression is "un aller-retour" for a round trip.',
        },
        {
          id: 'trp-35',
          learningItemId: 'aller-retour',
          type: 'translation',
          stage: 'context',
          prompt: 'Translate into French: "We bought a return ticket for the subway."',
          content: {"options":["Nous avons acheté un aller-retour pour le métro.","Nous avons acheté un aller simple pour le métro.","Nous avons acheté un billet retour pour le métro.","Nous avons acheté un aller-retour pour le bus."]},
          answer: 'Nous avons acheté un aller-retour pour le métro.',
          explanation: 'The phrase refers to a return ticket for the subway.',
        },
        {
          id: 'trp-36',
          learningItemId: 'utiliser-les-transports',
          type: 'pronunciation',
          stage: 'production',
          prompt: 'Pronounce the sentence correctly:',
          content: {"sentence":"Ils utilisent les transports en commun pour aller à l'école."},
          answer: 'Ils utilisent les transports en commun pour aller à l\'école.',
          explanation: 'Pay attention to the liaison between "commun" and "pour".',
        },
      ],
    },
    {
      id: 'transports-argumenter',
      title: 'Argumenter sur les transports',
      learningItemIds: ['prendre-les-transports', 'ca-coute-un-ticket'],
      exercises: [
        {
          id: 'trp-13',
          learningItemId: 'prendre-les-transports',
          type: 'multiple_choice',
          stage: 'recognition',
          prompt: 'What does "Prendre les transports en commun" mean?',
          content: { options: ['To take public transit', 'To drive everywhere', 'To walk to work', 'To share a ride'] },
          answer: 'To take public transit',
          explanation: '"Prendre les transports en commun" = "to take public transit."',
        },
        {
          id: 'trp-14',
          learningItemId: 'prendre-les-transports',
          type: 'fill_blank',
          stage: 'context',
          prompt: 'Complete the sentence',
          content: {
            sentence: 'Je ______ les transports en commun tous les jours.',
            options: ['prends', 'prendrais', 'prenant', 'prendre'],
          },
          answer: 'prends',
          explanation: 'Present of "prendre": "je prends."',
        },
        {
          id: 'trp-15',
          learningItemId: 'ca-coute-un-ticket',
          type: 'multiple_choice',
          stage: 'recognition',
          prompt: 'What does "Ça coûte un ticket" mean?',
          content: { options: ['It\u2019s expensive / it costs a fortune', "It's cheap", 'It\u2019s free', 'It\u2019s nearby'] },
          answer: 'It\u2019s expensive / it costs a fortune',
          explanation: '"Ça coûte un ticket" = it costs a lot.',
        },
        {
          id: 'trp-16',
          learningItemId: 'ca-coute-un-ticket',
          type: 'fill_blank',
          stage: 'context',
          prompt: 'Complete the sentence',
          content: {
            sentence: 'Le billet d\u2019avion, ça ______ un ticket !',
            options: ['coûte', 'coûtes', 'coûter', 'compte'],
          },
          answer: 'coûte',
          explanation: '"Ça coûte" — present of "coûter."',
        },
        {
          id: 'trp-17',
          learningItemId: 'prendre-les-transports',
          type: 'pronunciation',
          stage: 'production',
          prompt: 'Say the sentence aloud.',
          content: { sentence: 'Je prends les transports en commun tous les jours.' },
          answer: 'Je prends les transports en commun tous les jours.',
          explanation: '"Prendre les transports en commun" — a daily-habit sentence you can adapt for the oral exam.',
        },
        {
          id: 'trp-18',
          learningItemId: 'aller-retour',
          type: 'pronunciation',
          stage: 'production',
          prompt: 'Say the sentence aloud.',
          content: { sentence: 'Il faut payer un aller-retour.' },
          answer: 'Il faut payer un aller-retour.',
          explanation: '"Il faut" + infinitive: "payer un aller-retour."',
        },
      
        {
          id: 'trp-19',
          learningItemId: 'prendre-les-transports',
          type: 'multiple_choice',
          stage: 'recall',
          prompt: 'Which sentence best uses "prendre les transports en commun" in the present tense?',
          content: {"options":["Je prends les transports en commun chaque matin.","Je prendrai les transports en commun demain.","Je prenais les transports en commun hier.","Je prendre les transports en commun tous les jours."]},
          answer: 'Je prends les transports en commun chaque matin.',
          explanation: 'The correct present tense form is "je prends".',
        },
        {
          id: 'trp-20',
          learningItemId: 'prendre-les-transports',
          type: 'fill_blank',
          stage: 'context',
          prompt: 'Complete the sentence with the correct form of "prendre" for "nous".',
          content: {"sentence":"Nous ______ les transports en commun le week-end.","options":["prendons","prends","prendre","prendais"]},
          answer: 'prendons',
          explanation: 'Present tense, nous form: "nous prendons".',
        },
        {
          id: 'trp-21',
          learningItemId: 'prendre-les-transports',
          type: 'translation',
          stage: 'recognition',
          prompt: 'Translate to French: "They take public transit on Sundays."',
          content: {"options":["Ils prennent les transports en commun le dimanche.","Ils prend les transports en commun le dimanche.","Ils prendre les transports en commun le dimanche.","Ils prendons les transports en commun le dimanche."]},
          answer: 'Ils prennent les transports en commun le dimanche.',
          explanation: 'Correct translation uses "ils prennent".',
        },
        {
          id: 'trp-22',
          learningItemId: 'prendre-les-transports',
          type: 'pronunciation',
          stage: 'production',
          prompt: 'Pronounce the full sentence in French: "Je prends les transports en commun."',
          content: {"sentence":"Je prends les transports en commun."},
          answer: 'Je prends les transports en commun.',
          explanation: '',
        },
        {
          id: 'trp-23',
          learningItemId: 'ca-coute-un-ticket',
          type: 'multiple_choice',
          stage: 'recall',
          prompt: 'What does "Ça coûte un ticket" express?',
          content: {"options":["It costs a lot.","It costs a ticket.","It is free.","It is cheap."]},
          answer: 'It costs a lot.',
          explanation: 'The phrase means "It’s very expensive."',
        },
        {
          id: 'trp-24',
          learningItemId: 'ca-coute-un-ticket',
          type: 'fill_blank',
          stage: 'context',
          prompt: 'Complete: "Le billet de train, ______ un ticket !"',
          content: {"options":["ça coûte","c'est cher","ça coûte un ticket","c'est gratuit"]},
          answer: 'ça coûte un ticket',
          explanation: 'Correct idiomatic expression.',
        },
        {
          id: 'trp-25',
          learningItemId: 'ca-coute-un-ticket',
          type: 'translation',
          stage: 'recognition',
          prompt: 'Translate to French: "The plane ticket is very expensive."',
          content: {"options":["Le billet d’avion, ça coûte un ticket.","Le billet d’avion, ça coûte cher.","Le billet d’avion, c’est gratuit.","Le billet d’avion, c’est cher."]},
          answer: 'Le billet d’avion, ça coûte un ticket.',
          explanation: 'Matches the idiom "ça coûte un ticket".',
        },
        {
          id: 'trp-26',
          learningItemId: 'ca-coute-un-ticket',
          type: 'pronunciation',
          stage: 'production',
          prompt: 'Say the sentence: "Le billet de bus, ça coûte un ticket."',
          content: {"sentence":"Le billet de bus, ça coûte un ticket."},
          answer: 'Le billet de bus, ça coûte un ticket.',
          explanation: '',
        },
        {
          id: 'trp-27',
          learningItemId: 'prendre-les-transports',
          type: 'multiple_choice',
          stage: 'transformation',
          prompt: 'Choose the correct negative form: "Je ne ______ les transports en commun."',
          content: {"options":["prends","prend","prendons","prendre"]},
          answer: 'prends',
          explanation: 'Negative present: "je ne prends pas".',
        },
        {
          id: 'trp-28',
          learningItemId: 'ca-coute-un-ticket',
          type: 'fill_blank',
          stage: 'recall',
          prompt: 'Fill in: "Le métro, ______ un ticket."',
          content: {"options":["c'est cher","ça coûte un ticket","c'est gratuit","ça coûte cher"]},
          answer: 'ça coûte un ticket',
          explanation: 'Correct idiomatic phrase.',
        },
      ],
    },
  ],
}

export const items = {
  voiture: {
    id: 'voiture',
    type: 'vocabulary',
    word: 'voiture',
    meaning: 'car',
    partOfSpeech: 'noun (f.)',
    level: 'A2',
    topic: 'Les transports',
    example: 'Nous prenons la voiture pour aller au travail.',
    related: ['automobile', 'véhicule'],
  },
  billet: {
    id: 'billet',
    type: 'vocabulary',
    word: 'billet',
    meaning: 'ticket',
    partOfSpeech: 'noun (m.)',
    level: 'A2',
    topic: 'Les transports',
    example: 'Je vais acheter un billet de train.',
    related: ['ticket', 'aller-retour'],
  },
  horaires: {
    id: 'horaires',
    type: 'vocabulary',
    word: 'horaires',
    meaning: 'timetables / hours',
    partOfSpeech: 'noun (m. pl.)',
    level: 'A2',
    topic: 'Les transports',
    example: 'Les horaires des trains sont affichés sur le site.',
    related: ['heure', 'départ'],
  },
  trafique: {
    id: 'trafique',
    type: 'vocabulary',
    word: 'trafic',
    meaning: 'traffic',
    partOfSpeech: 'noun (m.)',
    level: 'A2',
    topic: 'Les transports',
    example: 'Il y a beaucoup de trafic sur cette route le matin.',
    related: ['circulation', 'route'],
  },

  'utiliser-les-transports': {
    id: 'utiliser-les-transports',
    type: 'phrase',
    phrase: 'Utiliser les transports',
    meaning: 'To use public transit',
    function: 'Getting around',
    level: 'A2',
    topic: 'Les transports',
    tefUsage: 'Expression orale — décrire ses habitudes de mobilité',
    example: 'Pour polluer moins, on peut utiliser les transports en commun.',
    related: ['Prendre le bus', 'Le métro'],
    conjugation: {
      je: 'utilise les transports',
      tu: 'utilises les transports',
      ilElle: 'utilise les transports',
      nous: 'utilisons les transports',
      vous: 'utilisez les transports',
      ilsElles: 'utilisent les transports',
    },
  },
  'aller-retour': {
    id: 'aller-retour',
    type: 'phrase',
    phrase: 'Un aller-retour',
    meaning: 'A return / round trip',
    function: 'Buying a ticket',
    level: 'A2',
    topic: 'Les transports',
    tefUsage: 'Expression orale — acheter un billet',
    example: 'Je voudrais un aller-retour pour Paris.',
    related: ['Un aller simple'],
  },
  'prendre-les-transports': {
    id: 'prendre-les-transports',
    type: 'phrase',
    phrase: 'Prendre les transports en commun',
    meaning: 'To take public transit',
    function: 'Getting around',
    level: 'A2',
    topic: 'Les transports',
    tefUsage: 'Expression orale — décrire ses déplacements quotidiens',
    example: 'Je prends les transports en commun tous les jours.',
    related: ['Utiliser les transports'],
    conjugation: {
      je: 'prends les transports',
      tu: 'prends les transports',
      ilElle: 'prend les transports',
      nous: 'prenons les transports',
      vous: 'prenez les transports',
      ilsElles: 'prennent les transports',
    },
  },
  'ca-coute-un-ticket': {
    id: 'ca-coute-un-ticket',
    type: 'phrase',
    phrase: 'Ça coûte un ticket',
    meaning: 'It\u2019s very expensive',
    function: 'Evaluating a price',
    level: 'B1',
    topic: 'Les transports',
    tefUsage: 'Expression orale — commenter un prix',
    example: 'Le billet d\u2019avion, ça coûte un ticket !',
    related: ['Ça coûte cher'],
  },

  'pronoms-y': {
    id: 'pronoms-y',
    type: 'grammar',
    title: 'Le pronom "y" (place and position)',
    level: 'A2',
    explanation:
      '"Y" replaces a place already mentioned ("à + place" or "en + place"). It goes before the conjugated verb: on y va, nous y allons.',
    examples: ['J\u2019y vais en train.', 'Nous y habitons depuis deux ans.'],
    counterexamples: ['Je vais y en train. (incorrect — "y" must come before the verb, not after)'],
  },
}