// Hand-authored TEF theme unit (spec §3.2.1) — "Les transports" (Transport). Part of the full TEF
// theme coverage in the Learn path. Exports the same { unit, items } shape as generated units
// (spec §3.2.6). All exercises are tap-only (spec §3.2.2).

export const unit = {
  id: 'transports',
  title: 'Les transports',
  description: 'Talk about getting around, routes, and public transit in French.',
  lessons: [
    {
      id: 'transports-vocabulaire',
      title: 'Vocabulaire des transports',
      learningItemIds: ['voiture', 'billet', 'horaires', 'trafique'],
      exercises: [
        {
          id: 'trp-1',
          learningItemId: 'voiture',
          type: 'multiple_choice',
          stage: 'recognition',
          prompt: 'What does "une voiture" mean?',
          content: { options: ['a car', 'a plane', 'a boat', 'a bike'] },
          answer: 'a car',
          explanation: '"Une voiture" is a "car."',
        },
        {
          id: 'trp-2',
          learningItemId: 'billet',
          type: 'multiple_choice',
          stage: 'recognition',
          prompt: 'What does "un billet" mean?',
          content: { options: ['a ticket', 'a map', 'a station', 'a sign'] },
          answer: 'a ticket',
          explanation: '"Un billet" is a "ticket."',
        },
        {
          id: 'trp-3',
          learningItemId: 'horaires',
          type: 'translation',
          stage: 'recall',
          prompt: 'Translate: timetables / hours',
          content: { direction: 'en_to_fr', options: ['horaires', 'habitudes', 'honneur', 'heures'] },
          answer: 'horaires',
          explanation: '"Timetables" translates to "les horaires."',
        },
        {
          id: 'trp-4',
          learningItemId: 'trafique',
          type: 'translation',
          stage: 'recall',
          prompt: 'Translate: traffic',
          content: { direction: 'en_to_fr', options: ['trafic', 'tricot', 'tropique', 'trait'] },
          answer: 'trafic',
          explanation: '"Traffic" translates to "le trafic."',
        },
        {
          id: 'trp-5',
          learningItemId: 'voiture',
          type: 'fill_blank',
          stage: 'context',
          prompt: 'Complete the sentence',
          content: {
            sentence: 'Nous prenons la ______ pour aller au travail.',
            options: ['voiture', 'volette', 'visite', 'vitrine'],
          },
          answer: 'voiture',
          explanation: '"Prendre la voiture" — to take the car.',
        },
        {
          id: 'trp-6',
          learningItemId: 'billet',
          type: 'fill_blank',
          stage: 'context',
          prompt: 'Complete the sentence',
          content: {
            sentence: 'Je vais acheter un ______ de train.',
            options: ['billet', 'bijou', 'biscuit', 'bureau'],
          },
          answer: 'billet',
          explanation: '"Un billet de train" — a train ticket.',
        },
      ],
    },
    {
      id: 'transports-idees',
      title: 'Construire des idées',
      learningItemIds: ['pronoms-y', 'utiliser-les-transports', 'aller-retour'],
      exercises: [
        {
          id: 'trp-7',
          learningItemId: 'pronoms-y',
          type: 'multiple_choice',
          stage: 'recognition',
          prompt: 'Which sentence is correct?',
          content: { options: ['Je vais y en train.', 'J\u2019y vais en train.'] },
          answer: 'J\u2019y vais en train.',
          explanation: '"Y" replaces a place: it goes before the verb.',
        },
        {
          id: 'trp-8',
          learningItemId: 'pronoms-y',
          type: 'fill_blank',
          stage: 'transformation',
          prompt: 'Complete the sentence',
          content: {
            sentence: 'Nous allons au centre-ville. → Nous ______ allons à pied.',
            options: ['y', 'en', 'la', 'le'],
          },
          answer: 'y',
          explanation: '"Y" replaces "au centre-ville": "Nous y allons à pied."',
        },
        {
          id: 'trp-9',
          learningItemId: 'utiliser-les-transports',
          type: 'multiple_choice',
          stage: 'recognition',
          prompt: 'What does "Utiliser les transports" mean?',
          content: { options: ['To use public transit', 'To buy a car', 'To miss the train', 'To sell tickets'] },
          answer: 'To use public transit',
          explanation: '"Utiliser les transports" = "to use public transit."',
        },
        {
          id: 'trp-10',
          learningItemId: 'utiliser-les-transports',
          type: 'fill_blank',
          stage: 'context',
          prompt: 'Complete the sentence',
          content: {
            sentence: 'Pour polluer moins, on peut ______ les transports en commun.',
            options: ['utiliser', 'user', 'utilitaire', 'utile'],
          },
          answer: 'utiliser',
          explanation: '"Utiliser les transports en commun" — to use public transit.',
        },
        {
          id: 'trp-11',
          learningItemId: 'aller-retour',
          type: 'translation',
          stage: 'recall',
          prompt: 'Translate: a return ticket',
          content: { direction: 'en_to_fr', options: ['un aller-retour', 'un aller-retournement', 'un aller vers', 'un aller-retourner'] },
          answer: 'un aller-retour',
          explanation: '"A return ticket" is "un aller-retour."',
        },
        {
          id: 'trp-12',
          learningItemId: 'aller-retour',
          type: 'fill_blank',
          stage: 'context',
          prompt: 'Complete the sentence',
          content: {
            sentence: 'Un ticket aller simple ou ______ ?',
            options: ['aller-retour', 'aller-retourner', 'revient', 'revenir'],
          },
          answer: 'aller-retour',
          explanation: '"Un aller simple ou un aller-retour" — one-way or return.',
        },
      ],
    },
    {
      id: 'transports-argumenter',
      title: 'Argumenter sur les transports',
      learningItemIds: ['prendre-les-transports', 'ca-coute-un-ticket'],
      exercises: [
        {
          id: 'trp-13',
          learningItemId: 'prendre-les-transports',
          type: 'multiple_choice',
          stage: 'recognition',
          prompt: 'What does "Prendre les transports en commun" mean?',
          content: { options: ['To take public transit', 'To drive everywhere', 'To walk to work', 'To share a ride'] },
          answer: 'To take public transit',
          explanation: '"Prendre les transports en commun" = "to take public transit."',
        },
        {
          id: 'trp-14',
          learningItemId: 'prendre-les-transports',
          type: 'fill_blank',
          stage: 'context',
          prompt: 'Complete the sentence',
          content: {
            sentence: 'Je ______ les transports en commun tous les jours.',
            options: ['prends', 'prendrais', 'prenant', 'prendre'],
          },
          answer: 'prends',
          explanation: 'Present of "prendre": "je prends."',
        },
        {
          id: 'trp-15',
          learningItemId: 'ca-coute-un-ticket',
          type: 'multiple_choice',
          stage: 'recognition',
          prompt: 'What does "Ça coûte un ticket" mean?',
          content: { options: ['It\u2019s expensive / it costs a fortune', "It's cheap", 'It\u2019s free', 'It\u2019s nearby'] },
          answer: 'It\u2019s expensive / it costs a fortune',
          explanation: '"Ça coûte un ticket" = it costs a lot.',
        },
        {
          id: 'trp-16',
          learningItemId: 'ca-coute-un-ticket',
          type: 'fill_blank',
          stage: 'context',
          prompt: 'Complete the sentence',
          content: {
            sentence: 'Le billet d\u2019avion, ça ______ un ticket !',
            options: ['coûte', 'coûtes', 'coûter', 'compte'],
          },
          answer: 'coûte',
          explanation: '"Ça coûte" — present of "coûter."',
        },
        {
          id: 'trp-17',
          learningItemId: 'prendre-les-transports',
          type: 'production',
          stage: 'production',
          prompt: 'Build the sentence: "Je prends les transports en commun tous les jours."',
          content: {
            tiles: ['Je', 'prends', 'les', 'transports', 'en', 'commun', 'tous', 'les', 'jours.', 'prend', 'public'],
          },
          answer: 'Je prends les transports en commun tous les jours.',
          explanation: '"Prendre les transports en commun" — a daily-habit sentence you can adapt for the oral exam.',
        },
        {
          id: 'trp-18',
          learningItemId: 'aller-retour',
          type: 'production',
          stage: 'production',
          prompt: 'Build the sentence: "Il faut payer un aller-retour."',
          content: {
            tiles: ['Il', 'faut', 'payer', 'un', 'aller-retour.', 'payerais', 'retourner'],
          },
          answer: 'Il faut payer un aller-retour.',
          explanation: '"Il faut" + infinitive: "payer un aller-retour."',
        },
      ],
    },
  ],
}

export const items = {
  voiture: {
    id: 'voiture',
    type: 'vocabulary',
    word: 'voiture',
    meaning: 'car',
    partOfSpeech: 'noun (f.)',
    level: 'A2',
    topic: 'Les transports',
    example: 'Nous prenons la voiture pour aller au travail.',
    related: ['automobile', 'véhicule'],
  },
  billet: {
    id: 'billet',
    type: 'vocabulary',
    word: 'billet',
    meaning: 'ticket',
    partOfSpeech: 'noun (m.)',
    level: 'A2',
    topic: 'Les transports',
    example: 'Je vais acheter un billet de train.',
    related: ['ticket', 'aller-retour'],
  },
  horaires: {
    id: 'horaires',
    type: 'vocabulary',
    word: 'horaires',
    meaning: 'timetables / hours',
    partOfSpeech: 'noun (m. pl.)',
    level: 'A2',
    topic: 'Les transports',
    example: 'Les horaires des trains sont affichés sur le site.',
    related: ['heure', 'départ'],
  },
  trafique: {
    id: 'trafique',
    type: 'vocabulary',
    word: 'trafic',
    meaning: 'traffic',
    partOfSpeech: 'noun (m.)',
    level: 'A2',
    topic: 'Les transports',
    example: 'Il y a beaucoup de trafic sur cette route le matin.',
    related: ['circulation', 'route'],
  },

  'utiliser-les-transports': {
    id: 'utiliser-les-transports',
    type: 'phrase',
    phrase: 'Utiliser les transports',
    meaning: 'To use public transit',
    function: 'Getting around',
    level: 'A2',
    topic: 'Les transports',
    tefUsage: 'Expression orale — décrire ses habitudes de mobilité',
    example: 'Pour polluer moins, on peut utiliser les transports en commun.',
    related: ['Prendre le bus', 'Le métro'],
  },
  'aller-retour': {
    id: 'aller-retour',
    type: 'phrase',
    phrase: 'Un aller-retour',
    meaning: 'A return / round trip',
    function: 'Buying a ticket',
    level: 'A2',
    topic: 'Les transports',
    tefUsage: 'Expression orale — acheter un billet',
    example: 'Je voudrais un aller-retour pour Paris.',
    related: ['Un aller simple'],
  },
  'prendre-les-transports': {
    id: 'prendre-les-transports',
    type: 'phrase',
    phrase: 'Prendre les transports en commun',
    meaning: 'To take public transit',
    function: 'Getting around',
    level: 'A2',
    topic: 'Les transports',
    tefUsage: 'Expression orale — décrire ses déplacements quotidiens',
    example: 'Je prends les transports en commun tous les jours.',
    related: ['Utiliser les transports'],
  },
  'ca-coute-un-ticket': {
    id: 'ca-coute-un-ticket',
    type: 'phrase',
    phrase: 'Ça coûte un ticket',
    meaning: 'It\u2019s very expensive',
    function: 'Evaluating a price',
    level: 'B1',
    topic: 'Les transports',
    tefUsage: 'Expression orale — commenter un prix',
    example: 'Le billet d\u2019avion, ça coûte un ticket !',
    related: ['Ça coûte cher'],
  },

  'pronoms-y': {
    id: 'pronoms-y',
    type: 'grammar',
    title: 'Le pronom "y" (place and position)',
    level: 'A2',
    explanation:
      '"Y" replaces a place already mentioned ("à + place" or "en + place"). It goes before the conjugated verb: on y va, nous y allons.',
    examples: ['J\u2019y vais en train.', 'Nous y habitons depuis deux ans.'],
    counterexamples: ['Je vais y en train. (incorrect — "y" must come before the verb, not after)'],
  },
}