// Hand-authored TEF theme unit (spec §3.2.1) — "Le travail" (Work). One of the fourteen official
// TEF themes covered by the Learn path. Exports the same { unit, items } shape as the generated
// units (spec §3.2.6). All exercises are tap-only (spec §3.2.2).

export const unit = {
  id: 'travail',
  title: 'Le travail',
  description: 'Talk about jobs, work situations, and employment — a core theme on the TEF.',
  lessons: [
    {
      id: 'travail-vocabulaire',
      title: 'Vocabulaire du travail',
      learningItemIds: ['emploi', 'contrat', 'salaire', 'chomage', 'poste'],
      exercises: [
        {
          id: 'tr-1',
          learningItemId: 'emploi',
          type: 'multiple_choice',
          stage: 'recognition',
          prompt: 'What does "un emploi" mean?',
          content: { options: ['a job', 'a salary', 'a boss', 'a schedule'] },
          answer: 'a job',
          explanation: '"Un emploi" means a "job" or "employment."',
        },
        {
          id: 'tr-2',
          learningItemId: 'chomage',
          type: 'multiple_choice',
          stage: 'recognition',
          prompt: 'What does "le chômage" mean?',
          content: { options: ['unemployment', 'part-time work', 'a promotion', 'a contract'] },
          answer: 'unemployment',
          explanation: '"Le chômage" means "unemployment" — the state of being without a job.',
        },
        {
          id: 'tr-3',
          learningItemId: 'contrat',
          type: 'translation',
          stage: 'recall',
          prompt: 'Translate: contract',
          content: { direction: 'en_to_fr', options: ['contrat', 'salaire', 'poste', 'entretien'] },
          answer: 'contrat',
          explanation: '"Contract" translates to "contrat."',
        },
        {
          id: 'tr-4',
          learningItemId: 'salaire',
          type: 'translation',
          stage: 'recall',
          prompt: 'Translate: salary',
          content: { direction: 'en_to_fr', options: ['salaire', 'emploi', 'chômage', 'contrat'] },
          answer: 'salaire',
          explanation: '"Salary" translates to "salaire."',
        },
        {
          id: 'tr-5',
          learningItemId: 'emploi',
          type: 'fill_blank',
          stage: 'context',
          prompt: 'Complete the sentence',
          content: {
            sentence: 'Elle ______ un emploi stable.',
            options: ['cherche', 'cherchent', 'cherchons', 'cherches'],
          },
          answer: 'cherche',
          explanation: 'Subject "elle" takes the third-person singular form "cherche."',
        },
        {
          id: 'tr-6',
          learningItemId: 'contrat',
          type: 'fill_blank',
          stage: 'context',
          prompt: 'Complete the sentence',
          content: {
            sentence: 'Il a signé un ______ à durée indéterminée.',
            options: ['contrat', 'salaire', 'poste', 'chômage'],
          },
          answer: 'contrat',
          explanation: 'A "contrat" fixes the terms of an employment relationship.',
        },
      
        {
          id: 'tr-19',
          learningItemId: 'emploi',
          type: 'multiple_choice',
          stage: 'recall',
          prompt: 'Which word best translates "job"?',
          content: {"options":["emploi","contrat","salaire","chômage"]},
          answer: 'emploi',
          explanation: '"Job" translates to "emploi".',
        },
        {
          id: 'tr-20',
          learningItemId: 'emploi',
          type: 'fill_blank',
          stage: 'context',
          prompt: 'Il a trouvé un _______ dans une agence de publicité.',
          content: {"sentence":"Il a trouvé un _______ dans une agence de publicité.","options":["emploi","contrat","salaire","chômage"]},
          answer: 'emploi',
          explanation: 'The sentence means "He found a job in an advertising agency."',
        },
        {
          id: 'tr-21',
          learningItemId: 'contrat',
          type: 'translation',
          stage: 'recognition',
          prompt: 'Translate: "Un contrat à durée déterminée."',
          content: {"options":["A permanent contract","A fixed-term contract","A salary","An unemployment benefit"]},
          answer: 'A fixed-term contract',
          explanation: 'It means a contract for a set period.',
        },
        {
          id: 'tr-22',
          learningItemId: 'salaire',
          type: 'multiple_choice',
          stage: 'recall',
          prompt: 'What does "le salaire" refer to?',
          content: {"options":["un emploi","un contrat","un salaire","un chômage"]},
          answer: 'un salaire',
          explanation: '"Le salaire" means "salary."',
        },
        {
          id: 'tr-23',
          learningItemId: 'salaire',
          type: 'fill_blank',
          stage: 'context',
          prompt: 'Le _______ est payé chaque mois.',
          content: {"sentence":"Le _______ est payé chaque mois.","options":["emploi","contrat","salaire","chômage"]},
          answer: 'salaire',
          explanation: 'The sentence means "The salary is paid every month."',
        },
        {
          id: 'tr-24',
          learningItemId: 'chomage',
          type: 'translation',
          stage: 'recall',
          prompt: 'Translate: "Le chômage a augmenté."',
          content: {"options":["Un emploi a augmenté.","Un contrat a augmenté.","Un salaire a augmenté.","Le chômage a augmenté."]},
          answer: 'Le chômage a augmenté.',
          explanation: 'It means "Unemployment has increased."',
        },
        {
          id: 'tr-25',
          learningItemId: 'poste',
          type: 'multiple_choice',
          stage: 'context',
          prompt: 'Quel terme décrit une position dans une entreprise?',
          content: {"options":["emploi","poste","salaire","contrat"]},
          answer: 'poste',
          explanation: '"Poste" means a position or post.',
        },
        {
          id: 'tr-26',
          learningItemId: 'poste',
          type: 'fill_blank',
          stage: 'recall',
          prompt: 'Elle travaille dans le _______ de la communication.',
          content: {"sentence":"Elle travaille dans le _______ de la communication.","options":["emploi","contrat","poste","salaire"]},
          answer: 'poste',
          explanation: 'The sentence means "She works in the communication post."',
        },
        {
          id: 'tr-27',
          learningItemId: 'contrat',
          type: 'translation',
          stage: 'recall',
          prompt: 'Translate: "Je signe un contrat d\'embauche."',
          content: {"options":["I sign a job contract.","I sign a salary contract.","I sign an unemployment contract.","I sign a contract of employment."]},
          answer: 'I sign a contract of employment.',
          explanation: 'It means signing a contract for employment.',
        },
        {
          id: 'tr-28',
          learningItemId: 'chomage',
          type: 'multiple_choice',
          stage: 'recognition',
          prompt: 'Which word means "unemployment"?',
          content: {"options":["emploi","contrat","salaire","chômage"]},
          answer: 'chômage',
          explanation: '"Chômage" means unemployment.',
        },
      ],
    },
    {
      id: 'travail-idees',
      title: 'Construire des idées',
      learningItemIds: ['conditionnel-politesse', 'je-voudrais', 'teletravail', 'entretien'],
      exercises: [
        {
          id: 'tr-7',
          learningItemId: 'conditionnel-politesse',
          type: 'multiple_choice',
          stage: 'recognition',
          prompt: 'Which sentence is correct in a job application?',
          content: { options: ['Je veux postuler à ce poste.', 'Je voudrais postuler à ce poste.'] },
          answer: 'Je voudrais postuler à ce poste.',
          explanation: 'The conditional "je voudrais" sounds polite and professional in formal requests.',
        },
        {
          id: 'tr-8',
          learningItemId: 'conditionnel-politesse',
          type: 'fill_blank',
          stage: 'transformation',
          prompt: 'Complete the sentence',
          content: {
            sentence: 'Je ______ postuler à ce poste.',
            options: ['voudrais', 'veux', 'voudrai', 'voulais'],
          },
          answer: 'voudrais',
          explanation: 'The conditional of "vouloir" is "voudrais" — the polite form for requests.',
        },
        {
          id: 'tr-9',
          learningItemId: 'teletravail',
          type: 'translation',
          stage: 'recall',
          prompt: 'Translate: remote work',
          content: { direction: 'en_to_fr', options: ['télétravail', 'travail manuel', 'chômage', 'entretien'] },
          answer: 'télétravail',
          explanation: '"Remote work" translates to "télétravail."',
        },
        {
          id: 'tr-10',
          learningItemId: 'je-voudrais',
          type: 'multiple_choice',
          stage: 'recognition',
          prompt: 'What does "Je voudrais" express?',
          content: { options: ['A polite request', 'A firm order', 'A past habit', 'A refusal'] },
          answer: 'A polite request',
          explanation: '"Je voudrais" ("I would like") softens a request into a polite form.',
        },
        {
          id: 'tr-11',
          learningItemId: 'teletravail',
          type: 'fill_blank',
          stage: 'context',
          prompt: 'Complete the sentence',
          content: {
            sentence: 'Le ______ est devenu courant depuis 2020.',
            options: ['télétravail', 'salaire', 'contrat', 'entretien'],
          },
          answer: 'télétravail',
          explanation: '"Le télétravail" is the practice of working from home or remotely.',
        },
        {
          id: 'tr-12',
          learningItemId: 'entretien',
          type: 'fill_blank',
          stage: 'context',
          prompt: 'Complete the sentence',
          content: {
            sentence: "Mon ______ d'embauche est jeudi.",
            options: ['entretien', 'emploi', 'poste', 'chômage'],
          },
          answer: 'entretien',
          explanation: 'A job interview is "un entretien (d\u2019embauche)."',
        },
      
        {
          id: 'tr-29',
          learningItemId: 'conditionnel-politesse',
          type: 'multiple_choice',
          stage: 'recognition',
          prompt: 'Choose the polite form of the request:',
          content: {"options":["Je veux envoyer mon CV.","Je voudrais envoyer mon CV."]},
          answer: 'Je voudrais envoyer mon CV.',
          explanation: 'The conditional form "voudrais" softens the request.',
        },
        {
          id: 'tr-30',
          learningItemId: 'je-voudrais',
          type: 'fill_blank',
          stage: 'recall',
          prompt: 'Complete with the correct form of "vouloir" for each subject:',
          content: {"sentence":"______ postuler à ce poste.","options":["Je voudrais","Tu voudrais","Il voudrait","Nous voudrions"]},
          answer: 'Je voudrais',
          explanation: 'First person singular conditional of vouloir.',
        },
        {
          id: 'tr-31',
          learningItemId: 'je-voudrais',
          type: 'translation',
          stage: 'context',
          prompt: 'Translate into French: "I would like to apply for this position."',
          content: {"options":["Je voudrais postuler à ce poste.","Je veux postuler à ce poste.","Je postulerais à ce poste.","Je postulais à ce poste."]},
          answer: 'Je voudrais postuler à ce poste.',
          explanation: 'The conditional expresses politeness.',
        },
        {
          id: 'tr-32',
          learningItemId: 'conditionnel-politesse',
          type: 'pronunciation',
          stage: 'production',
          prompt: 'Pronounce the full sentence:',
          content: {"sentence":"Pourriez-vous m'envoyer le détail du poste?"},
          answer: 'Pourriez-vous m\'envoyer le détail du poste?',
          explanation: 'Use the polite conditional form of pouvoir.',
        },
        {
          id: 'tr-33',
          learningItemId: 'conditionnel-politesse',
          type: 'multiple_choice',
          stage: 'recall',
          prompt: 'Which sentence uses the correct polite request for a phone call?',
          content: {"options":["Je veux vous appeler demain.","Pourriez-vous m'appeler demain?","Je voudrais vous appeler demain.","Je appelais vous demain."]},
          answer: 'Pourriez-vous m\'appeler demain?',
          explanation: 'The conditional form is used for polite requests.',
        },
        {
          id: 'tr-34',
          learningItemId: 'teletravail',
          type: 'fill_blank',
          stage: 'completion',
          prompt: 'Fill in the blank with the correct form of "télétravail" (noun):',
          content: {"sentence":"Le ______ est devenu courant.","options":["télétravail","télétravails","télétravaille","télétravaillez"]},
          answer: 'télétravail',
          explanation: 'Singular masculine noun.',
        },
        {
          id: 'tr-35',
          learningItemId: 'teletravail',
          type: 'translation',
          stage: 'context',
          prompt: 'Translate into French: "Remote work is becoming common."',
          content: {"options":["Le télétravail est devenu courant.","Le télétravail est devenu courante.","Les télétravaux sont courants.","Le télétravail est courante."]},
          answer: 'Le télétravail est devenu courant.',
          explanation: 'Singular masculine noun with correct agreement.',
        },
        {
          id: 'tr-36',
          learningItemId: 'entretien',
          type: 'multiple_choice',
          stage: 'recognition',
          prompt: 'Choose the correct noun for a job interview:',
          content: {"options":["entretien","entrevue","rendez-vous","rencontre"]},
          answer: 'entretien',
          explanation: '"Entretien" is the formal term for a job interview.',
        },
        {
          id: 'tr-37',
          learningItemId: 'entretien',
          type: 'fill_blank',
          stage: 'recall',
          prompt: 'Complete the sentence with the correct noun form:',
          content: {"sentence":"Mon ______ d'embauche est mercredi.","options":["entretien","entretiens","entretienne","entreve"]},
          answer: 'entretien',
          explanation: 'Singular masculine noun.',
        },
      ],
    },
    {
      id: 'travail-argumenter',
      title: 'Argumenter sur le travail',
      learningItemIds: ['en-ce-qui-concerne', 'a-temps-partiel'],
      exercises: [
        {
          id: 'tr-13',
          learningItemId: 'en-ce-qui-concerne',
          type: 'multiple_choice',
          stage: 'recognition',
          prompt: 'What does "En ce qui concerne" mean?',
          content: { options: ['Regarding', 'By the way', 'Afterwards', 'Nevertheless'] },
          answer: 'Regarding',
          explanation: '"En ce qui concerne" introduces the aspect you are about to discuss — "regarding."',
        },
        {
          id: 'tr-14',
          learningItemId: 'en-ce-qui-concerne',
          type: 'fill_blank',
          stage: 'context',
          prompt: 'Complete the sentence',
          content: {
            sentence: "______ le salaire, c'est négociable.",
            options: ['En ce qui concerne', 'Par contre', 'D\u2019abord', 'Au fait'],
          },
          answer: 'En ce qui concerne',
          explanation: '"En ce qui concerne" opens a switch to a new aspect of the topic.',
        },
        {
          id: 'tr-15',
          learningItemId: 'a-temps-partiel',
          type: 'multiple_choice',
          stage: 'recognition',
          prompt: 'What does "À temps partiel" mean?',
          content: { options: ['Part-time', 'Full-time', 'On schedule', 'Overtime'] },
          answer: 'Part-time',
          explanation: 'Working "à temps partiel" means working reduced hours.',
        },
        {
          id: 'tr-16',
          learningItemId: 'a-temps-partiel',
          type: 'fill_blank',
          stage: 'context',
          prompt: 'Complete the sentence',
          content: {
            sentence: 'Il travaille ______ partiel pour finir ses études.',
            options: ['à temps', 'en temps', 'de temps', 'sur temps'],
          },
          answer: 'à temps',
          explanation: 'The fixed expression is "à temps partiel."',
        },
        {
          id: 'tr-17',
          learningItemId: 'je-voudrais',
          type: 'pronunciation',
          stage: 'production',
          prompt: 'Say the sentence aloud.',
          content: { sentence: 'Je voudrais postuler à ce poste.' },
          answer: 'Je voudrais postuler à ce poste.',
          explanation: '"Je voudrais" opens the polite request, then the infinitive follows.',
        },
        {
          id: 'tr-18',
          learningItemId: 'en-ce-qui-concerne',
          type: 'pronunciation',
          stage: 'production',
          prompt: 'Say the sentence aloud.',
          content: { sentence: "En ce qui concerne le salaire, c'est négociable." },
          answer: "En ce qui concerne le salaire, c'est négociable.",
          explanation: '"En ce qui concerne" introduces the subject, then the comment follows.',
        },
      ],
    },
  ],
}

export const items = {
  emploi: {
    id: 'emploi',
    type: 'vocabulary',
    word: 'emploi',
    meaning: 'job',
    partOfSpeech: 'noun (m.)',
    level: 'B1',
    topic: 'Le travail',
    example: 'Elle cherche un emploi stable.',
    related: ['poste', 'travail', 'métier'],
  },
  contrat: {
    id: 'contrat',
    type: 'vocabulary',
    word: 'contrat',
    meaning: 'contract',
    partOfSpeech: 'noun (m.)',
    level: 'B1',
    topic: 'Le travail',
    example: 'Il a signé un contrat à durée indéterminée.',
    related: ['accord', 'document'],
  },
  salaire: {
    id: 'salaire',
    type: 'vocabulary',
    word: 'salaire',
    meaning: 'salary',
    partOfSpeech: 'noun (m.)',
    level: 'B1',
    topic: 'Le travail',
    example: "Le salaire est négocié lors de l'entretien.",
    related: ['revenu', 'rémunération'],
  },
  teletravail: {
    id: 'teletravail',
    type: 'vocabulary',
    word: 'télétravail',
    meaning: 'remote work',
    partOfSpeech: 'noun (m.)',
    level: 'B1',
    topic: 'Le travail',
    example: 'Le télétravail est devenu courant.',
    related: ['travail à distance'],
  },
  chomage: {
    id: 'chomage',
    type: 'vocabulary',
    word: 'chômage',
    meaning: 'unemployment',
    partOfSpeech: 'noun (m.)',
    level: 'B1',
    topic: 'Le travail',
    example: 'Le chômage a baissé cette année.',
    related: ['emploi'],
  },
  poste: {
    id: 'poste',
    type: 'vocabulary',
    word: 'poste',
    meaning: 'position / post',
    partOfSpeech: 'noun (m.)',
    level: 'B1',
    topic: 'Le travail',
    example: 'Ce poste exige un bon niveau de français.',
    related: ['emploi', 'métier'],
  },
  entretien: {
    id: 'entretien',
    type: 'vocabulary',
    word: 'entretien',
    meaning: 'job interview',
    partOfSpeech: 'noun (m.)',
    level: 'B1',
    topic: 'Le travail',
    example: "Mon entretien d'embauche est mercredi.",
    related: ['rendez-vous', 'entrevue'],
  },

  'je-voudrais': {
    id: 'je-voudrais',
    type: 'phrase',
    phrase: 'Je voudrais',
    meaning: 'I would like',
    function: 'Polite request',
    level: 'B1',
    topic: 'Le travail',
    tefUsage: 'Expression orale — demande polie',
    example: 'Je voudrais postuler à ce poste.',
    related: ['Pourriez-vous', "J'aimerais"],
    conjugation: {
      je: 'voudrais',
      tu: 'voudrais',
      ilElle: 'voudrait',
      nous: 'voudrions',
      vous: 'voudriez',
      ilsElles: 'voudraient',
    },
    tense: 'conditional',
  },
  'en-ce-qui-concerne': {
    id: 'en-ce-qui-concerne',
    type: 'phrase',
    phrase: 'En ce qui concerne',
    meaning: 'Regarding / As for',
    function: 'Introducing a topic',
    level: 'B1',
    topic: 'Le travail',
    tefUsage: 'Expression orale / écrite — structurer',
    example: "En ce qui concerne le salaire, c'est négociable.",
    related: ['Quant à', 'À propos de'],
  },
  'a-temps-partiel': {
    id: 'a-temps-partiel',
    type: 'phrase',
    phrase: 'À temps partiel',
    meaning: 'Part-time',
    function: 'Describing work arrangements',
    level: 'B1',
    topic: 'Le travail',
    tefUsage: 'Expression orale — décrire un emploi',
    example: 'Il travaille à temps partiel pour finir ses études.',
    related: ['À temps plein'],
  },

  'conditionnel-politesse': {
    id: 'conditionnel-politesse',
    type: 'grammar',
    title: 'The conditional for polite requests',
    level: 'B1',
    explanation:
      'The conditional softens requests and proposals — ideal for interviews, phone calls, and job hunts: je voudrais, on pourrait, pourriez-vous.',
    examples: [
      'Je voudrais postuler à ce poste.',
      'Pourriez-vous renvoyer mon contrat ?',
      'On pourrait fixer un entretien la semaine prochaine.',
    ],
    counterexamples: [
      'Je veux postuler à ce poste. (too direct for a formal request — use "je voudrais")',
    ],
  },
}