// Hand-authored TEF theme unit (spec §3.2.1) — "Le travail" (Work). One of the fourteen official
// TEF themes covered by the Learn path. Exports the same { unit, items } shape as the generated
// units (spec §3.2.6). All exercises are tap-only (spec §3.2.2).

export const unit = {
  id: 'travail',
  title: 'Le travail',
  description: 'Talk about jobs, work situations, and employment — a core theme on the TEF.',
  lessons: [
    {
      id: 'travail-vocabulaire',
      title: 'Vocabulaire du travail',
      learningItemIds: ['emploi', 'contrat', 'salaire', 'chomage', 'poste'],
      exercises: [
        {
          id: 'tr-1',
          learningItemId: 'emploi',
          type: 'multiple_choice',
          stage: 'recognition',
          prompt: 'What does "un emploi" mean?',
          content: { options: ['a job', 'a salary', 'a boss', 'a schedule'] },
          answer: 'a job',
          explanation: '"Un emploi" means a "job" or "employment."',
        },
        {
          id: 'tr-2',
          learningItemId: 'chomage',
          type: 'multiple_choice',
          stage: 'recognition',
          prompt: 'What does "le chômage" mean?',
          content: { options: ['unemployment', 'part-time work', 'a promotion', 'a contract'] },
          answer: 'unemployment',
          explanation: '"Le chômage" means "unemployment" — the state of being without a job.',
        },
        {
          id: 'tr-3',
          learningItemId: 'contrat',
          type: 'translation',
          stage: 'recall',
          prompt: 'Translate: contract',
          content: { direction: 'en_to_fr', options: ['contrat', 'salaire', 'poste', 'entretien'] },
          answer: 'contrat',
          explanation: '"Contract" translates to "contrat."',
        },
        {
          id: 'tr-4',
          learningItemId: 'salaire',
          type: 'translation',
          stage: 'recall',
          prompt: 'Translate: salary',
          content: { direction: 'en_to_fr', options: ['salaire', 'emploi', 'chômage', 'contrat'] },
          answer: 'salaire',
          explanation: '"Salary" translates to "salaire."',
        },
        {
          id: 'tr-5',
          learningItemId: 'emploi',
          type: 'fill_blank',
          stage: 'context',
          prompt: 'Complete the sentence',
          content: {
            sentence: 'Elle ______ un emploi stable.',
            options: ['cherche', 'cherchent', 'cherchons', 'cherches'],
          },
          answer: 'cherche',
          explanation: 'Subject "elle" takes the third-person singular form "cherche."',
        },
        {
          id: 'tr-6',
          learningItemId: 'contrat',
          type: 'fill_blank',
          stage: 'context',
          prompt: 'Complete the sentence',
          content: {
            sentence: 'Il a signé un ______ à durée indéterminée.',
            options: ['contrat', 'salaire', 'poste', 'chômage'],
          },
          answer: 'contrat',
          explanation: 'A "contrat" fixes the terms of an employment relationship.',
        },
      ],
    },
    {
      id: 'travail-idees',
      title: 'Construire des idées',
      learningItemIds: ['conditionnel-politesse', 'je-voudrais', 'teletravail', 'entretien'],
      exercises: [
        {
          id: 'tr-7',
          learningItemId: 'conditionnel-politesse',
          type: 'multiple_choice',
          stage: 'recognition',
          prompt: 'Which sentence is correct in a job application?',
          content: { options: ['Je veux postuler à ce poste.', 'Je voudrais postuler à ce poste.'] },
          answer: 'Je voudrais postuler à ce poste.',
          explanation: 'The conditional "je voudrais" sounds polite and professional in formal requests.',
        },
        {
          id: 'tr-8',
          learningItemId: 'conditionnel-politesse',
          type: 'fill_blank',
          stage: 'transformation',
          prompt: 'Complete the sentence',
          content: {
            sentence: 'Je ______ postuler à ce poste.',
            options: ['voudrais', 'veux', 'voudrai', 'voulais'],
          },
          answer: 'voudrais',
          explanation: 'The conditional of "vouloir" is "voudrais" — the polite form for requests.',
        },
        {
          id: 'tr-9',
          learningItemId: 'teletravail',
          type: 'translation',
          stage: 'recall',
          prompt: 'Translate: remote work',
          content: { direction: 'en_to_fr', options: ['télétravail', 'travail manuel', 'chômage', 'entretien'] },
          answer: 'télétravail',
          explanation: '"Remote work" translates to "télétravail."',
        },
        {
          id: 'tr-10',
          learningItemId: 'je-voudrais',
          type: 'multiple_choice',
          stage: 'recognition',
          prompt: 'What does "Je voudrais" express?',
          content: { options: ['A polite request', 'A firm order', 'A past habit', 'A refusal'] },
          answer: 'A polite request',
          explanation: '"Je voudrais" ("I would like") softens a request into a polite form.',
        },
        {
          id: 'tr-11',
          learningItemId: 'teletravail',
          type: 'fill_blank',
          stage: 'context',
          prompt: 'Complete the sentence',
          content: {
            sentence: 'Le ______ est devenu courant depuis 2020.',
            options: ['télétravail', 'salaire', 'contrat', 'entretien'],
          },
          answer: 'télétravail',
          explanation: '"Le télétravail" is the practice of working from home or remotely.',
        },
        {
          id: 'tr-12',
          learningItemId: 'entretien',
          type: 'fill_blank',
          stage: 'context',
          prompt: 'Complete the sentence',
          content: {
            sentence: "Mon ______ d'embauche est jeudi.",
            options: ['entretien', 'emploi', 'poste', 'chômage'],
          },
          answer: 'entretien',
          explanation: 'A job interview is "un entretien (d\u2019embauche)."',
        },
      ],
    },
    {
      id: 'travail-argumenter',
      title: 'Argumenter sur le travail',
      learningItemIds: ['en-ce-qui-concerne', 'a-temps-partiel'],
      exercises: [
        {
          id: 'tr-13',
          learningItemId: 'en-ce-qui-concerne',
          type: 'multiple_choice',
          stage: 'recognition',
          prompt: 'What does "En ce qui concerne" mean?',
          content: { options: ['Regarding', 'By the way', 'Afterwards', 'Nevertheless'] },
          answer: 'Regarding',
          explanation: '"En ce qui concerne" introduces the aspect you are about to discuss — "regarding."',
        },
        {
          id: 'tr-14',
          learningItemId: 'en-ce-qui-concerne',
          type: 'fill_blank',
          stage: 'context',
          prompt: 'Complete the sentence',
          content: {
            sentence: "______ le salaire, c'est négociable.",
            options: ['En ce qui concerne', 'Par contre', 'D\u2019abord', 'Au fait'],
          },
          answer: 'En ce qui concerne',
          explanation: '"En ce qui concerne" opens a switch to a new aspect of the topic.',
        },
        {
          id: 'tr-15',
          learningItemId: 'a-temps-partiel',
          type: 'multiple_choice',
          stage: 'recognition',
          prompt: 'What does "À temps partiel" mean?',
          content: { options: ['Part-time', 'Full-time', 'On schedule', 'Overtime'] },
          answer: 'Part-time',
          explanation: 'Working "à temps partiel" means working reduced hours.',
        },
        {
          id: 'tr-16',
          learningItemId: 'a-temps-partiel',
          type: 'fill_blank',
          stage: 'context',
          prompt: 'Complete the sentence',
          content: {
            sentence: 'Il travaille ______ partiel pour finir ses études.',
            options: ['à temps', 'en temps', 'de temps', 'sur temps'],
          },
          answer: 'à temps',
          explanation: 'The fixed expression is "à temps partiel."',
        },
        {
          id: 'tr-17',
          learningItemId: 'je-voudrais',
          type: 'production',
          stage: 'production',
          prompt: 'Build the sentence: "Je voudrais postuler à ce poste."',
          content: { tiles: ['Je', 'voudrais', 'postuler', 'à', 'ce', 'poste.', 'veux', 'emploi'] },
          answer: 'Je voudrais postuler à ce poste.',
          explanation: '"Je voudrais" opens the polite request, then the infinitive follows.',
        },
        {
          id: 'tr-18',
          learningItemId: 'en-ce-qui-concerne',
          type: 'production',
          stage: 'production',
          prompt: 'Build the sentence: "En ce qui concerne le salaire, c\u2019est négociable."',
          content: {
            tiles: ['En', 'ce', 'qui', 'concerne', 'le', 'salaire,', "c'est", 'négociable.', 'Par', 'contre'],
          },
          answer: "En ce qui concerne le salaire, c'est négociable.",
          explanation: '"En ce qui concerne" introduces the subject, then the comment follows.',
        },
      ],
    },
  ],
}

export const items = {
  emploi: {
    id: 'emploi',
    type: 'vocabulary',
    word: 'emploi',
    meaning: 'job',
    partOfSpeech: 'noun (m.)',
    level: 'B1',
    topic: 'Le travail',
    example: 'Elle cherche un emploi stable.',
    related: ['poste', 'travail', 'métier'],
  },
  contrat: {
    id: 'contrat',
    type: 'vocabulary',
    word: 'contrat',
    meaning: 'contract',
    partOfSpeech: 'noun (m.)',
    level: 'B1',
    topic: 'Le travail',
    example: 'Il a signé un contrat à durée indéterminée.',
    related: ['accord', 'document'],
  },
  salaire: {
    id: 'salaire',
    type: 'vocabulary',
    word: 'salaire',
    meaning: 'salary',
    partOfSpeech: 'noun (m.)',
    level: 'B1',
    topic: 'Le travail',
    example: "Le salaire est négocié lors de l'entretien.",
    related: ['revenu', 'rémunération'],
  },
  teletravail: {
    id: 'teletravail',
    type: 'vocabulary',
    word: 'télétravail',
    meaning: 'remote work',
    partOfSpeech: 'noun (m.)',
    level: 'B1',
    topic: 'Le travail',
    example: 'Le télétravail est devenu courant.',
    related: ['travail à distance'],
  },
  chomage: {
    id: 'chomage',
    type: 'vocabulary',
    word: 'chômage',
    meaning: 'unemployment',
    partOfSpeech: 'noun (m.)',
    level: 'B1',
    topic: 'Le travail',
    example: 'Le chômage a baissé cette année.',
    related: ['emploi'],
  },
  poste: {
    id: 'poste',
    type: 'vocabulary',
    word: 'poste',
    meaning: 'position / post',
    partOfSpeech: 'noun (m.)',
    level: 'B1',
    topic: 'Le travail',
    example: 'Ce poste exige un bon niveau de français.',
    related: ['emploi', 'métier'],
  },
  entretien: {
    id: 'entretien',
    type: 'vocabulary',
    word: 'entretien',
    meaning: 'job interview',
    partOfSpeech: 'noun (m.)',
    level: 'B1',
    topic: 'Le travail',
    example: "Mon entretien d'embauche est mercredi.",
    related: ['rendez-vous', 'entrevue'],
  },

  'je-voudrais': {
    id: 'je-voudrais',
    type: 'phrase',
    phrase: 'Je voudrais',
    meaning: 'I would like',
    function: 'Polite request',
    level: 'B1',
    topic: 'Le travail',
    tefUsage: 'Expression orale — demande polie',
    example: 'Je voudrais postuler à ce poste.',
    related: ['Pourriez-vous', "J'aimerais"],
  },
  'en-ce-qui-concerne': {
    id: 'en-ce-qui-concerne',
    type: 'phrase',
    phrase: 'En ce qui concerne',
    meaning: 'Regarding / As for',
    function: 'Introducing a topic',
    level: 'B1',
    topic: 'Le travail',
    tefUsage: 'Expression orale / écrite — structurer',
    example: "En ce qui concerne le salaire, c'est négociable.",
    related: ['Quant à', 'À propos de'],
  },
  'a-temps-partiel': {
    id: 'a-temps-partiel',
    type: 'phrase',
    phrase: 'À temps partiel',
    meaning: 'Part-time',
    function: 'Describing work arrangements',
    level: 'B1',
    topic: 'Le travail',
    tefUsage: 'Expression orale — décrire un emploi',
    example: 'Il travaille à temps partiel pour finir ses études.',
    related: ['À temps plein'],
  },

  'conditionnel-politesse': {
    id: 'conditionnel-politesse',
    type: 'grammar',
    title: 'The conditional for polite requests',
    level: 'B1',
    explanation:
      'The conditional softens requests and proposals — ideal for interviews, phone calls, and job hunts: je voudrais, on pourrait, pourriez-vous.',
    examples: [
      'Je voudrais postuler à ce poste.',
      'Pourriez-vous renvoyer mon contrat ?',
      'On pourrait fixer un entretien la semaine prochaine.',
    ],
    counterexamples: [
      'Je veux postuler à ce poste. (too direct for a formal request — use "je voudrais")',
    ],
  },
}